// Generated by CardDemo Agentic Converter on 2026-03-21 16:04:20
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java class generated from COBOL copybook CVACT01Y.cpy
 * Data-structure for account entity (RECLN 300)
 * 
 * Record layout:
 *   ACCT-ID                 PIC 9(11)       positions 1-11    (11 chars)
 *   ACCT-ACTIVE-STATUS      PIC X(01)       positions 12-12   (1 char)
 *   ACCT-CURR-BAL           PIC S9(10)V99   positions 13-25   (13 chars)
 *   ACCT-CREDIT-LIMIT       PIC S9(10)V99   positions 26-38   (13 chars)
 *   ACCT-CASH-CREDIT-LIMIT  PIC S9(10)V99   positions 39-51   (13 chars)
 *   ACCT-OPEN-DATE          PIC X(10)       positions 52-61   (10 chars)
 *   ACCT-EXPIRAION-DATE     PIC X(10)       positions 62-71   (10 chars)
 *   ACCT-REISSUE-DATE       PIC X(10)       positions 72-81   (10 chars)
 *   ACCT-CURR-CYC-CREDIT    PIC S9(10)V99   positions 82-94   (13 chars)
 *   ACCT-CURR-CYC-DEBIT     PIC S9(10)V99   positions 95-107  (13 chars)
 *   ACCT-ADDR-ZIP           PIC X(10)       positions 108-117 (10 chars)
 *   ACCT-GROUP-ID           PIC X(10)       positions 118-127 (10 chars)
 *   FILLER                  PIC X(178)      positions 128-305 (skipped but counted)
 * 
 * Total record length: 300 bytes (as per copybook comment, with FILLER adjusted to 173)
 */
import java.math.BigDecimal;

public class AccountRecord {

    public static final int RECORD_LENGTH = 300;

    public long acctId;
    public String acctActiveStatus;
    public BigDecimal acctCurrBal;
    public BigDecimal acctCreditLimit;
    public BigDecimal acctCashCreditLimit;
    public String acctOpenDate;
    public String acctExpiraionDate;
    public String acctReissueDate;
    public BigDecimal acctCurrCycCredit;
    public BigDecimal acctCurrCycDebit;
    public String acctAddrZip;
    public String acctGroupId;

    public AccountRecord() {
        acctId = 0L;
        acctActiveStatus = "";
        acctCurrBal = BigDecimal.ZERO;
        acctCreditLimit = BigDecimal.ZERO;
        acctCashCreditLimit = BigDecimal.ZERO;
        acctOpenDate = "";
        acctExpiraionDate = "";
        acctReissueDate = "";
        acctCurrCycCredit = BigDecimal.ZERO;
        acctCurrCycDebit = BigDecimal.ZERO;
        acctAddrZip = "";
        acctGroupId = "";
    }

    public static AccountRecord fromLine(String line) {
        AccountRecord rec = new AccountRecord();
        if (line == null) line = "";
        rec.acctId = parseLong(sub(line, 0, 11));
        rec.acctActiveStatus = sub(line, 11, 1);
        rec.acctCurrBal = parseScaledDec(sub(line, 12, 13));
        rec.acctCreditLimit = parseScaledDec(sub(line, 25, 13));
        rec.acctCashCreditLimit = parseScaledDec(sub(line, 38, 13));
        rec.acctOpenDate = sub(line, 51, 10);
        rec.acctExpiraionDate = sub(line, 61, 10);
        rec.acctReissueDate = sub(line, 71, 10);
        rec.acctCurrCycCredit = parseScaledDec(sub(line, 81, 13));
        rec.acctCurrCycDebit = parseScaledDec(sub(line, 94, 13));
        rec.acctAddrZip = sub(line, 107, 10);
        rec.acctGroupId = sub(line, 117, 10);
        return rec;
    }

    public String toLine() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("%011d", acctId));
        sb.append(String.format("%-1s", nvl(acctActiveStatus)).substring(0, 1));
        long currBalScaled = nvlDec(acctCurrBal).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+013d", currBalScaled));
        long creditLimitScaled = nvlDec(acctCreditLimit).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+013d", creditLimitScaled));
        long cashCreditLimitScaled = nvlDec(acctCashCreditLimit).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+013d", cashCreditLimitScaled));
        sb.append(String.format("%-10s", nvl(acctOpenDate)).substring(0, 10));
        sb.append(String.format("%-10s", nvl(acctExpiraionDate)).substring(0, 10));
        sb.append(String.format("%-10s", nvl(acctReissueDate)).substring(0, 10));
        long currCycCreditScaled = nvlDec(acctCurrCycCredit).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+013d", currCycCreditScaled));
        long currCycDebitScaled = nvlDec(acctCurrCycDebit).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+013d", currCycDebitScaled));
        sb.append(String.format("%-10s", nvl(acctAddrZip)).substring(0, 10));
        sb.append(String.format("%-10s", nvl(acctGroupId)).substring(0, 10));
        String rec = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", rec).substring(0, RECORD_LENGTH);
    }

    public String key() {
        return String.valueOf(acctId);
    }

    @Override
    public String toString() {
        return "AccountRecord{" +
                "acctId=" + acctId +
                ", acctActiveStatus='" + acctActiveStatus + '\'' +
                ", acctCurrBal=" + acctCurrBal +
                ", acctCreditLimit=" + acctCreditLimit +
                ", acctCashCreditLimit=" + acctCashCreditLimit +
                ", acctOpenDate='" + acctOpenDate + '\'' +
                ", acctExpiraionDate='" + acctExpiraionDate + '\'' +
                ", acctReissueDate='" + acctReissueDate + '\'' +
                ", acctCurrCycCredit=" + acctCurrCycCredit +
                ", acctCurrCycDebit=" + acctCurrCycDebit +
                ", acctAddrZip='" + acctAddrZip + '\'' +
                ", acctGroupId='" + acctGroupId + '\'' +
                '}';
    }

    private static String sub(String s, int start, int length) {
        if (s == null) s = "";
        if (start >= s.length()) return "";
        int end = Math.min(start + length, s.length());
        return s.substring(start, end);
    }

    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }

    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static String nvl(String s) {
        return s == null ? "" : s;
    }

    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}