// Generated by CardDemo Agentic Converter on 2026-03-21 16:05:56
// Source: AWS CardDemo (Apache 2.0)

/**
 * Data-structure for card xref (RECLN 50)
 * 
 * Generated from COBOL copybook: CVACT03Y.cpy
 * Record length: 50 bytes
 */
import java.math.BigDecimal;

public class CardXrefRecord {
    
    public static final int RECORD_LENGTH = 50;
    
    // PIC X(16) - Card number
    public String xrefCardNum;
    
    // PIC 9(09) - Customer ID
    public long xrefCustId;
    
    // PIC 9(11) - Account ID
    public long xrefAcctId;
    
    // FILLER PIC X(14) - not mapped
    
    /**
     * Parse a fixed-length string into record fields
     */
    public static CardXrefRecord fromLine(String line) {
        CardXrefRecord rec = new CardXrefRecord();
        if (line == null) line = "";
        
        // Offset 0: XREF-CARD-NUM PIC X(16)
        rec.xrefCardNum = sub(line, 0, 16);
        
        // Offset 16: XREF-CUST-ID PIC 9(09)
        rec.xrefCustId = parseLong(sub(line, 16, 9));
        
        // Offset 25: XREF-ACCT-ID PIC 9(11)
        rec.xrefAcctId = parseLong(sub(line, 25, 11));
        
        // Offset 36: FILLER PIC X(14) - skipped
        
        return rec;
    }
    
    /**
     * Serialize record to fixed-length string
     */
    public String toLine() {
        StringBuilder sb = new StringBuilder();
        
        // XREF-CARD-NUM PIC X(16)
        sb.append(String.format("%-16s", nvl(xrefCardNum)).substring(0, 16));
        
        // XREF-CUST-ID PIC 9(09)
        sb.append(String.format("%09d", xrefCustId));
        
        // XREF-ACCT-ID PIC 9(11)
        sb.append(String.format("%011d", xrefAcctId));
        
        // FILLER PIC X(14)
        sb.append(String.format("%-14s", "").substring(0, 14));
        
        String result = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
    }
    
    /**
     * Return the VSAM key field(s) as a String (card number is the key)
     */
    public String key() {
        return nvl(xrefCardNum).trim();
    }
    
    /**
     * Human readable summary
     */
    @Override
    public String toString() {
        return "CardXrefRecord{" +
                "xrefCardNum='" + xrefCardNum + '\'' +
                ", xrefCustId=" + xrefCustId +
                ", xrefAcctId=" + xrefAcctId +
                '}';
    }
    
    // ========== Inline Utility Methods ==========
    
    private static String sub(String s, int start, int length) {
        if (s == null) s = "";
        if (start >= s.length()) return String.format("%-" + length + "s", "");
        int end = Math.min(start + length, s.length());
        String result = s.substring(start, end);
        if (result.length() < length) {
            result = String.format("%-" + length + "s", result);
        }
        return result;
    }
    
    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }
    
    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static String nvl(String s) {
        return s == null ? "" : s;
    }
    
    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}