// Generated by CardDemo Agentic Converter on 2026-03-21 16:05:13
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java representation of COBOL copybook: CVACT02Y.cpy
 * Data-structure for card entity (RECLN 150)
 * 
 * Generated from CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:16:00 CDT
 */
import java.math.BigDecimal;

public class CardRecord {

    public static final int RECORD_LENGTH = 150;

    // PIC X(16)
    public String cardNum;
    // PIC 9(11)
    public long cardAcctId;
    // PIC 9(03)
    public int cardCvvCd;
    // PIC X(50)
    public String cardEmbossedName;
    // PIC X(10)
    public String cardExpirationDate;
    // PIC X(01)
    public String cardActiveStatus;
    // FILLER PIC X(59) - skipped

    public CardRecord() {
        this.cardNum = "";
        this.cardAcctId = 0L;
        this.cardCvvCd = 0;
        this.cardEmbossedName = "";
        this.cardExpirationDate = "";
        this.cardActiveStatus = "";
    }

    public static CardRecord fromLine(String line) {
        CardRecord rec = new CardRecord();
        if (line == null) line = "";
        // Pad line to RECORD_LENGTH if needed
        if (line.length() < RECORD_LENGTH) {
            line = String.format("%-" + RECORD_LENGTH + "s", line);
        }
        int offset = 0;
        // CARD-NUM PIC X(16) offset 0-16
        rec.cardNum = sub(line, offset, 16);
        offset += 16;
        // CARD-ACCT-ID PIC 9(11) offset 16-27
        rec.cardAcctId = parseLong(sub(line, offset, 11));
        offset += 11;
        // CARD-CVV-CD PIC 9(03) offset 27-30
        rec.cardCvvCd = parseInt(sub(line, offset, 3));
        offset += 3;
        // CARD-EMBOSSED-NAME PIC X(50) offset 30-80
        rec.cardEmbossedName = sub(line, offset, 50);
        offset += 50;
        // CARD-EXPIRAION-DATE PIC X(10) offset 80-90
        rec.cardExpirationDate = sub(line, offset, 10);
        offset += 10;
        // CARD-ACTIVE-STATUS PIC X(01) offset 90-91
        rec.cardActiveStatus = sub(line, offset, 1);
        // FILLER PIC X(59) offset 91-150 - skipped
        return rec;
    }

    public String toLine() {
        StringBuilder sb = new StringBuilder();
        // CARD-NUM PIC X(16)
        sb.append(String.format("%-16s", nvl(cardNum)).substring(0, 16));
        // CARD-ACCT-ID PIC 9(11)
        sb.append(String.format("%011d", cardAcctId));
        // CARD-CVV-CD PIC 9(03)
        sb.append(String.format("%03d", cardCvvCd));
        // CARD-EMBOSSED-NAME PIC X(50)
        sb.append(String.format("%-50s", nvl(cardEmbossedName)).substring(0, 50));
        // CARD-EXPIRAION-DATE PIC X(10)
        sb.append(String.format("%-10s", nvl(cardExpirationDate)).substring(0, 10));
        // CARD-ACTIVE-STATUS PIC X(01)
        sb.append(String.format("%-1s", nvl(cardActiveStatus)).substring(0, 1));
        // FILLER PIC X(59)
        sb.append(String.format("%-59s", ""));
        String rec = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", rec).substring(0, RECORD_LENGTH);
    }

    public String key() {
        return nvl(cardNum).trim();
    }

    @Override
    public String toString() {
        return "CardRecord{" +
                "cardNum='" + cardNum + '\'' +
                ", cardAcctId=" + cardAcctId +
                ", cardCvvCd=" + cardCvvCd +
                ", cardEmbossedName='" + cardEmbossedName + '\'' +
                ", cardExpirationDate='" + cardExpirationDate + '\'' +
                ", cardActiveStatus='" + cardActiveStatus + '\'' +
                '}';
    }

    private static String sub(String s, int start, int length) {
        if (s == null) return spaces(length);
        if (start >= s.length()) return spaces(length);
        int end = Math.min(start + length, s.length());
        String result = s.substring(start, end);
        if (result.length() < length) {
            result = result + spaces(length - result.length());
        }
        return result;
    }

    private static String spaces(int n) {
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++) sb.append(' ');
        return sb.toString();
    }

    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }

    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static String nvl(String s) {
        return s == null ? "" : s;
    }

    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}