// Generated by CardDemo Agentic Converter on 2026-03-21 16:06:49
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java representation of COBOL copybook CVCUS01Y.cpy
 * Data-structure for Customer entity (RECLN 500)
 * 
 * Generated from COBOL copybook: CVCUS01Y.cpy
 * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:16:00 CDT
 */
import java.math.BigDecimal;

public class CustomerRecord {
    
    public static final int RECORD_LENGTH = 500;
    
    // PIC 9(09) - 9 bytes
    public long custId;
    // PIC X(25) - 25 bytes
    public String custFirstName;
    // PIC X(25) - 25 bytes
    public String custMiddleName;
    // PIC X(25) - 25 bytes
    public String custLastName;
    // PIC X(50) - 50 bytes
    public String custAddrLine1;
    // PIC X(50) - 50 bytes
    public String custAddrLine2;
    // PIC X(50) - 50 bytes
    public String custAddrLine3;
    // PIC X(02) - 2 bytes
    public String custAddrStateCd;
    // PIC X(03) - 3 bytes
    public String custAddrCountryCd;
    // PIC X(10) - 10 bytes
    public String custAddrZip;
    // PIC X(15) - 15 bytes
    public String custPhoneNum1;
    // PIC X(15) - 15 bytes
    public String custPhoneNum2;
    // PIC 9(09) - 9 bytes
    public long custSsn;
    // PIC X(20) - 20 bytes
    public String custGovtIssuedId;
    // PIC X(10) - 10 bytes
    public String custDobYyyyMmDd;
    // PIC X(10) - 10 bytes
    public String custEftAccountId;
    // PIC X(01) - 1 byte
    public String custPriCardHolderInd;
    // PIC 9(03) - 3 bytes
    public int custFicoCreditScore;
    // FILLER PIC X(168) - 168 bytes - SKIPPED
    
    public CustomerRecord() {
        custId = 0L;
        custFirstName = "";
        custMiddleName = "";
        custLastName = "";
        custAddrLine1 = "";
        custAddrLine2 = "";
        custAddrLine3 = "";
        custAddrStateCd = "";
        custAddrCountryCd = "";
        custAddrZip = "";
        custPhoneNum1 = "";
        custPhoneNum2 = "";
        custSsn = 0L;
        custGovtIssuedId = "";
        custDobYyyyMmDd = "";
        custEftAccountId = "";
        custPriCardHolderInd = "";
        custFicoCreditScore = 0;
    }
    
    public static CustomerRecord fromLine(String line) {
        CustomerRecord rec = new CustomerRecord();
        if (line == null) line = "";
        // Pad line to RECORD_LENGTH if needed
        if (line.length() < RECORD_LENGTH) {
            line = String.format("%-" + RECORD_LENGTH + "s", line);
        }
        
        int pos = 0;
        rec.custId = parseLong(sub(line, pos, 9));                    pos += 9;   // 0-8
        rec.custFirstName = sub(line, pos, 25);                       pos += 25;  // 9-33
        rec.custMiddleName = sub(line, pos, 25);                      pos += 25;  // 34-58
        rec.custLastName = sub(line, pos, 25);                        pos += 25;  // 59-83
        rec.custAddrLine1 = sub(line, pos, 50);                       pos += 50;  // 84-133
        rec.custAddrLine2 = sub(line, pos, 50);                       pos += 50;  // 134-183
        rec.custAddrLine3 = sub(line, pos, 50);                       pos += 50;  // 184-233
        rec.custAddrStateCd = sub(line, pos, 2);                      pos += 2;   // 234-235
        rec.custAddrCountryCd = sub(line, pos, 3);                    pos += 3;   // 236-238
        rec.custAddrZip = sub(line, pos, 10);                         pos += 10;  // 239-248
        rec.custPhoneNum1 = sub(line, pos, 15);                       pos += 15;  // 249-263
        rec.custPhoneNum2 = sub(line, pos, 15);                       pos += 15;  // 264-278
        rec.custSsn = parseLong(sub(line, pos, 9));                   pos += 9;   // 279-287
        rec.custGovtIssuedId = sub(line, pos, 20);                    pos += 20;  // 288-307
        rec.custDobYyyyMmDd = sub(line, pos, 10);                     pos += 10;  // 308-317
        rec.custEftAccountId = sub(line, pos, 10);                    pos += 10;  // 318-327
        rec.custPriCardHolderInd = sub(line, pos, 1);                 pos += 1;   // 328
        rec.custFicoCreditScore = parseInt(sub(line, pos, 3));        pos += 3;   // 329-331
        // FILLER: 168 bytes at pos 332-499
        
        return rec;
    }
    
    public String toLine() {
        StringBuilder sb = new StringBuilder(RECORD_LENGTH);
        
        sb.append(String.format("%09d", custId));
        sb.append(String.format("%-25s", nvl(custFirstName)).substring(0, 25));
        sb.append(String.format("%-25s", nvl(custMiddleName)).substring(0, 25));
        sb.append(String.format("%-25s", nvl(custLastName)).substring(0, 25));
        sb.append(String.format("%-50s", nvl(custAddrLine1)).substring(0, 50));
        sb.append(String.format("%-50s", nvl(custAddrLine2)).substring(0, 50));
        sb.append(String.format("%-50s", nvl(custAddrLine3)).substring(0, 50));
        sb.append(String.format("%-2s", nvl(custAddrStateCd)).substring(0, 2));
        sb.append(String.format("%-3s", nvl(custAddrCountryCd)).substring(0, 3));
        sb.append(String.format("%-10s", nvl(custAddrZip)).substring(0, 10));
        sb.append(String.format("%-15s", nvl(custPhoneNum1)).substring(0, 15));
        sb.append(String.format("%-15s", nvl(custPhoneNum2)).substring(0, 15));
        sb.append(String.format("%09d", custSsn));
        sb.append(String.format("%-20s", nvl(custGovtIssuedId)).substring(0, 20));
        sb.append(String.format("%-10s", nvl(custDobYyyyMmDd)).substring(0, 10));
        sb.append(String.format("%-10s", nvl(custEftAccountId)).substring(0, 10));
        sb.append(String.format("%-1s", nvl(custPriCardHolderInd)).substring(0, 1));
        sb.append(String.format("%03d", custFicoCreditScore));
        // FILLER: 168 spaces
        sb.append(String.format("%-168s", ""));
        
        String result = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
    }
    
    public String key() {
        return String.valueOf(custId);
    }
    
    @Override
    public String toString() {
        return "CustomerRecord{" +
                "custId=" + custId +
                ", custFirstName='" + nvl(custFirstName).trim() + '\'' +
                ", custMiddleName='" + nvl(custMiddleName).trim() + '\'' +
                ", custLastName='" + nvl(custLastName).trim() + '\'' +
                ", custAddrStateCd='" + nvl(custAddrStateCd).trim() + '\'' +
                ", custAddrCountryCd='" + nvl(custAddrCountryCd).trim() + '\'' +
                ", custAddrZip='" + nvl(custAddrZip).trim() + '\'' +
                ", custSsn=" + custSsn +
                ", custDobYyyyMmDd='" + nvl(custDobYyyyMmDd).trim() + '\'' +
                ", custPriCardHolderInd='" + nvl(custPriCardHolderInd).trim() + '\'' +
                ", custFicoCreditScore=" + custFicoCreditScore +
                '}';
    }
    
    private static String sub(String s, int start, int length) {
        if (s == null) return spaces(length);
        if (start >= s.length()) return spaces(length);
        int end = Math.min(start + length, s.length());
        String result = s.substring(start, end);
        if (result.length() < length) {
            result = result + spaces(length - result.length());
        }
        return result;
    }
    
    private static String spaces(int n) {
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++) sb.append(' ');
        return sb.toString();
    }
    
    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }
    
    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static String nvl(String s) {
        return s == null ? "" : s;
    }
    
    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}