// Generated by CardDemo Agentic Converter on 2026-03-21 16:10:37
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java representation of COBOL copybook: CVTRA06Y.cpy
 * Data-structure for DALYTRANsaction record (RECLN = 350)
 * 
 * Record Layout:
 *   DALYTRAN-ID              PIC X(16)      offset 0
 *   DALYTRAN-TYPE-CD         PIC X(02)      offset 16
 *   DALYTRAN-CAT-CD          PIC 9(04)      offset 18
 *   DALYTRAN-SOURCE          PIC X(10)      offset 22
 *   DALYTRAN-DESC            PIC X(100)     offset 32
 *   DALYTRAN-AMT             PIC S9(09)V99  offset 132 (12 chars)
 *   DALYTRAN-MERCHANT-ID     PIC 9(09)      offset 144
 *   DALYTRAN-MERCHANT-NAME   PIC X(50)      offset 153
 *   DALYTRAN-MERCHANT-CITY   PIC X(50)      offset 203
 *   DALYTRAN-MERCHANT-ZIP    PIC X(10)      offset 253
 *   DALYTRAN-CARD-NUM        PIC X(16)      offset 263
 *   DALYTRAN-ORIG-TS         PIC X(26)      offset 279
 *   DALYTRAN-PROC-TS         PIC X(26)      offset 305
 *   FILLER                   PIC X(20)      offset 331
 *   Total: 351 bytes (but comment says 350)
 */
import java.math.BigDecimal;

public class DailyTranRecord {

    public static final int RECORD_LENGTH = 350;

    public String dalytranId;
    public String dalytranTypeCd;
    public int dalytranCatCd;
    public String dalytranSource;
    public String dalytranDesc;
    public BigDecimal dalytranAmt;
    public long dalytranMerchantId;
    public String dalytranMerchantName;
    public String dalytranMerchantCity;
    public String dalytranMerchantZip;
    public String dalytranCardNum;
    public String dalytranOrigTs;
    public String dalytranProcTs;

    public DailyTranRecord() {
        this.dalytranId = "";
        this.dalytranTypeCd = "";
        this.dalytranCatCd = 0;
        this.dalytranSource = "";
        this.dalytranDesc = "";
        this.dalytranAmt = BigDecimal.ZERO;
        this.dalytranMerchantId = 0L;
        this.dalytranMerchantName = "";
        this.dalytranMerchantCity = "";
        this.dalytranMerchantZip = "";
        this.dalytranCardNum = "";
        this.dalytranOrigTs = "";
        this.dalytranProcTs = "";
    }

    public static DailyTranRecord fromLine(String line) {
        DailyTranRecord rec = new DailyTranRecord();
        if (line == null) line = "";
        rec.dalytranId = sub(line, 0, 16);
        rec.dalytranTypeCd = sub(line, 16, 2);
        rec.dalytranCatCd = parseInt(sub(line, 18, 4));
        rec.dalytranSource = sub(line, 22, 10);
        rec.dalytranDesc = sub(line, 32, 100);
        rec.dalytranAmt = parseScaledDec(sub(line, 132, 12));
        rec.dalytranMerchantId = parseLong(sub(line, 144, 9));
        rec.dalytranMerchantName = sub(line, 153, 50);
        rec.dalytranMerchantCity = sub(line, 203, 50);
        rec.dalytranMerchantZip = sub(line, 253, 10);
        rec.dalytranCardNum = sub(line, 263, 16);
        rec.dalytranOrigTs = sub(line, 279, 26);
        rec.dalytranProcTs = sub(line, 305, 26);
        return rec;
    }

    public String toLine() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("%-16s", nvl(dalytranId)));
        sb.append(String.format("%-2s", nvl(dalytranTypeCd)));
        sb.append(String.format("%04d", dalytranCatCd));
        sb.append(String.format("%-10s", nvl(dalytranSource)));
        sb.append(String.format("%-100s", nvl(dalytranDesc)));
        long amtScaled = nvlDec(dalytranAmt).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+012d", amtScaled));
        sb.append(String.format("%09d", dalytranMerchantId));
        sb.append(String.format("%-50s", nvl(dalytranMerchantName)));
        sb.append(String.format("%-50s", nvl(dalytranMerchantCity)));
        sb.append(String.format("%-10s", nvl(dalytranMerchantZip)));
        sb.append(String.format("%-16s", nvl(dalytranCardNum)));
        sb.append(String.format("%-26s", nvl(dalytranOrigTs)));
        sb.append(String.format("%-26s", nvl(dalytranProcTs)));
        sb.append(String.format("%-19s", ""));
        String rec = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", rec).substring(0, RECORD_LENGTH);
    }

    public String key() {
        return nvl(dalytranId);
    }

    @Override
    public String toString() {
        return "DailyTranRecord{" +
                "dalytranId='" + dalytranId + '\'' +
                ", dalytranTypeCd='" + dalytranTypeCd + '\'' +
                ", dalytranCatCd=" + dalytranCatCd +
                ", dalytranSource='" + dalytranSource + '\'' +
                ", dalytranDesc='" + dalytranDesc + '\'' +
                ", dalytranAmt=" + dalytranAmt +
                ", dalytranMerchantId=" + dalytranMerchantId +
                ", dalytranMerchantName='" + dalytranMerchantName + '\'' +
                ", dalytranMerchantCity='" + dalytranMerchantCity + '\'' +
                ", dalytranMerchantZip='" + dalytranMerchantZip + '\'' +
                ", dalytranCardNum='" + dalytranCardNum + '\'' +
                ", dalytranOrigTs='" + dalytranOrigTs + '\'' +
                ", dalytranProcTs='" + dalytranProcTs + '\'' +
                '}';
    }

    private static String sub(String s, int start, int length) {
        if (s == null) return "";
        if (start >= s.length()) return "";
        int end = Math.min(start + length, s.length());
        return s.substring(start, end);
    }

    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }

    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static String nvl(String s) {
        return s == null ? "" : s;
    }

    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}