// Generated by CardDemo Agentic Converter on 2026-03-21 16:03:31
// Source: AWS CardDemo (Apache 2.0)

/**
 * COBOL Copybook: CODATECN.cpy
 * Date Conversion Record
 * 
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0
 */
import java.math.BigDecimal;

public class DateConversionRecord {
    
    // Record length: 1 + 20 + 1 + 20 + 38 = 80
    public static final int RECORD_LENGTH = 80;
    
    // 88-level constants for input type
    public static final String YYYYMMDD_IN = "1";
    public static final String YYYY_MM_DD_IN = "2";
    
    // 88-level constants for output type
    public static final String YYYY_MM_DD_OP = "1";
    public static final String YYYYMMDD_OP = "2";
    
    // Input Record Fields
    public String codatecnType;           // PIC X
    public String codatecnInpDate;        // PIC X(20)
    
    // CODATECN-1INP redefines (YYYYMMDD format)
    public String codatecn1Yyyy;          // PIC XXXX
    public String codatecn1Mm;            // PIC XX
    public String codatecn1Dd;            // PIC XX
    public String codatecn1Fil;           // PIC X(12)
    
    // CODATECN-2INP redefines (YYYY-MM-DD format)
    public String codatecn1OYyyy;         // PIC XXXX
    public String codatecn1IS1;           // PIC X
    public String codatecn2InpMm;         // PIC XX (reusing name to avoid conflict)
    public String codatecn1IS2;           // PIC X
    public String codatecn2Yy;            // PIC XX
    public String codatecn2Fil;           // PIC X(10)
    
    // Output Record Fields
    public String codatecnOuttype;        // PIC X
    public String codatecn0utDate;        // PIC X(20)
    
    // CODATECN-1OUT redefines (YYYY-MM-DD format)
    public String codatecn1OOutYyyy;      // PIC XXXX
    public String codatecn1OS1;           // PIC X
    public String codatecn1OMm;           // PIC XX
    public String codatecn1OS2;           // PIC X
    public String codatecn1ODd;           // PIC XX
    public String codatecn1OFil;          // PIC X(10)
    
    // CODATECN-2OUT redefines (YYYYMMDD format)
    public String codatecn2OYyyy;         // PIC XXXX
    public String codatecn2OMm;           // PIC XX
    public String codatecn2ODd;           // PIC XX
    public String codatecn2OFil;          // PIC X(12)
    
    // Error message
    public String codatecnErrorMsg;       // PIC X(38)
    
    public static DateConversionRecord fromLine(String line) {
        DateConversionRecord rec = new DateConversionRecord();
        if (line == null) line = "";
        
        int pos = 0;
        
        // Input Record
        rec.codatecnType = sub(line, pos, 1); pos += 1;
        rec.codatecnInpDate = sub(line, pos, 20);
        
        // Parse CODATECN-1INP redefine
        rec.codatecn1Yyyy = sub(line, 1, 4);
        rec.codatecn1Mm = sub(line, 5, 2);
        rec.codatecn1Dd = sub(line, 7, 2);
        rec.codatecn1Fil = sub(line, 9, 12);
        
        // Parse CODATECN-2INP redefine
        rec.codatecn1OYyyy = sub(line, 1, 4);
        rec.codatecn1IS1 = sub(line, 5, 1);
        rec.codatecn2InpMm = sub(line, 6, 2);
        rec.codatecn1IS2 = sub(line, 8, 1);
        rec.codatecn2Yy = sub(line, 9, 2);
        rec.codatecn2Fil = sub(line, 11, 10);
        
        pos += 20;
        
        // Output Record
        rec.codatecnOuttype = sub(line, pos, 1); pos += 1;
        rec.codatecn0utDate = sub(line, pos, 20);
        
        // Parse CODATECN-1OUT redefine
        rec.codatecn1OOutYyyy = sub(line, 22, 4);
        rec.codatecn1OS1 = sub(line, 26, 1);
        rec.codatecn1OMm = sub(line, 27, 2);
        rec.codatecn1OS2 = sub(line, 29, 1);
        rec.codatecn1ODd = sub(line, 30, 2);
        rec.codatecn1OFil = sub(line, 32, 10);
        
        // Parse CODATECN-2OUT redefine
        rec.codatecn2OYyyy = sub(line, 22, 4);
        rec.codatecn2OMm = sub(line, 26, 2);
        rec.codatecn2ODd = sub(line, 28, 2);
        rec.codatecn2OFil = sub(line, 30, 12);
        
        pos += 20;
        
        // Error message
        rec.codatecnErrorMsg = sub(line, pos, 38);
        
        return rec;
    }
    
    public String toLine() {
        StringBuilder sb = new StringBuilder();
        
        // Input Record
        sb.append(String.format("%-1.1s", nvl(codatecnType)));
        sb.append(String.format("%-20.20s", nvl(codatecnInpDate)));
        
        // Output Record
        sb.append(String.format("%-1.1s", nvl(codatecnOuttype)));
        sb.append(String.format("%-20.20s", nvl(codatecn0utDate)));
        
        // Error message
        sb.append(String.format("%-38.38s", nvl(codatecnErrorMsg)));
        
        String result = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
    }
    
    public String key() {
        return nvl(codatecnType) + nvl(codatecnInpDate);
    }
    
    @Override
    public String toString() {
        return "DateConversionRecord{" +
               "type='" + codatecnType + '\'' +
               ", inpDate='" + codatecnInpDate + '\'' +
               ", outType='" + codatecnOuttype + '\'' +
               ", outDate='" + codatecn0utDate + '\'' +
               ", errorMsg='" + codatecnErrorMsg + '\'' +
               '}';
    }
    
    private static String sub(String s, int start, int length) {
        if (s == null) return spaces(length);
        if (start >= s.length()) return spaces(length);
        int end = Math.min(start + length, s.length());
        String result = s.substring(start, end);
        if (result.length() < length) {
            result = result + spaces(length - result.length());
        }
        return result;
    }
    
    private static String spaces(int n) {
        if (n <= 0) return "";
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++) sb.append(' ');
        return sb.toString();
    }
    
    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }
    
    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static String nvl(String s) {
        return s == null ? "" : s;
    }
    
    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}