// Generated by CardDemo Agentic Converter on 2026-03-21 16:11:47
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java class generated from COBOL copybook: CVTRA07Y.cpy
 * Reporting data structure for transaction report
 * 
 * This copybook contains multiple 01-level records for report formatting.
 * All structures are included as nested static classes.
 */
import java.math.BigDecimal;

public class ReportStructures {
    
    // REPORT-NAME-HEADER structure
    public static class ReportNameHeader {
        public static final int RECORD_LENGTH = 115;
        
        public String reptShortName = "DALYREPT";
        public String reptLongName = "Daily Transaction Report";
        public String reptDateHeader = "Date Range: ";
        public String reptStartDate = "";
        public String reptEndDate = "";
        
        public static ReportNameHeader fromLine(String line) {
            ReportNameHeader rec = new ReportNameHeader();
            if (line == null) line = "";
            rec.reptShortName = sub(line, 0, 38);
            rec.reptLongName = sub(line, 38, 41);
            rec.reptDateHeader = sub(line, 79, 12);
            rec.reptStartDate = sub(line, 91, 10);
            // FILLER at 101, length 4
            rec.reptEndDate = sub(line, 105, 10);
            return rec;
        }
        
        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-38s", nvl(reptShortName)));
            sb.append(String.format("%-41s", nvl(reptLongName)));
            sb.append(String.format("%-12s", nvl(reptDateHeader)));
            sb.append(String.format("%-10s", nvl(reptStartDate)));
            sb.append(" to ");
            sb.append(String.format("%-10s", nvl(reptEndDate)));
            String result = sb.toString();
            return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
        }
        
        public String key() {
            return reptShortName.trim();
        }
        
        @Override
        public String toString() {
            return "ReportNameHeader[shortName=" + reptShortName.trim() + 
                   ", longName=" + reptLongName.trim() + 
                   ", startDate=" + reptStartDate.trim() + 
                   ", endDate=" + reptEndDate.trim() + "]";
        }
    }
    
    // TRANSACTION-DETAIL-REPORT structure
    public static class TransactionDetailReport {
        public static final int RECORD_LENGTH = 115;
        
        public String tranReportTransId = "";
        public String tranReportAccountId = "";
        public String tranReportTypeCd = "";
        public String tranReportTypeDesc = "";
        public int tranReportCatCd = 0;
        public String tranReportCatDesc = "";
        public String tranReportSource = "";
        public String tranReportAmt = "";
        
        public static TransactionDetailReport fromLine(String line) {
            TransactionDetailReport rec = new TransactionDetailReport();
            if (line == null) line = "";
            int pos = 0;
            rec.tranReportTransId = sub(line, pos, 16); pos += 16;
            pos += 1; // FILLER
            rec.tranReportAccountId = sub(line, pos, 11); pos += 11;
            pos += 1; // FILLER
            rec.tranReportTypeCd = sub(line, pos, 2); pos += 2;
            pos += 1; // FILLER '-'
            rec.tranReportTypeDesc = sub(line, pos, 15); pos += 15;
            pos += 1; // FILLER
            rec.tranReportCatCd = parseInt(sub(line, pos, 4)); pos += 4;
            pos += 1; // FILLER '-'
            rec.tranReportCatDesc = sub(line, pos, 29); pos += 29;
            pos += 1; // FILLER
            rec.tranReportSource = sub(line, pos, 10); pos += 10;
            pos += 4; // FILLER
            rec.tranReportAmt = sub(line, pos, 15); pos += 15;
            // FILLER 2 at end
            return rec;
        }
        
        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-16s", nvl(tranReportTransId)));
            sb.append(" ");
            sb.append(String.format("%-11s", nvl(tranReportAccountId)));
            sb.append(" ");
            sb.append(String.format("%-2s", nvl(tranReportTypeCd)));
            sb.append("-");
            sb.append(String.format("%-15s", nvl(tranReportTypeDesc)));
            sb.append(" ");
            sb.append(String.format("%04d", tranReportCatCd));
            sb.append("-");
            sb.append(String.format("%-29s", nvl(tranReportCatDesc)));
            sb.append(" ");
            sb.append(String.format("%-10s", nvl(tranReportSource)));
            sb.append("    ");
            sb.append(String.format("%15s", nvl(tranReportAmt)));
            sb.append("  ");
            String result = sb.toString();
            return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
        }
        
        public String key() {
            return tranReportTransId.trim();
        }
        
        @Override
        public String toString() {
            return "TransactionDetailReport[transId=" + tranReportTransId.trim() + 
                   ", accountId=" + tranReportAccountId.trim() + 
                   ", typeCd=" + tranReportTypeCd.trim() + 
                   ", amt=" + tranReportAmt.trim() + "]";
        }
    }
    
    // TRANSACTION-HEADER-1 structure
    public static class TransactionHeader1 {
        public static final int RECORD_LENGTH = 114;
        
        public static TransactionHeader1 fromLine(String line) {
            return new TransactionHeader1();
        }
        
        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-17s", "Transaction ID"));
            sb.append(String.format("%-12s", "Account ID"));
            sb.append(String.format("%-19s", "Transaction Type"));
            sb.append(String.format("%-35s", "Tran Category"));
            sb.append(String.format("%-14s", "Tran Source"));
            sb.append(" ");
            sb.append(String.format("%-16s", "        Amount"));
            String result = sb.toString();
            return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
        }
        
        public String key() {
            return "HEADER1";
        }
        
        @Override
        public String toString() {
            return "TransactionHeader1[]";
        }
    }
    
    // TRANSACTION-HEADER-2 structure (all dashes)
    public static class TransactionHeader2 {
        public static final int RECORD_LENGTH = 133;
        
        public static TransactionHeader2 fromLine(String line) {
            return new TransactionHeader2();
        }
        
        public String toLine() {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < RECORD_LENGTH; i++) {
                sb.append('-');
            }
            return sb.toString();
        }
        
        public String key() {
            return "HEADER2";
        }
        
        @Override
        public String toString() {
            return "TransactionHeader2[dashes]";
        }
    }
    
    // REPORT-PAGE-TOTALS structure
    public static class ReportPageTotals {
        public static final int RECORD_LENGTH = 112;
        
        public String reptPageTotal = "";
        
        public static ReportPageTotals fromLine(String line) {
            ReportPageTotals rec = new ReportPageTotals();
            if (line == null) line = "";
            rec.reptPageTotal = sub(line, 97, 15);
            return rec;
        }
        
        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-11s", "Page Total"));
            for (int i = 0; i < 86; i++) sb.append('.');
            sb.append(String.format("%15s", nvl(reptPageTotal)));
            String result = sb.toString();
            return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
        }
        
        public String key() {
            return "PAGE_TOTAL";
        }
        
        @Override
        public String toString() {
            return "ReportPageTotals[total=" + reptPageTotal.trim() + "]";
        }
    }
    
    // REPORT-ACCOUNT-TOTALS structure
    public static class ReportAccountTotals {
        public static final int RECORD_LENGTH = 112;
        
        public String reptAccountTotal = "";
        
        public static ReportAccountTotals fromLine(String line) {
            ReportAccountTotals rec = new ReportAccountTotals();
            if (line == null) line = "";
            rec.reptAccountTotal = sub(line, 97, 15);
            return rec;
        }
        
        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-13s", "Account Total"));
            for (int i = 0; i < 84; i++) sb.append('.');
            sb.append(String.format("%15s", nvl(reptAccountTotal)));
            String result = sb.toString();
            return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
        }
        
        public String key() {
            return "ACCOUNT_TOTAL";
        }
        
        @Override
        public String toString() {
            return "ReportAccountTotals[total=" + reptAccountTotal.trim() + "]";
        }
    }
    
    // REPORT-GRAND-TOTALS structure
    public static class ReportGrandTotals {
        public static final int RECORD_LENGTH = 112;
        
        public String reptGrandTotal = "";
        
        public static ReportGrandTotals fromLine(String line) {
            ReportGrandTotals rec = new ReportGrandTotals();
            if (line == null) line = "";
            rec.reptGrandTotal = sub(line, 97, 15);
            return rec;
        }
        
        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-11s", "Grand Total"));
            for (int i = 0; i < 86; i++) sb.append('.');
            sb.append(String.format("%15s", nvl(reptGrandTotal)));
            String result = sb.toString();
            return String.format("%-" + RECORD_LENGTH + "s", result).substring(0, RECORD_LENGTH);
        }
        
        public String key() {
            return "GRAND_TOTAL";
        }
        
        @Override
        public String toString() {
            return "ReportGrandTotals[total=" + reptGrandTotal.trim() + "]";
        }
    }
    
    // Utility methods
    private static String sub(String s, int start, int length) {
        if (s == null) return spaces(length);
        if (start >= s.length()) return spaces(length);
        int end = Math.min(start + length, s.length());
        String result = s.substring(start, end);
        if (result.length() < length) {
            result = result + spaces(length - result.length());
        }
        return result;
    }
    
    private static String spaces(int n) {
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++) sb.append(' ');
        return sb.toString();
    }
    
    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }
    
    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static String nvl(String s) {
        return s == null ? "" : s;
    }
    
    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}