// Generated by CardDemo Agentic Converter on 2026-03-21 16:08:57
// Source: AWS CardDemo (Apache 2.0)

/**
 * Data-structure for transaction category type (RECLN = 60)
 * 
 * Generated from COBOL copybook: CVTRA04Y.cpy
 * Record length: 60 bytes
 * 
 * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:16:01 CDT
 */
import java.math.BigDecimal;

public class TranCatRecord {
    
    public static final int RECORD_LENGTH = 60;
    
    // Key fields
    public String tranTypeCd;      // PIC X(02) - offset 0, length 2
    public int tranCatCd;          // PIC 9(04) - offset 2, length 4
    
    // Data fields
    public String tranCatTypeDesc; // PIC X(50) - offset 6, length 50
    // FILLER PIC X(04) - offset 56, length 4 (skipped)
    
    public TranCatRecord() {
        this.tranTypeCd = "";
        this.tranCatCd = 0;
        this.tranCatTypeDesc = "";
    }
    
    public static TranCatRecord fromLine(String line) {
        TranCatRecord rec = new TranCatRecord();
        if (line == null) line = "";
        rec.tranTypeCd = sub(line, 0, 2);
        rec.tranCatCd = parseInt(sub(line, 2, 4));
        rec.tranCatTypeDesc = sub(line, 6, 50);
        return rec;
    }
    
    public String toLine() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("%-2s", nvl(tranTypeCd)).substring(0, 2));
        sb.append(String.format("%04d", tranCatCd));
        sb.append(String.format("%-50s", nvl(tranCatTypeDesc)).substring(0, 50));
        sb.append(String.format("%-4s", "").substring(0, 4)); // FILLER
        String rec = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", rec).substring(0, RECORD_LENGTH);
    }
    
    public String key() {
        return String.format("%-2s", nvl(tranTypeCd)).substring(0, 2) +
               String.format("%04d", tranCatCd);
    }
    
    @Override
    public String toString() {
        return "TranCatRecord{" +
               "tranTypeCd='" + tranTypeCd + '\'' +
               ", tranCatCd=" + tranCatCd +
               ", tranCatTypeDesc='" + tranCatTypeDesc + '\'' +
               '}';
    }
    
    private static String sub(String s, int start, int length) {
        if (s == null) return "";
        if (start >= s.length()) return "";
        int end = Math.min(start + length, s.length());
        return s.substring(start, end);
    }
    
    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }
    
    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static String nvl(String s) {
        return s == null ? "" : s;
    }
    
    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}