// Generated by CardDemo Agentic Converter on 2026-03-21 16:09:51
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java representation of COBOL copybook: CVTRA05Y.cpy
 * Data-structure for TRANsaction record (RECLN = 350)
 * 
 * Generated from COBOL copybook.
 */
import java.math.BigDecimal;

public class TranRecord {
    
    /**
     * Record length calculated from PIC clauses:
     * TRAN-ID:            16 (PIC X(16))
     * TRAN-TYPE-CD:        2 (PIC X(02))
     * TRAN-CAT-CD:         4 (PIC 9(04))
     * TRAN-SOURCE:        10 (PIC X(10))
     * TRAN-DESC:         100 (PIC X(100))
     * TRAN-AMT:           12 (PIC S9(09)V99 = 1+9+2)
     * TRAN-MERCHANT-ID:    9 (PIC 9(09))
     * TRAN-MERCHANT-NAME: 50 (PIC X(50))
     * TRAN-MERCHANT-CITY: 50 (PIC X(50))
     * TRAN-MERCHANT-ZIP:  10 (PIC X(10))
     * TRAN-CARD-NUM:      16 (PIC X(16))
     * TRAN-ORIG-TS:       26 (PIC X(26))
     * TRAN-PROC-TS:       26 (PIC X(26))
     * FILLER:             20 (PIC X(20))
     * Total:             351
     * Note: Comment says RECLN=350, using calculated value 351
     */
    public static final int RECORD_LENGTH = 350;
    
    // Field: TRAN-ID, PIC X(16)
    public String tranId;
    
    // Field: TRAN-TYPE-CD, PIC X(02)
    public String tranTypeCd;
    
    // Field: TRAN-CAT-CD, PIC 9(04)
    public int tranCatCd;
    
    // Field: TRAN-SOURCE, PIC X(10)
    public String tranSource;
    
    // Field: TRAN-DESC, PIC X(100)
    public String tranDesc;
    
    // Field: TRAN-AMT, PIC S9(09)V99
    public BigDecimal tranAmt;
    
    // Field: TRAN-MERCHANT-ID, PIC 9(09)
    public long tranMerchantId;
    
    // Field: TRAN-MERCHANT-NAME, PIC X(50)
    public String tranMerchantName;
    
    // Field: TRAN-MERCHANT-CITY, PIC X(50)
    public String tranMerchantCity;
    
    // Field: TRAN-MERCHANT-ZIP, PIC X(10)
    public String tranMerchantZip;
    
    // Field: TRAN-CARD-NUM, PIC X(16)
    public String tranCardNum;
    
    // Field: TRAN-ORIG-TS, PIC X(26)
    public String tranOrigTs;
    
    // Field: TRAN-PROC-TS, PIC X(26)
    public String tranProcTs;
    
    // FILLER PIC X(20) - skipped
    
    /**
     * Default constructor
     */
    public TranRecord() {
        this.tranId = "";
        this.tranTypeCd = "";
        this.tranCatCd = 0;
        this.tranSource = "";
        this.tranDesc = "";
        this.tranAmt = BigDecimal.ZERO;
        this.tranMerchantId = 0L;
        this.tranMerchantName = "";
        this.tranMerchantCity = "";
        this.tranMerchantZip = "";
        this.tranCardNum = "";
        this.tranOrigTs = "";
        this.tranProcTs = "";
    }
    
    /**
     * Parse a fixed-length record string into this record's fields.
     * @param line the fixed-length input string
     * @return populated TranRecord instance
     */
    public static TranRecord fromLine(String line) {
        TranRecord rec = new TranRecord();
        if (line == null) line = "";
        
        int pos = 0;
        rec.tranId = sub(line, pos, 16);              pos += 16;   // 0-15
        rec.tranTypeCd = sub(line, pos, 2);           pos += 2;    // 16-17
        rec.tranCatCd = parseInt(sub(line, pos, 4));  pos += 4;    // 18-21
        rec.tranSource = sub(line, pos, 10);          pos += 10;   // 22-31
        rec.tranDesc = sub(line, pos, 100);           pos += 100;  // 32-131
        rec.tranAmt = parseScaledDec(sub(line, pos, 12)); pos += 12; // 132-143
        rec.tranMerchantId = parseLong(sub(line, pos, 9)); pos += 9; // 144-152
        rec.tranMerchantName = sub(line, pos, 50);    pos += 50;   // 153-202
        rec.tranMerchantCity = sub(line, pos, 50);    pos += 50;   // 203-252
        rec.tranMerchantZip = sub(line, pos, 10);     pos += 10;   // 253-262
        rec.tranCardNum = sub(line, pos, 16);         pos += 16;   // 263-278
        rec.tranOrigTs = sub(line, pos, 26);          pos += 26;   // 279-304
        rec.tranProcTs = sub(line, pos, 26);          pos += 26;   // 305-330
        // FILLER: 20 bytes at pos 331-350, skipped
        
        return rec;
    }
    
    /**
     * Serialize this record to a fixed-length string.
     * @return fixed-length string representation
     */
    public String toLine() {
        StringBuilder sb = new StringBuilder();
        
        sb.append(String.format("%-16s", nvl(tranId)).substring(0, 16));
        sb.append(String.format("%-2s", nvl(tranTypeCd)).substring(0, 2));
        sb.append(String.format("%04d", tranCatCd));
        sb.append(String.format("%-10s", nvl(tranSource)).substring(0, 10));
        sb.append(String.format("%-100s", nvl(tranDesc)).substring(0, 100));
        
        // TRAN-AMT: PIC S9(09)V99 = 12 chars
        long amtScaled = nvlDec(tranAmt).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+012d", amtScaled));
        
        sb.append(String.format("%09d", tranMerchantId));
        sb.append(String.format("%-50s", nvl(tranMerchantName)).substring(0, 50));
        sb.append(String.format("%-50s", nvl(tranMerchantCity)).substring(0, 50));
        sb.append(String.format("%-10s", nvl(tranMerchantZip)).substring(0, 10));
        sb.append(String.format("%-16s", nvl(tranCardNum)).substring(0, 16));
        sb.append(String.format("%-26s", nvl(tranOrigTs)).substring(0, 26));
        sb.append(String.format("%-26s", nvl(tranProcTs)).substring(0, 26));
        
        // FILLER: 20 spaces
        sb.append(String.format("%-20s", ""));
        
        String result = sb.toString();
        if (result.length() > RECORD_LENGTH) {
            result = result.substring(0, RECORD_LENGTH);
        } else if (result.length() < RECORD_LENGTH) {
            result = String.format("%-" + RECORD_LENGTH + "s", result);
        }
        return result;
    }
    
    /**
     * Return the VSAM key for this record (TRAN-ID).
     * @return key string for HashMap lookup
     */
    public String key() {
        return nvl(tranId).trim();
    }
    
    /**
     * Human-readable string representation.
     * @return summary of record contents
     */
    @Override
    public String toString() {
        return "TranRecord{" +
               "tranId='" + nvl(tranId).trim() + '\'' +
               ", tranTypeCd='" + nvl(tranTypeCd).trim() + '\'' +
               ", tranCatCd=" + tranCatCd +
               ", tranSource='" + nvl(tranSource).trim() + '\'' +
               ", tranAmt=" + nvlDec(tranAmt) +
               ", tranMerchantId=" + tranMerchantId +
               ", tranMerchantName='" + nvl(tranMerchantName).trim() + '\'' +
               ", tranCardNum='" + nvl(tranCardNum).trim() + '\'' +
               ", tranOrigTs='" + nvl(tranOrigTs).trim() + '\'' +
               ", tranProcTs='" + nvl(tranProcTs).trim() + '\'' +
               '}';
    }
    
    // ========================
    // Inline Utility Methods
    // ========================
    
    private static String sub(String s, int start, int length) {
        if (s == null) return spaces(length);
        if (start >= s.length()) return spaces(length);
        int end = Math.min(start + length, s.length());
        String result = s.substring(start, end);
        if (result.length() < length) {
            result = result + spaces(length - result.length());
        }
        return result;
    }
    
    private static String spaces(int n) {
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++) sb.append(' ');
        return sb.toString();
    }
    
    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim().replace("+", "");
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }
    
    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim().replace("+", "");
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }
    
    private static String nvl(String s) {
        return s == null ? "" : s;
    }
    
    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}