// Generated by CardDemo Agentic Converter on 2026-03-21 16:07:41
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java representation of COBOL copybook: CVTRA01Y.cpy
 * Data-structure for transaction category balance (RECLN = 50)
 * 
 * Record Layout:
 *   TRANCAT-ACCT-ID    PIC 9(11)       positions 1-11   (11 chars)
 *   TRANCAT-TYPE-CD    PIC X(02)       positions 12-13  (2 chars)
 *   TRANCAT-CD         PIC 9(04)       positions 14-17  (4 chars)
 *   TRAN-CAT-BAL       PIC S9(09)V99   positions 18-29  (12 chars)
 *   FILLER             PIC X(22)       positions 30-51  (22 chars - skipped)
 * 
 * Total Record Length: 50
 */
import java.math.BigDecimal;

public class TranCatBalRecord {

    public static final int RECORD_LENGTH = 50;

    // Key fields (TRAN-CAT-KEY)
    public long trancatAcctId;      // PIC 9(11)
    public String trancatTypeCd;    // PIC X(02)
    public int trancatCd;           // PIC 9(04)

    // Data fields
    public BigDecimal tranCatBal;   // PIC S9(09)V99

    // FILLER PIC X(22) - skipped

    public TranCatBalRecord() {
        this.trancatAcctId = 0L;
        this.trancatTypeCd = "";
        this.trancatCd = 0;
        this.tranCatBal = BigDecimal.ZERO;
    }

    public static TranCatBalRecord fromLine(String line) {
        TranCatBalRecord rec = new TranCatBalRecord();
        if (line == null) line = "";
        if (line.length() < RECORD_LENGTH) {
            line = String.format("%-" + RECORD_LENGTH + "s", line);
        }

        int pos = 0;
        rec.trancatAcctId = parseLong(sub(line, pos, 11));   pos += 11;  // 0-10
        rec.trancatTypeCd = sub(line, pos, 2);                pos += 2;   // 11-12
        rec.trancatCd = parseInt(sub(line, pos, 4));          pos += 4;   // 13-16
        rec.tranCatBal = parseScaledDec(sub(line, pos, 12));  pos += 12;  // 17-28
        // FILLER X(22) skipped                                           // 29-50

        return rec;
    }

    public String toLine() {
        StringBuilder sb = new StringBuilder();

        sb.append(String.format("%011d", trancatAcctId));                           // 11 chars
        sb.append(String.format("%-2s", nvl(trancatTypeCd)).substring(0, 2));       // 2 chars
        sb.append(String.format("%04d", trancatCd));                                // 4 chars

        long balScaled = nvlDec(tranCatBal).multiply(new BigDecimal("100")).longValue();
        sb.append(String.format("%+012d", balScaled));                              // 12 chars

        sb.append(String.format("%-22s", ""));                                      // 22 chars FILLER

        String result = sb.toString();
        if (result.length() < RECORD_LENGTH) {
            result = String.format("%-" + RECORD_LENGTH + "s", result);
        }
        return result.substring(0, RECORD_LENGTH);
    }

    public String key() {
        return String.format("%011d", trancatAcctId) +
               String.format("%-2s", nvl(trancatTypeCd)).substring(0, 2) +
               String.format("%04d", trancatCd);
    }

    @Override
    public String toString() {
        return "TranCatBalRecord{" +
               "trancatAcctId=" + trancatAcctId +
               ", trancatTypeCd='" + trancatTypeCd + '\'' +
               ", trancatCd=" + trancatCd +
               ", tranCatBal=" + tranCatBal +
               '}';
    }

    private static String sub(String s, int start, int length) {
        if (s == null) return "";
        int end = start + length;
        if (start >= s.length()) return "";
        if (end > s.length()) end = s.length();
        return s.substring(start, end);
    }

    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try { return Long.parseLong(s); } catch (NumberFormatException e) { return 0L; }
    }

    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try { return Integer.parseInt(s); } catch (NumberFormatException e) { return 0; }
    }

    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try { return new BigDecimal(s); } catch (NumberFormatException e) { return BigDecimal.ZERO; }
    }

    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try { return new BigDecimal(s); } catch (NumberFormatException e) { return BigDecimal.ZERO; }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new BigDecimal("100"));
        } catch (NumberFormatException e) { return BigDecimal.ZERO; }
    }

    private static String nvl(String s) {
        return s == null ? "" : s;
    }

    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}