// Generated by CardDemo Agentic Converter on 2026-03-21 16:08:22
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java class generated from COBOL copybook: CVTRA03Y.cpy
 * Data-structure for transaction type (RECLN = 60)
 * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:16:00 CDT
 */
import java.math.BigDecimal;

public class TranTypeRecord {

    public static final int RECORD_LENGTH = 60;

    // PIC X(02)
    public String tranType;
    // PIC X(50)
    public String tranTypeDesc;
    // FILLER PIC X(08) - skipped

    public static TranTypeRecord fromLine(String line) {
        TranTypeRecord rec = new TranTypeRecord();
        if (line == null) line = "";
        rec.tranType = sub(line, 0, 2);
        rec.tranTypeDesc = sub(line, 2, 50);
        return rec;
    }

    public String toLine() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("%-2s", nvl(tranType)).substring(0, 2));
        sb.append(String.format("%-50s", nvl(tranTypeDesc)).substring(0, 50));
        sb.append(String.format("%-8s", "").substring(0, 8)); // FILLER
        String rec = sb.toString();
        return String.format("%-" + RECORD_LENGTH + "s", rec).substring(0, RECORD_LENGTH);
    }

    public String key() {
        return nvl(tranType);
    }

    @Override
    public String toString() {
        return "TranTypeRecord{" +
                "tranType='" + tranType + '\'' +
                ", tranTypeDesc='" + tranTypeDesc + '\'' +
                '}';
    }

    private static String sub(String s, int start, int length) {
        if (s == null) return "";
        int end = start + length;
        if (start >= s.length()) return "";
        if (end > s.length()) end = s.length();
        return s.substring(start, end);
    }

    private static long parseLong(String s) {
        if (s == null) return 0L;
        s = s.trim();
        if (s.isEmpty()) return 0L;
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0L;
        }
    }

    private static int parseInt(String s) {
        if (s == null) return 0;
        s = s.trim();
        if (s.isEmpty()) return 0;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private static BigDecimal parseDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        try {
            return new BigDecimal(s);
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static BigDecimal parseScaledDec(String s) {
        if (s == null) return BigDecimal.ZERO;
        s = s.trim();
        if (s.isEmpty()) return BigDecimal.ZERO;
        if (s.contains(".")) {
            try {
                return new BigDecimal(s);
            } catch (NumberFormatException e) {
                return BigDecimal.ZERO;
            }
        }
        try {
            return new BigDecimal(Long.parseLong(s)).divide(new java.math.BigDecimal("100"));
        } catch (NumberFormatException e) {
            return BigDecimal.ZERO;
        }
    }

    private static String nvl(String s) {
        return s == null ? "" : s;
    }

    private static BigDecimal nvlDec(BigDecimal d) {
        return d == null ? BigDecimal.ZERO : d;
    }
}