# Generated by CardDemo Agentic Converter on 2026-03-21 18:10:42
# Source: AWS CardDemo (Apache 2.0)

"""
ACCTFILE.py - Converted from ACCTFILE.jcl

JCL Job: ACCTFILE - Delete define Account Data
This script manages VSAM Account data file:
- STEP05: Delete existing VSAM cluster if exists
- STEP10: Define new VSAM KSDS cluster
- STEP15: Copy data from flat file to VSAM file

Copyright Amazon.com, Inc. or its affiliates.
All Rights Reserved.
Licensed under the Apache License, Version 2.0
"""

import os
import sys
import json
import shutil
import logging
from datetime import datetime

# Configure logging (replaces SYSPRINT DD SYSOUT=*)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def step05_delete_vsam():
    """
    STEP05 - EXEC PGM=IDCAMS
    DELETE ACCOUNT VSAM FILE IF ONE ALREADY EXISTS
    
    IDCAMS Commands:
        DELETE AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS CLUSTER
        IF MAXCC LE 08 THEN SET MAXCC = 0
    """
    logger.info("=" * 60)
    logger.info("STEP05 - DELETE EXISTING VSAM CLUSTER")
    logger.info("=" * 60)
    
    # DD allocations for this step
    vsam_cluster = os.getenv("DD_ACCTVSAM_KSDS", "data/ACCTDATA.VSAM.KSDS.dat")
    vsam_metadata = vsam_cluster + ".meta.json"
    vsam_data = os.getenv("DD_ACCTVSAM_DATA", "data/ACCTDATA.VSAM.KSDS.DATA.dat")
    vsam_index = os.getenv("DD_ACCTVSAM_INDEX", "data/ACCTDATA.VSAM.KSDS.INDEX.dat")
    
    logger.info(f"VSAM Cluster file: {vsam_cluster}")
    logger.info(f"VSAM Metadata file: {vsam_metadata}")
    logger.info(f"VSAM Data file: {vsam_data}")
    logger.info(f"VSAM Index file: {vsam_index}")
    
    # DELETE AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS CLUSTER
    files_to_delete = [vsam_cluster, vsam_metadata, vsam_data, vsam_index]
    
    for file_path in files_to_delete:
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                logger.info(f"DELETED: {file_path}")
            except Exception as e:
                logger.warning(f"Error deleting {file_path}: {e}")
        else:
            logger.info(f"FILE NOT FOUND (OK): {file_path}")
    
    # IF MAXCC LE 08 THEN SET MAXCC = 0
    # File not found is acceptable, always return success
    logger.info("STEP05 completed - MAXCC set to 0")
    return 0


def step10_define_vsam():
    """
    STEP10 - EXEC PGM=IDCAMS
    DEFINE ACCOUNT VSAM FILE
    
    IDCAMS Commands:
        DEFINE CLUSTER (NAME(AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS)
               CYLINDERS(1 5)
               VOLUMES(AWSHJ1)
               KEYS(11 0)
               RECORDSIZE(300 300)
               SHAREOPTIONS(2 3)
               ERASE
               INDEXED)
               DATA (NAME(AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS.DATA))
               INDEX (NAME(AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS.INDEX))
    """
    logger.info("=" * 60)
    logger.info("STEP10 - DEFINE VSAM KSDS CLUSTER")
    logger.info("=" * 60)
    
    # DD allocations for this step
    vsam_cluster = os.getenv("DD_ACCTVSAM_KSDS", "data/ACCTDATA.VSAM.KSDS.dat")
    vsam_metadata = vsam_cluster + ".meta.json"
    vsam_data = os.getenv("DD_ACCTVSAM_DATA", "data/ACCTDATA.VSAM.KSDS.DATA.dat")
    vsam_index = os.getenv("DD_ACCTVSAM_INDEX", "data/ACCTDATA.VSAM.KSDS.INDEX.dat")
    
    logger.info(f"Defining VSAM Cluster: {vsam_cluster}")
    logger.info(f"  DATA component: {vsam_data}")
    logger.info(f"  INDEX component: {vsam_index}")
    
    # Ensure data directory exists
    data_dir = os.path.dirname(vsam_cluster)
    if data_dir and not os.path.exists(data_dir):
        os.makedirs(data_dir)
        logger.info(f"Created directory: {data_dir}")
    
    # Create empty VSAM cluster file
    try:
        with open(vsam_cluster, 'wb') as f:
            pass  # Create empty file
        logger.info(f"Created empty cluster file: {vsam_cluster}")
    except Exception as e:
        logger.error(f"Error creating cluster file: {e}")
        return 8
    
    # Create empty DATA component
    try:
        with open(vsam_data, 'wb') as f:
            pass
        logger.info(f"Created DATA component: {vsam_data}")
    except Exception as e:
        logger.error(f"Error creating DATA component: {e}")
        return 8
    
    # Create empty INDEX component
    try:
        with open(vsam_index, 'wb') as f:
            pass
        logger.info(f"Created INDEX component: {vsam_index}")
    except Exception as e:
        logger.error(f"Error creating INDEX component: {e}")
        return 8
    
    # Write VSAM metadata sidecar file
    vsam_metadata_content = {
        "name": "AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS",
        "type": "KSDS",
        "key_length": 11,
        "key_offset": 0,
        "record_size": 300,
        "record_size_max": 300,
        "cylinders_primary": 1,
        "cylinders_secondary": 5,
        "volumes": ["AWSHJ1"],
        "shareoptions": [2, 3],
        "erase": True,
        "indexed": True,
        "data_component": "AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS.DATA",
        "index_component": "AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS.INDEX",
        "created_at": datetime.now().isoformat()
    }
    
    try:
        with open(vsam_metadata, 'w') as f:
            json.dump(vsam_metadata_content, f, indent=2)
        logger.info(f"Created metadata sidecar: {vsam_metadata}")
        logger.info(f"  Key Length: {vsam_metadata_content['key_length']}")
        logger.info(f"  Key Offset: {vsam_metadata_content['key_offset']}")
        logger.info(f"  Record Size: {vsam_metadata_content['record_size']}")
    except Exception as e:
        logger.error(f"Error creating metadata file: {e}")
        return 8
    
    logger.info("STEP10 completed successfully - VSAM cluster defined")
    return 0


def step15_repro_data():
    """
    STEP15 - EXEC PGM=IDCAMS
    COPY DATA FROM FLAT FILE TO VSAM FILE
    
    DD Statements:
        ACCTDATA DD DSN=AWS.M2.CARDDEMO.ACCTDATA.PS (input flat file)
        ACCTVSAM DD DSN=AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS (output VSAM)
    
    IDCAMS Commands:
        REPRO INFILE(ACCTDATA) OUTFILE(ACCTVSAM)
    """
    logger.info("=" * 60)
    logger.info("STEP15 - REPRO DATA FROM FLAT FILE TO VSAM")
    logger.info("=" * 60)
    
    # DD allocations for this step
    acctdata_input = os.getenv("DD_ACCTDATA", "data/ACCTDATA.PS.dat")
    acctvsam_output = os.getenv("DD_ACCTVSAM", "data/ACCTDATA.VSAM.KSDS.dat")
    
    logger.info(f"DD ACCTDATA (input): {acctdata_input}")
    logger.info(f"DD ACCTVSAM (output): {acctvsam_output}")
    
    # REPRO INFILE(ACCTDATA) OUTFILE(ACCTVSAM)
    if not os.path.exists(acctdata_input):
        logger.error(f"Input file not found: {acctdata_input}")
        return 8
    
    try:
        shutil.copyfile(acctdata_input, acctvsam_output)
        
        # Get file statistics
        input_size = os.path.getsize(acctdata_input)
        output_size = os.path.getsize(acctvsam_output)
        
        logger.info(f"REPRO completed successfully")
        logger.info(f"  Input file size: {input_size} bytes")
        logger.info(f"  Output file size: {output_size} bytes")
        
        # Estimate record count based on record size (300 bytes)
        record_size = 300
        estimated_records = input_size // record_size if input_size > 0 else 0
        logger.info(f"  Estimated records copied: {estimated_records}")
        
    except Exception as e:
        logger.error(f"Error during REPRO operation: {e}")
        return 8
    
    logger.info("STEP15 completed successfully")
    return 0


def main():
    """
    Main function - ACCTFILE JOB
    Delete define Account Data
    
    Job Flow:
        STEP05: Delete existing VSAM cluster (if exists)
        STEP10: Define new VSAM KSDS cluster
        STEP15: Copy data from flat file to VSAM
    """
    logger.info("=" * 60)
    logger.info("JOB ACCTFILE - Delete define Account Data")
    logger.info("=" * 60)
    logger.info(f"Job started at: {datetime.now().isoformat()}")
    logger.info("")
    
    max_rc = 0
    
    # STEP05 - Delete existing VSAM cluster
    rc = step05_delete_vsam()
    logger.info(f"STEP05 Return Code: {rc}")
    if rc > max_rc:
        max_rc = rc
    if rc > 8:
        logger.error("STEP05 failed with RC > 8, terminating job")
        sys.exit(rc)
    logger.info("")
    
    # STEP10 - Define VSAM cluster
    rc = step10_define_vsam()
    logger.info(f"STEP10 Return Code: {rc}")
    if rc > max_rc:
        max_rc = rc
    if rc > 0:
        logger.error("STEP10 failed, terminating job")
        sys.exit(rc)
    logger.info("")
    
    # STEP15 - Copy data from flat file to VSAM
    rc = step15_repro_data()
    logger.info(f"STEP15 Return Code: {rc}")
    if rc > max_rc:
        max_rc = rc
    if rc > 0:
        logger.error("STEP15 failed")
    logger.info("")
    
    # Job completion summary
    logger.info("=" * 60)
    logger.info("JOB ACCTFILE COMPLETED")
    logger.info(f"Job ended at: {datetime.now().isoformat()}")
    logger.info(f"Maximum Return Code: {max_rc}")
    logger.info("=" * 60)
    
    sys.exit(max_rc)


if __name__ == "__main__":
    main()