# Generated by CardDemo Agentic Converter on 2026-03-21 18:12:02
# Source: AWS CardDemo (Apache 2.0)

"""
INTCALC.jcl - Interest Calculator Batch Job

Converted from JCL to Python.
Processes transaction balance file and computes interest and fees.

Original JCL: INTCALC.jcl
Job: INTCALC - INTEREST CALCULATOR
"""

import os
import sys
import logging
import subprocess
from datetime import datetime

# Configure logging (replaces SYSPRINT/SYSOUT=*)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)


def run_step15():
    """
    STEP15 - Execute CBACT04C program
    
    Original JCL:
    //STEP15 EXEC PGM=CBACT04C,PARM='2022071800'
    
    Process transaction balance file and compute interest and fees.
    """
    logger.info("=" * 60)
    logger.info("STEP15 - Executing CBACT04C (Interest and Fees Calculation)")
    logger.info("=" * 60)
    
    # DD Name allocations - map to environment variables
    # STEPLIB DD - Program library (not needed in Python conversion)
    
    # TCATBALF DD - Transaction Category Balance File (VSAM KSDS)
    tcatbalf_file = os.getenv("TCATBALF", "data/tcatbalf.dat")
    logger.info(f"DD TCATBALF allocated: {tcatbalf_file}")
    
    # XREFFILE DD - Card Cross Reference File (VSAM KSDS)
    xreffile = os.getenv("XREFFILE", "data/cardxref.dat")
    logger.info(f"DD XREFFILE allocated: {xreffile}")
    
    # XREFFIL1 DD - Card Cross Reference Alternate Index Path
    xreffil1 = os.getenv("XREFFIL1", "data/cardxref_aix.dat")
    logger.info(f"DD XREFFIL1 allocated: {xreffil1}")
    
    # ACCTFILE DD - Account Data File (VSAM KSDS)
    acctfile = os.getenv("ACCTFILE", "data/acctdata.dat")
    logger.info(f"DD ACCTFILE allocated: {acctfile}")
    
    # DISCGRP DD - Disclosure Group File (VSAM KSDS)
    discgrp_file = os.getenv("DISCGRP", "data/discgrp.dat")
    logger.info(f"DD DISCGRP allocated: {discgrp_file}")
    
    # TRANSACT DD - Transaction Output File (GDG +1)
    # DSN=AWS.M2.CARDDEMO.SYSTRAN(+1) - New generation
    # DISP=(NEW,CATLG,DELETE), DCB=(RECFM=F,LRECL=350,BLKSIZE=0)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    transact_file = os.getenv("TRANSACT", f"data/SYSTRAN_{timestamp}.dat")
    logger.info(f"DD TRANSACT allocated (GDG +1): {transact_file}")
    
    # PARM value - default to original value or current date
    parm_value = os.getenv("PARM", "2022071800")
    logger.info(f"PARM value: {parm_value}")
    
    # Ensure data directory exists
    os.makedirs("data", exist_ok=True)
    
    # Build environment for subprocess
    env = os.environ.copy()
    env["TCATBALF"] = tcatbalf_file
    env["XREFFILE"] = xreffile
    env["XREFFIL1"] = xreffil1
    env["ACCTFILE"] = acctfile
    env["DISCGRP"] = discgrp_file
    env["TRANSACT"] = transact_file
    env["PARM"] = parm_value
    
    # Execute CBACT04C program
    program_name = "CBACT04C"
    program_file = f"{program_name.lower()}.py"
    
    logger.info(f"Executing program: {program_name}")
    
    # CRITICAL: Check if program file exists BEFORE subprocess.run()
    if not os.path.exists(program_file):
        logger.warning(f"Program {program_file} not found. Skipping.")
        return 0
    
    try:
        result = subprocess.run(
            [sys.executable, program_file, parm_value],
            env=env,
            capture_output=False
        )
        rc = result.returncode
        logger.info(f"Program {program_name} completed with return code: {rc}")
        return rc
    except Exception as e:
        logger.error(f"Error running {program_file}: {e}")
        return 8


def main():
    """
    Main function - INTCALC Job
    
    Process transaction balance file and compute interest and fees.
    """
    logger.info("*" * 60)
    logger.info("* JOB: INTCALC - INTEREST CALCULATOR")
    logger.info("* Converted from JCL to Python")
    logger.info("*" * 60)
    
    job_start_time = datetime.now()
    logger.info(f"Job started at: {job_start_time.isoformat()}")
    
    max_rc = 0
    
    # Execute STEP15 - CBACT04C (Interest and Fees Calculation)
    logger.info("")
    logger.info("Starting STEP15...")
    step_rc = run_step15()
    logger.info(f"STEP15 completed with RC={step_rc}")
    max_rc = max(max_rc, step_rc)
    
    # Check if step failed
    if step_rc > 4:
        logger.error(f"STEP15 failed with RC={step_rc}")
    
    # Job completion
    job_end_time = datetime.now()
    job_duration = job_end_time - job_start_time
    
    logger.info("")
    logger.info("*" * 60)
    logger.info(f"* JOB INTCALC COMPLETED")
    logger.info(f"* Maximum return code: {max_rc}")
    logger.info(f"* Job duration: {job_duration}")
    logger.info("*" * 60)
    
    sys.exit(max_rc)


if __name__ == "__main__":
    main()