# Generated by CardDemo Agentic Converter on 2026-03-21 18:13:07
# Source: AWS CardDemo (Apache 2.0)

"""
POSTTRAN.jcl - Process and load daily transaction file and create transaction
category balance and update transaction master vsam

Converted from JCL to Python.

Original JCL: POSTTRAN.jcl
Job: POSTTRAN
"""

import os
import sys
import logging
import subprocess
from datetime import datetime

# Configure logging (replaces SYSPRINT/SYSOUT=*)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)


def run_step15():
    """
    STEP15 - EXEC PGM=CBTRN02C
    
    Process and load daily transaction file and create transaction
    category balance and update transaction master vsam
    
    DD allocations:
    - STEPLIB:  AWS.M2.CARDDEMO.LOADLIB
    - TRANFILE: AWS.M2.CARDDEMO.TRANSACT.VSAM.KSDS (VSAM KSDS input)
    - DALYTRAN: AWS.M2.CARDDEMO.DALYTRAN.PS (daily transactions input)
    - XREFFILE: AWS.M2.CARDDEMO.CARDXREF.VSAM.KSDS (card xref VSAM input)
    - DALYREJS: AWS.M2.CARDDEMO.DALYREJS(+1) (daily rejects output - GDG)
    - ACCTFILE: AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS (account data VSAM)
    - TCATBALF: AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS (transaction category balance VSAM)
    """
    logger.info("=" * 60)
    logger.info("STEP15 - EXEC PGM=CBTRN02C")
    logger.info("Process daily transaction file and update transaction master")
    logger.info("=" * 60)
    
    # DD Name allocations from environment variables
    steplib = os.getenv("DD_STEPLIB", "data/loadlib")
    tranfile = os.getenv("DD_TRANFILE", "data/transact.vsam.ksds.dat")
    dalytran = os.getenv("DD_DALYTRAN", "data/dalytran.ps.dat")
    xreffile = os.getenv("DD_XREFFILE", "data/cardxref.vsam.ksds.dat")
    acctfile = os.getenv("DD_ACCTFILE", "data/acctdata.vsam.ksds.dat")
    tcatbalf = os.getenv("DD_TCATBALF", "data/tcatbalf.vsam.ksds.dat")
    
    # GDG (+1) simulation for DALYREJS - create timestamped filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    dalyrejs = os.getenv("DD_DALYREJS", f"data/dalyrejs_{timestamp}.dat")
    
    # Log DD allocations
    logger.info("DD Allocations:")
    logger.info(f"  STEPLIB:  {steplib}")
    logger.info(f"  TRANFILE: {tranfile}")
    logger.info(f"  DALYTRAN: {dalytran}")
    logger.info(f"  XREFFILE: {xreffile}")
    logger.info(f"  DALYREJS: {dalyrejs} (GDG +1)")
    logger.info(f"  ACCTFILE: {acctfile}")
    logger.info(f"  TCATBALF: {tcatbalf}")
    
    # Ensure data directory exists
    os.makedirs("data", exist_ok=True)
    
    # Build environment for subprocess
    env = os.environ.copy()
    env["DD_STEPLIB"] = steplib
    env["DD_TRANFILE"] = tranfile
    env["DD_DALYTRAN"] = dalytran
    env["DD_XREFFILE"] = xreffile
    env["DD_DALYREJS"] = dalyrejs
    env["DD_ACCTFILE"] = acctfile
    env["DD_TCATBALF"] = tcatbalf
    
    # EXEC PGM=CBTRN02C
    program_name = "CBTRN02C"
    program_file = f"{program_name.lower()}.py"
    
    logger.info(f"Executing program: {program_name}")
    
    # Check if program file exists BEFORE attempting to run
    if not os.path.exists(program_file):
        logger.warning(f"Program {program_file} not found. Skipping.")
        return 0
    
    try:
        result = subprocess.run([sys.executable, program_file], env=env)
        rc = result.returncode
        logger.info(f"Program {program_name} completed with return code: {rc}")
        return rc
    except Exception as e:
        logger.error(f"Error running {program_file}: {e}")
        return 8


def main():
    """
    Main function - POSTTRAN Job
    
    Process and load daily transaction file and create transaction
    category balance and update transaction master vsam
    """
    logger.info("*" * 60)
    logger.info("* POSTTRAN JOB - Started")
    logger.info("* Process and load daily transaction file")
    logger.info("* Create transaction category balance")
    logger.info("* Update transaction master VSAM")
    logger.info("*" * 60)
    
    job_start_time = datetime.now()
    logger.info(f"Job started at: {job_start_time.isoformat()}")
    
    max_rc = 0
    
    # Execute STEP15 - CBTRN02C
    rc = run_step15()
    logger.info(f"STEP15 return code: {rc}")
    max_rc = max(max_rc, rc)
    
    if rc > 4:
        logger.error(f"STEP15 failed with return code {rc}")
        # Continue processing or stop based on condition code
        # In JCL this would be handled by COND parameter
    
    job_end_time = datetime.now()
    job_duration = job_end_time - job_start_time
    
    logger.info("*" * 60)
    logger.info(f"* POSTTRAN JOB - Completed")
    logger.info(f"* Job ended at: {job_end_time.isoformat()}")
    logger.info(f"* Job duration: {job_duration}")
    logger.info(f"* Maximum return code: {max_rc}")
    logger.info("*" * 60)
    
    sys.exit(max_rc)


if __name__ == "__main__":
    main()