# Generated by CardDemo Agentic Converter on 2026-03-21 18:14:16
# Source: AWS CardDemo (Apache 2.0)

"""
TCATBALF.jcl - Define Transaction Category Balance VSAM File

Converted from JCL to Python.
Original job: TCATBALF - DEFINE TRANCAT BAL

Steps:
  STEP05 - Delete existing VSAM cluster if it exists
  STEP10 - Define new VSAM KSDS cluster
  STEP15 - Copy data from flat file to VSAM file
"""

import json
import logging
import os
import shutil
import sys
from datetime import datetime

# Configure logging (replaces SYSPRINT DD SYSOUT=*)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def step05_delete_vsam():
    """
    STEP05 - DELETE TRANSACTION CATEGORY BALANCE VSAM FILE IF ONE ALREADY EXISTS
    
    Original JCL:
      //STEP05 EXEC PGM=IDCAMS
      DELETE AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS CLUSTER
      SET MAXCC = 0
    """
    logger.info("=" * 60)
    logger.info("STEP05 - DELETE VSAM CLUSTER (IDCAMS)")
    logger.info("=" * 60)
    
    # DD allocations for this step
    vsam_file = os.getenv("DD_TCATBALV", "data/AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS")
    vsam_metadata = f"{vsam_file}.metadata.json"
    vsam_data = f"{vsam_file}.DATA"
    vsam_index = f"{vsam_file}.INDEX"
    
    logger.info(f"Target VSAM cluster: {vsam_file}")
    
    # DELETE CLUSTER - remove all associated files
    files_to_delete = [vsam_file, vsam_metadata, vsam_data, vsam_index]
    
    for file_path in files_to_delete:
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                logger.info(f"Deleted: {file_path}")
            except OSError as e:
                logger.warning(f"Could not delete {file_path}: {e}")
        else:
            logger.info(f"File not found (OK): {file_path}")
    
    # SET MAXCC = 0 - unconditional success
    logger.info("SET MAXCC = 0 - Returning success regardless of delete outcome")
    return 0


def step10_define_vsam():
    """
    STEP10 - DEFINE TRANSACTION CATEGORY BALANCE VSAM FILE
    
    Original JCL:
      //STEP10 EXEC PGM=IDCAMS
      DEFINE CLUSTER (NAME(AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS)
             CYLINDERS(1 5)
             VOLUMES(AWSHJ1)
             KEYS(17 0)
             RECORDSIZE(50 50)
             SHAREOPTIONS(2 3)
             ERASE
             INDEXED)
             DATA (NAME(AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS.DATA))
             INDEX (NAME(AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS.INDEX))
    """
    logger.info("=" * 60)
    logger.info("STEP10 - DEFINE VSAM CLUSTER (IDCAMS)")
    logger.info("=" * 60)
    
    # DD allocations
    vsam_file = os.getenv("DD_TCATBALV", "data/AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS")
    vsam_metadata = f"{vsam_file}.metadata.json"
    
    logger.info(f"Defining VSAM cluster: {vsam_file}")
    
    # Ensure data directory exists
    data_dir = os.path.dirname(vsam_file)
    if data_dir and not os.path.exists(data_dir):
        os.makedirs(data_dir)
        logger.info(f"Created directory: {data_dir}")
    
    # Create empty VSAM data file
    try:
        with open(vsam_file, 'wb') as f:
            pass  # Create empty file
        logger.info(f"Created VSAM data file: {vsam_file}")
    except IOError as e:
        logger.error(f"Failed to create VSAM file: {e}")
        return 12
    
    # Write VSAM cluster metadata sidecar (simulates IDCAMS catalog entry)
    metadata = {
        "name": "AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS",
        "type": "KSDS",
        "key_length": 17,
        "key_offset": 0,
        "record_size": 50,
        "record_size_max": 50,
        "primary_allocation": "1 CYLINDERS",
        "secondary_allocation": "5 CYLINDERS",
        "volumes": ["AWSHJ1"],
        "shareoptions": [2, 3],
        "erase": True,
        "indexed": True,
        "data_component": "AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS.DATA",
        "index_component": "AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS.INDEX",
        "created_at": datetime.now().isoformat()
    }
    
    try:
        with open(vsam_metadata, 'w') as f:
            json.dump(metadata, f, indent=2)
        logger.info(f"Created VSAM metadata: {vsam_metadata}")
    except IOError as e:
        logger.error(f"Failed to create metadata file: {e}")
        return 12
    
    logger.info("VSAM cluster defined successfully")
    logger.info(f"  Key length: {metadata['key_length']}")
    logger.info(f"  Key offset: {metadata['key_offset']}")
    logger.info(f"  Record size: {metadata['record_size']}")
    
    return 0


def step15_repro_data():
    """
    STEP15 - COPY DATA FROM FLAT FILE TO VSAM FILE
    
    Original JCL:
      //STEP15 EXEC PGM=IDCAMS
      //TCATBAL DD DISP=SHR,DSN=AWS.M2.CARDDEMO.TCATBALF.PS
      //TCATBALV DD DISP=OLD,DSN=AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS
      REPRO INFILE(TCATBAL) OUTFILE(TCATBALV)
    """
    logger.info("=" * 60)
    logger.info("STEP15 - REPRO DATA TO VSAM (IDCAMS)")
    logger.info("=" * 60)
    
    # DD allocations
    infile = os.getenv("DD_TCATBAL", "data/AWS.M2.CARDDEMO.TCATBALF.PS")
    outfile = os.getenv("DD_TCATBALV", "data/AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS")
    
    logger.info(f"DD TCATBAL (input):  {infile}")
    logger.info(f"DD TCATBALV (output): {outfile}")
    
    # REPRO INFILE(TCATBAL) OUTFILE(TCATBALV)
    if not os.path.exists(infile):
        logger.error(f"Input file not found: {infile}")
        return 12
    
    try:
        shutil.copyfile(infile, outfile)
        
        # Get record count for logging
        file_size = os.path.getsize(outfile)
        # Assuming 50-byte fixed records as per RECORDSIZE(50 50)
        record_size = 50
        record_count = file_size // record_size if file_size > 0 else 0
        
        logger.info(f"REPRO completed successfully")
        logger.info(f"  Source file size: {os.path.getsize(infile)} bytes")
        logger.info(f"  Records copied: {record_count} (estimated)")
        
    except IOError as e:
        logger.error(f"REPRO failed: {e}")
        return 12
    
    return 0


def main():
    """
    Main function - TCATBALF job execution
    
    Original JCL:
      //TCATBALF JOB 'DEFINE TRANCAT BAL',CLASS=A,MSGCLASS=0,
      // NOTIFY=&SYSUID
    """
    logger.info("*" * 60)
    logger.info("* TCATBALF - DEFINE TRANSACTION CATEGORY BALANCE FILE")
    logger.info("* Converted from JCL to Python")
    logger.info("*" * 60)
    
    max_rc = 0
    
    # STEP05 - Delete existing VSAM cluster
    rc = step05_delete_vsam()
    logger.info(f"STEP05 completed with RC={rc}")
    max_rc = max(max_rc, rc)
    
    if max_rc > 8:
        logger.error(f"Job terminated due to error. MAXCC={max_rc}")
        sys.exit(max_rc)
    
    # STEP10 - Define new VSAM cluster
    rc = step10_define_vsam()
    logger.info(f"STEP10 completed with RC={rc}")
    max_rc = max(max_rc, rc)
    
    if max_rc > 8:
        logger.error(f"Job terminated due to error. MAXCC={max_rc}")
        sys.exit(max_rc)
    
    # STEP15 - Copy data to VSAM
    rc = step15_repro_data()
    logger.info(f"STEP15 completed with RC={rc}")
    max_rc = max(max_rc, rc)
    
    logger.info("*" * 60)
    logger.info(f"* TCATBALF Job completed. MAXCC={max_rc}")
    logger.info("*" * 60)
    
    sys.exit(max_rc)


if __name__ == "__main__":
    main()