// Generated by CardDemo Agentic Converter on 2026-03-21 16:04:49
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;

class AccountRecordTest {

    private AccountRecord record;

    @BeforeEach
    void setUp() {
        record = new AccountRecord();
    }

    // Test that default constructor initializes all fields correctly
    @Test
    void testDefaultConstructorInitializesFields() {
        assertEquals(0L, record.acctId);
        assertEquals("", record.acctActiveStatus);
        assertEquals(BigDecimal.ZERO, record.acctCurrBal);
        assertEquals(BigDecimal.ZERO, record.acctCreditLimit);
        assertEquals(BigDecimal.ZERO, record.acctCashCreditLimit);
        assertEquals("", record.acctOpenDate);
        assertEquals("", record.acctExpiraionDate);
        assertEquals("", record.acctReissueDate);
        assertEquals(BigDecimal.ZERO, record.acctCurrCycCredit);
        assertEquals(BigDecimal.ZERO, record.acctCurrCycDebit);
        assertEquals("", record.acctAddrZip);
        assertEquals("", record.acctGroupId);
    }

    // Test that RECORD_LENGTH constant is correctly set to 300
    @Test
    void testRecordLengthConstant() {
        assertEquals(300, AccountRecord.RECORD_LENGTH);
    }

    // Test fromLine() with valid fixed-length input parses account ID correctly
    @Test
    void testFromLineWithValidInputParsesAccountId() {
        // Build a 300-character line with account ID "12345678901"
        StringBuilder sb = new StringBuilder();
        sb.append("12345678901"); // acctId (11 chars)
        sb.append("A");           // acctActiveStatus (1 char)
        sb.append("0000100000000"); // acctCurrBal (13 chars) = 1000000.00
        sb.append("0000200000000"); // acctCreditLimit (13 chars)
        sb.append("0000050000000"); // acctCashCreditLimit (13 chars)
        sb.append("2023-01-01"); // acctOpenDate (10 chars)
        sb.append("2028-12-31"); // acctExpiraionDate (10 chars)
        sb.append("2025-06-15"); // acctReissueDate (10 chars)
        sb.append("0000001000000"); // acctCurrCycCredit (13 chars)
        sb.append("0000000500000"); // acctCurrCycDebit (13 chars)
        sb.append("12345-6789"); // acctAddrZip (10 chars)
        sb.append("GROUP001  "); // acctGroupId (10 chars)
        // Pad to 300 chars with filler
        while (sb.length() < 300) {
            sb.append(" ");
        }
        String line = sb.toString();

        AccountRecord result = AccountRecord.fromLine(line);

        assertEquals(12345678901L, result.acctId);
        assertEquals("A", result.acctActiveStatus);
        assertEquals("2023-01-01", result.acctOpenDate);
        assertEquals("2028-12-31", result.acctExpiraionDate);
        assertEquals("2025-06-15", result.acctReissueDate);
        assertEquals("12345-6789", result.acctAddrZip);
        assertEquals("GROUP001  ", result.acctGroupId);
    }

    // Test fromLine() with null input handles gracefully
    @Test
    void testFromLineWithNullInputHandlesGracefully() {
        AccountRecord result = AccountRecord.fromLine(null);
        
        assertNotNull(result);
        assertEquals(0L, result.acctId);
        assertEquals("", result.acctActiveStatus);
    }

    // Test fromLine() with empty string input handles gracefully
    @Test
    void testFromLineWithEmptyInputHandlesGracefully() {
        AccountRecord result = AccountRecord.fromLine("");
        
        assertNotNull(result);
        assertEquals(0L, result.acctId);
        assertEquals("", result.acctActiveStatus);
    }

    // Test fromLine() with short input string handles gracefully
    @Test
    void testFromLineWithShortInputHandlesGracefully() {
        String shortLine = "12345678901A"; // Only 12 characters
        
        AccountRecord result = AccountRecord.fromLine(shortLine);
        
        assertNotNull(result);
        assertEquals(12345678901L, result.acctId);
        assertEquals("A", result.acctActiveStatus);
    }

    // Test fromLine() parses active status field correctly
    @Test
    void testFromLineParsesActiveStatus() {
        StringBuilder sb = new StringBuilder();
        sb.append("00000000001"); // acctId (11 chars)
        sb.append("Y");           // acctActiveStatus (1 char) - Active
        while (sb.length() < 300) {
            sb.append("0");
        }
        
        AccountRecord result = AccountRecord.fromLine(sb.toString());
        
        assertEquals("Y", result.acctActiveStatus);
    }

    // Test fromLine() with inactive status
    @Test
    void testFromLineParsesInactiveStatus() {
        StringBuilder sb = new StringBuilder();
        sb.append("00000000001"); // acctId (11 chars)
        sb.append("N");           // acctActiveStatus (1 char) - Inactive
        while (sb.length() < 300) {
            sb.append("0");
        }
        
        AccountRecord result = AccountRecord.fromLine(sb.toString());
        
        assertEquals("N", result.acctActiveStatus);
    }

    // Test fromLine() parses dates correctly
    @Test
    void testFromLineParsesDatesCorrectly() {
        StringBuilder sb = new StringBuilder();
        sb.append("00000000001"); // acctId (11 chars)
        sb.append("A");           // acctActiveStatus (1 char)
        sb.append("0000000000000"); // acctCurrBal (13 chars)
        sb.append("0000000000000"); // acctCreditLimit (13 chars)
        sb.append("0000000000000"); // acctCashCreditLimit (13 chars)
        sb.append("2020-05-15"); // acctOpenDate (10 chars)
        sb.append("2030-05-15"); // acctExpiraionDate (10 chars)
        sb.append("2025-05-15"); // acctReissueDate (10 chars)
        while (sb.length() < 300) {
            sb.append(" ");
        }
        
        AccountRecord result = AccountRecord.fromLine(sb.toString());
        
        assertEquals("2020-05-15", result.acctOpenDate);
        assertEquals("2030-05-15", result.acctExpiraionDate);
        assertEquals("2025-05-15", result.acctReissueDate);
    }

    // Test fromLine() handles leading zeros in account ID
    @Test
    void testFromLineHandlesLeadingZerosInAccountId() {
        StringBuilder sb = new StringBuilder();
        sb.append("00000000123"); // acctId with leading zeros (11 chars)
        sb.append("A");           // acctActiveStatus (1 char)
        while (sb.length() < 300) {
            sb.append("0");
        }
        
        AccountRecord result = AccountRecord.fromLine(sb.toString());
        
        assertEquals(123L, result.acctId);
    }

    // Test fromLine() parses zip code field correctly
    @Test
    void testFromLineParsesZipCode() {
        StringBuilder sb = new StringBuilder();
        sb.append("00000000001"); // acctId (11 chars) - positions 0-10
        sb.append("A");           // acctActiveStatus (1 char) - position 11
        sb.append("0000000000000"); // acctCurrBal (13 chars) - positions 12-24
        sb.append("0000000000000"); // acctCreditLimit (13 chars) - positions 25-37
        sb.append("0000000000000"); // acctCashCreditLimit (13 chars) - positions 38-50
        sb.append("2020-05-15"); // acctOpenDate (10 chars) - positions 51-60
        sb.append("2030-05-15"); // acctExpiraionDate (10 chars) - positions 61-70
        sb.append("2025-05-15"); // acctReissueDate (10 chars) - positions 71-80
        sb.append("0000000000000"); // acctCurrCycCredit (13 chars) - positions 81-93
        sb.append("0000000000000"); // acctCurrCycDebit (13 chars) - positions 94-106
        sb.append("90210     "); // acctAddrZip (10 chars) - positions 107-116
        sb.append("GRPTEST   "); // acctGroupId (10 chars) - positions 117-126
        while (sb.length() < 300) {
            sb.append(" ");
        }
        
        AccountRecord result = AccountRecord.fromLine(sb.toString());
        
        assertEquals("90210     ", result.acctAddrZip);
        assertEquals("GRPTEST   ", result.acctGroupId);
    }

    // Test fromLine() parses group ID field correctly
    @Test
    void testFromLineParsesGroupId() {
        StringBuilder sb = new StringBuilder();
        sb.append("00000000001"); // acctId (11 chars)
        sb.append("A");           // acctActiveStatus (1 char)
        sb.append("0000000000000"); // acctCurrBal (13 chars)
        sb.append("0000000000000"); // acctCreditLimit (13 chars)
        sb.append("0000000000000"); // acctCashCreditLimit (13 chars)
        sb.append("2020-05-15"); // acctOpenDate (10 chars)
        sb.append("2030-05-15"); // acctExpiraionDate (10 chars)
        sb.append("2025-05-15"); // acctReissueDate (10 chars)
        sb.append("0000000000000"); // acctCurrCycCredit (13 chars)
        sb.append("0000000000000"); // acctCurrCycDebit (13 chars)
        sb.append("12345     "); // acctAddrZip (10 chars)
        sb.append("MYGROUP123"); // acctGroupId (10 chars)
        while (sb.length() < 300) {
            sb.append(" ");
        }
        
        AccountRecord result = AccountRecord.fromLine(sb.toString());
        
        assertEquals("MYGROUP123", result.acctGroupId);
    }

    // Test that fields can be modified after construction
    @Test
    void testFieldsAreModifiable() {
        record.acctId = 99999999999L;
        record.acctActiveStatus = "Y";
        record.acctCurrBal = new BigDecimal("5000.50");
        record.acctOpenDate = "2024-01-01";
        
        assertEquals(99999999999L, record.acctId);
        assertEquals("Y", record.acctActiveStatus);
        assertEquals(new BigDecimal("5000.50"), record.acctCurrBal);
        assertEquals("2024-01-01", record.acctOpenDate);
    }

    // Test fromLine() with all spaces input
    @Test
    void testFromLineWithAllSpacesInput() {
        String spaceLine = " ".repeat(300);
        
        AccountRecord result = AccountRecord.fromLine(spaceLine);
        
        assertNotNull(result);
        // Account ID should be 0 when parsing spaces/empty
        assertEquals(0L, result.acctId);
    }

    // Test fromLine() with maximum account ID value
    @Test
    void testFromLineWithMaxAccountId() {
        StringBuilder sb = new StringBuilder();
        sb.append("99999999999"); // Max 11-digit number
        sb.append("A");
        while (sb.length() < 300) {
            sb.append("0");
        }
        
        AccountRecord result = AccountRecord.fromLine(sb.toString());
        
        assertEquals(99999999999L, result.acctId);
    }
}