// Generated by CardDemo Agentic Converter on 2026-03-21 16:05:38
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class CardRecordTest {

    private CardRecord record;

    @BeforeEach
    void setUp() {
        record = new CardRecord();
    }

    // Test that default constructor initializes all fields to empty/zero values
    @Test
    void testDefaultConstructorInitializesFields() {
        assertEquals("", record.cardNum);
        assertEquals(0L, record.cardAcctId);
        assertEquals(0, record.cardCvvCd);
        assertEquals("", record.cardEmbossedName);
        assertEquals("", record.cardExpirationDate);
        assertEquals("", record.cardActiveStatus);
    }

    // Test that RECORD_LENGTH constant is correct
    @Test
    void testRecordLengthConstant() {
        assertEquals(150, CardRecord.RECORD_LENGTH);
    }

    // Test fromLine() with valid fixed-length input parses all fields correctly
    @Test
    void testFromLineWithValidInput() {
        StringBuilder line = new StringBuilder();
        line.append("1234567890123456"); // cardNum PIC X(16)
        line.append("00012345678");      // cardAcctId PIC 9(11)
        line.append("123");              // cardCvvCd PIC 9(03)
        line.append(String.format("%-50s", "John Doe")); // cardEmbossedName PIC X(50)
        line.append("2025-12-31");       // cardExpirationDate PIC X(10)
        line.append("Y");                // cardActiveStatus PIC X(01)
        line.append(String.format("%-59s", "")); // FILLER PIC X(59)

        CardRecord rec = CardRecord.fromLine(line.toString());

        assertEquals("1234567890123456", rec.cardNum);
        assertEquals(12345678L, rec.cardAcctId);
        assertEquals(123, rec.cardCvvCd);
        assertEquals(String.format("%-50s", "John Doe"), rec.cardEmbossedName);
        assertEquals("2025-12-31", rec.cardExpirationDate);
        assertEquals("Y", rec.cardActiveStatus);
    }

    // Test fromLine() with null input handles gracefully
    @Test
    void testFromLineWithNullInput() {
        CardRecord rec = CardRecord.fromLine(null);

        assertNotNull(rec);
        assertEquals("                ", rec.cardNum); // 16 spaces
        assertEquals(0L, rec.cardAcctId);
        assertEquals(0, rec.cardCvvCd);
    }

    // Test fromLine() with empty string input handles gracefully
    @Test
    void testFromLineWithEmptyInput() {
        CardRecord rec = CardRecord.fromLine("");

        assertNotNull(rec);
        assertEquals("                ", rec.cardNum); // 16 spaces
        assertEquals(0L, rec.cardAcctId);
        assertEquals(0, rec.cardCvvCd);
    }

    // Test fromLine() with short input pads to RECORD_LENGTH
    @Test
    void testFromLineWithShortInput() {
        String shortLine = "4111222233334444"; // Only cardNum provided

        CardRecord rec = CardRecord.fromLine(shortLine);

        assertNotNull(rec);
        assertEquals("4111222233334444", rec.cardNum);
        assertEquals(0L, rec.cardAcctId); // Spaces parsed as 0
        assertEquals(0, rec.cardCvvCd);   // Spaces parsed as 0
    }

    // Test toLine() produces correct length output
    @Test
    void testToLineProducesCorrectLength() {
        record.cardNum = "1234567890123456";
        record.cardAcctId = 12345678L;
        record.cardCvvCd = 123;
        record.cardEmbossedName = "Test User";
        record.cardExpirationDate = "2025-12-31";
        record.cardActiveStatus = "Y";

        String line = record.toLine();

        assertEquals(CardRecord.RECORD_LENGTH, line.length());
    }

    // Test toLine() roundtrip - fromLine then toLine should give same length
    @Test
    void testToLineFromLineRoundtrip() {
        StringBuilder originalLine = new StringBuilder();
        originalLine.append("9876543210123456"); // cardNum
        originalLine.append("00098765432");      // cardAcctId
        originalLine.append("456");              // cardCvvCd
        originalLine.append(String.format("%-50s", "Jane Smith")); // cardEmbossedName
        originalLine.append("2024-06-30");       // cardExpirationDate
        originalLine.append("N");                // cardActiveStatus
        originalLine.append(String.format("%-59s", "")); // FILLER

        String original = originalLine.toString();
        CardRecord rec = CardRecord.fromLine(original);
        String result = rec.toLine();

        assertEquals(CardRecord.RECORD_LENGTH, result.length());
        assertEquals(original.length(), result.length());
    }

    // Test toLine() roundtrip preserves field values
    @Test
    void testToLineFromLinePreservesValues() {
        record.cardNum = "5555444433332222";
        record.cardAcctId = 99999999999L;
        record.cardCvvCd = 999;
        record.cardEmbossedName = "Roundtrip Test";
        record.cardExpirationDate = "2030-01-01";
        record.cardActiveStatus = "A";

        String line = record.toLine();
        CardRecord parsed = CardRecord.fromLine(line);

        assertEquals(record.cardNum, parsed.cardNum);
        assertEquals(record.cardAcctId, parsed.cardAcctId);
        assertEquals(record.cardCvvCd, parsed.cardCvvCd);
        assertEquals(record.cardActiveStatus, parsed.cardActiveStatus);
        assertEquals(record.cardExpirationDate, parsed.cardExpirationDate);
    }

    // Test key() returns trimmed cardNum
    @Test
    void testKeyReturnsCorrectValue() {
        record.cardNum = "1234567890123456";

        assertEquals("1234567890123456", record.key());
    }

    // Test key() trims whitespace from cardNum
    @Test
    void testKeyTrimsWhitespace() {
        record.cardNum = "1234567890      ";

        assertEquals("1234567890", record.key());
    }

    // Test key() handles null cardNum gracefully
    @Test
    void testKeyWithNullCardNum() {
        record.cardNum = null;

        String key = record.key();
        
        assertEquals("", key);
    }

    // Test key() handles empty cardNum
    @Test
    void testKeyWithEmptyCardNum() {
        record.cardNum = "";

        assertEquals("", record.key());
    }

    // Test toLine() handles null field values
    @Test
    void testToLineWithNullFields() {
        record.cardNum = null;
        record.cardEmbossedName = null;
        record.cardExpirationDate = null;
        record.cardActiveStatus = null;

        String line = record.toLine();

        assertNotNull(line);
        assertEquals(CardRecord.RECORD_LENGTH, line.length());
    }

    // Test toLine() formats numeric fields with leading zeros
    @Test
    void testToLineFormatsNumericFieldsWithLeadingZeros() {
        record.cardNum = "1234567890123456";
        record.cardAcctId = 123L;
        record.cardCvvCd = 7;
        record.cardEmbossedName = "Test";
        record.cardExpirationDate = "2025-01-01";
        record.cardActiveStatus = "Y";

        String line = record.toLine();

        // Check cardAcctId is padded to 11 digits
        assertTrue(line.substring(16, 27).equals("00000000123"));
        // Check cardCvvCd is padded to 3 digits
        assertTrue(line.substring(27, 30).equals("007"));
    }

    // Test fromLine() with maximum numeric values
    @Test
    void testFromLineWithMaxNumericValues() {
        StringBuilder line = new StringBuilder();
        line.append("1234567890123456"); // cardNum
        line.append("99999999999");      // max cardAcctId PIC 9(11)
        line.append("999");              // max cardCvvCd PIC 9(03)
        line.append(String.format("%-50s", "Max Values Test"));
        line.append("2099-12-31");
        line.append("Y");
        line.append(String.format("%-59s", ""));

        CardRecord rec = CardRecord.fromLine(line.toString());

        assertEquals(99999999999L, rec.cardAcctId);
        assertEquals(999, rec.cardCvvCd);
    }

    // Test toLine() truncates oversized string fields
    @Test
    void testToLineTruncatesOversizedFields() {
        record.cardNum = "12345678901234567890"; // 20 chars, should truncate to 16
        record.cardAcctId = 12345L;
        record.cardCvvCd = 123;
        record.cardEmbossedName = "A".repeat(60); // 60 chars, should truncate to 50
        record.cardExpirationDate = "2025-12-31-EXTRA"; // Should truncate to 10
        record.cardActiveStatus = "YN"; // Should truncate to 1

        String line = record.toLine();

        assertEquals(CardRecord.RECORD_LENGTH, line.length());
        assertEquals("1234567890123456", line.substring(0, 16));
        assertEquals("A".repeat(50), line.substring(30, 80));
        assertEquals("2025-12-31", line.substring(80, 90));
        assertEquals("Y", line.substring(90, 91));
    }
}