// Generated by CardDemo Agentic Converter on 2026-03-21 16:06:19
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class CardXrefRecordTest {

    // Test that fromLine correctly parses a valid fixed-length input string
    @Test
    void testFromLineWithValidInput() {
        // Card number (16) + Customer ID (9) + Account ID (11) + Filler (14) = 50 bytes
        String line = "1234567890123456000123456001234567890012345678901234";
        
        CardXrefRecord rec = CardXrefRecord.fromLine(line);
        
        assertEquals("1234567890123456", rec.xrefCardNum);
        assertEquals(123456L, rec.xrefCustId);
        assertEquals(12345678900L, rec.xrefAcctId);
    }

    // Test that fromLine handles card number with spaces correctly
    @Test
    void testFromLineWithPaddedCardNumber() {
        String line = "4111222233334444000000001000000000001              ";
        
        CardXrefRecord rec = CardXrefRecord.fromLine(line);
        
        assertEquals("4111222233334444", rec.xrefCardNum);
        assertEquals(1L, rec.xrefCustId);
        assertEquals(1L, rec.xrefAcctId);
    }

    // Test that fromLine handles null input gracefully
    @Test
    void testFromLineWithNullInput() {
        CardXrefRecord rec = CardXrefRecord.fromLine(null);
        
        assertNotNull(rec);
        assertEquals("                ", rec.xrefCardNum);
        assertEquals(0L, rec.xrefCustId);
        assertEquals(0L, rec.xrefAcctId);
    }

    // Test that fromLine handles empty string input gracefully
    @Test
    void testFromLineWithEmptyInput() {
        CardXrefRecord rec = CardXrefRecord.fromLine("");
        
        assertNotNull(rec);
        assertEquals("                ", rec.xrefCardNum);
        assertEquals(0L, rec.xrefCustId);
        assertEquals(0L, rec.xrefAcctId);
    }

    // Test that fromLine handles short input string gracefully
    @Test
    void testFromLineWithShortInput() {
        String line = "1234567890123456";  // Only card number provided
        
        CardXrefRecord rec = CardXrefRecord.fromLine(line);
        
        assertEquals("1234567890123456", rec.xrefCardNum);
        assertEquals(0L, rec.xrefCustId);
        assertEquals(0L, rec.xrefAcctId);
    }

    // Test that toLine produces a string of correct length (RECORD_LENGTH = 50)
    @Test
    void testToLineProducesCorrectLength() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = "4111222233334444";
        rec.xrefCustId = 123456789L;
        rec.xrefAcctId = 98765432100L;
        
        String line = rec.toLine();
        
        assertEquals(CardXrefRecord.RECORD_LENGTH, line.length());
    }

    // Test roundtrip: fromLine then toLine should preserve data and produce same length
    @Test
    void testRoundtripFromLineToLine() {
        String originalLine = "9876543210123456000999888123456789012              ";
        
        CardXrefRecord rec = CardXrefRecord.fromLine(originalLine);
        String outputLine = rec.toLine();
        
        assertEquals(CardXrefRecord.RECORD_LENGTH, outputLine.length());
        
        // Parse the output and verify fields match
        CardXrefRecord rec2 = CardXrefRecord.fromLine(outputLine);
        assertEquals(rec.xrefCardNum, rec2.xrefCardNum);
        assertEquals(rec.xrefCustId, rec2.xrefCustId);
        assertEquals(rec.xrefAcctId, rec2.xrefAcctId);
    }

    // Test that toLine correctly formats numeric fields with leading zeros
    @Test
    void testToLineFormatsNumericFieldsCorrectly() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = "CARD1234";
        rec.xrefCustId = 42L;
        rec.xrefAcctId = 100L;
        
        String line = rec.toLine();
        
        // Customer ID should be 9 digits with leading zeros
        assertEquals("000000042", line.substring(16, 25));
        // Account ID should be 11 digits with leading zeros
        assertEquals("00000000100", line.substring(25, 36));
    }

    // Test that key() returns the trimmed card number
    @Test
    void testKeyReturnsCorrectValue() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = "4111222233334444";
        
        String key = rec.key();
        
        assertEquals("4111222233334444", key);
    }

    // Test that key() trims whitespace from card number
    @Test
    void testKeyTrimsWhitespace() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = "CARD5678        ";
        
        String key = rec.key();
        
        assertEquals("CARD5678", key);
    }

    // Test that key() handles null card number gracefully
    @Test
    void testKeyWithNullCardNumber() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = null;
        
        String key = rec.key();
        
        assertEquals("", key);
    }

    // Test that toString returns a meaningful representation
    @Test
    void testToStringContainsAllFields() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = "1111222233334444";
        rec.xrefCustId = 12345L;
        rec.xrefAcctId = 67890L;
        
        String str = rec.toString();
        
        assertTrue(str.contains("1111222233334444"));
        assertTrue(str.contains("12345"));
        assertTrue(str.contains("67890"));
        assertTrue(str.contains("CardXrefRecord"));
    }

    // Test RECORD_LENGTH constant is correct
    @Test
    void testRecordLengthConstant() {
        assertEquals(50, CardXrefRecord.RECORD_LENGTH);
    }

    // Test toLine with null card number is handled gracefully
    @Test
    void testToLineWithNullCardNumber() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = null;
        rec.xrefCustId = 1L;
        rec.xrefAcctId = 2L;
        
        String line = rec.toLine();
        
        assertEquals(CardXrefRecord.RECORD_LENGTH, line.length());
        // First 16 chars should be spaces for null card number
        assertEquals("                ", line.substring(0, 16));
    }

    // Test parsing maximum values for numeric fields
    @Test
    void testFromLineWithMaxNumericValues() {
        // Max 9-digit customer ID: 999999999
        // Max 11-digit account ID: 99999999999
        String line = "MAXVALUECARD    99999999999999999999              ";
        
        CardXrefRecord rec = CardXrefRecord.fromLine(line);
        
        assertEquals(999999999L, rec.xrefCustId);
        assertEquals(99999999999L, rec.xrefAcctId);
    }

    // Test that toLine handles zero values correctly
    @Test
    void testToLineWithZeroValues() {
        CardXrefRecord rec = new CardXrefRecord();
        rec.xrefCardNum = "ZEROTEST";
        rec.xrefCustId = 0L;
        rec.xrefAcctId = 0L;
        
        String line = rec.toLine();
        
        assertEquals("000000000", line.substring(16, 25));
        assertEquals("00000000000", line.substring(25, 36));
    }
}