// Generated by CardDemo Agentic Converter on 2026-03-21 16:07:19
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class CustomerRecordTest {

    private CustomerRecord record;

    @BeforeEach
    void setUp() {
        record = new CustomerRecord();
    }

    // Test that default constructor initializes all fields correctly
    @Test
    void testDefaultConstructorInitializesFields() {
        assertEquals(0L, record.custId);
        assertEquals("", record.custFirstName);
        assertEquals("", record.custMiddleName);
        assertEquals("", record.custLastName);
        assertEquals("", record.custAddrLine1);
        assertEquals("", record.custAddrLine2);
        assertEquals("", record.custAddrLine3);
        assertEquals("", record.custAddrStateCd);
        assertEquals("", record.custAddrCountryCd);
        assertEquals("", record.custAddrZip);
        assertEquals("", record.custPhoneNum1);
        assertEquals("", record.custPhoneNum2);
        assertEquals(0L, record.custSsn);
        assertEquals("", record.custGovtIssuedId);
        assertEquals("", record.custDobYyyyMmDd);
        assertEquals("", record.custEftAccountId);
        assertEquals("", record.custPriCardHolderInd);
        assertEquals(0, record.custFicoCreditScore);
    }

    // Test that RECORD_LENGTH constant is set correctly
    @Test
    void testRecordLengthConstant() {
        assertEquals(500, CustomerRecord.RECORD_LENGTH);
    }

    // Test fromLine with valid fixed-length input parses fields correctly
    @Test
    void testFromLineWithValidInput() {
        StringBuilder sb = new StringBuilder();
        sb.append("123456789");                          // custId - 9 bytes
        sb.append(padRight("John", 25));                 // custFirstName - 25 bytes
        sb.append(padRight("William", 25));              // custMiddleName - 25 bytes
        sb.append(padRight("Doe", 25));                  // custLastName - 25 bytes
        sb.append(padRight("123 Main Street", 50));      // custAddrLine1 - 50 bytes
        sb.append(padRight("Apt 4B", 50));               // custAddrLine2 - 50 bytes
        sb.append(padRight("Building C", 50));           // custAddrLine3 - 50 bytes
        sb.append("TX");                                 // custAddrStateCd - 2 bytes
        sb.append("USA");                                // custAddrCountryCd - 3 bytes
        sb.append(padRight("75001", 10));                // custAddrZip - 10 bytes
        sb.append(padRight("555-123-4567", 15));         // custPhoneNum1 - 15 bytes
        sb.append(padRight("555-987-6543", 15));         // custPhoneNum2 - 15 bytes
        sb.append("987654321");                          // custSsn - 9 bytes
        sb.append(padRight("DL123456789", 20));          // custGovtIssuedId - 20 bytes
        sb.append(padRight("1990-05-15", 10));           // custDobYyyyMmDd - 10 bytes
        sb.append(padRight("EFT12345", 10));             // custEftAccountId - 10 bytes
        sb.append("Y");                                  // custPriCardHolderInd - 1 byte
        sb.append("750");                                // custFicoCreditScore - 3 bytes
        // Pad to full record length
        while (sb.length() < CustomerRecord.RECORD_LENGTH) {
            sb.append(" ");
        }

        CustomerRecord rec = CustomerRecord.fromLine(sb.toString());

        assertEquals(123456789L, rec.custId);
        assertEquals("John", rec.custFirstName.trim());
        assertEquals("William", rec.custMiddleName.trim());
        assertEquals("Doe", rec.custLastName.trim());
        assertEquals("123 Main Street", rec.custAddrLine1.trim());
        assertEquals("Apt 4B", rec.custAddrLine2.trim());
        assertEquals("Building C", rec.custAddrLine3.trim());
        assertEquals("TX", rec.custAddrStateCd);
        assertEquals("USA", rec.custAddrCountryCd);
        assertEquals("75001", rec.custAddrZip.trim());
        assertEquals("555-123-4567", rec.custPhoneNum1.trim());
        assertEquals("555-987-6543", rec.custPhoneNum2.trim());
        assertEquals(987654321L, rec.custSsn);
        assertEquals("DL123456789", rec.custGovtIssuedId.trim());
        assertEquals("1990-05-15", rec.custDobYyyyMmDd.trim());
        assertEquals("EFT12345", rec.custEftAccountId.trim());
        assertEquals("Y", rec.custPriCardHolderInd);
        assertEquals(750, rec.custFicoCreditScore);
    }

    // Test fromLine with null input handles gracefully
    @Test
    void testFromLineWithNullInput() {
        CustomerRecord rec = CustomerRecord.fromLine(null);
        assertNotNull(rec);
        assertEquals(0L, rec.custId);
        assertEquals("", rec.custFirstName.trim());
    }

    // Test fromLine with empty string handles gracefully
    @Test
    void testFromLineWithEmptyInput() {
        CustomerRecord rec = CustomerRecord.fromLine("");
        assertNotNull(rec);
        assertEquals(0L, rec.custId);
        assertEquals("", rec.custFirstName.trim());
    }

    // Test fromLine with short line pads correctly
    @Test
    void testFromLineWithShortLine() {
        String shortLine = "000000001John";
        CustomerRecord rec = CustomerRecord.fromLine(shortLine);
        assertNotNull(rec);
        assertEquals(1L, rec.custId);
    }

    // Test fromLine parses numeric fields correctly with leading zeros
    @Test
    void testFromLineNumericFieldsWithLeadingZeros() {
        StringBuilder sb = new StringBuilder();
        sb.append("000000001");                          // custId with leading zeros
        sb.append(padRight("", 25));                     // custFirstName
        sb.append(padRight("", 25));                     // custMiddleName
        sb.append(padRight("", 25));                     // custLastName
        sb.append(padRight("", 50));                     // custAddrLine1
        sb.append(padRight("", 50));                     // custAddrLine2
        sb.append(padRight("", 50));                     // custAddrLine3
        sb.append("  ");                                 // custAddrStateCd
        sb.append("   ");                                // custAddrCountryCd
        sb.append(padRight("", 10));                     // custAddrZip
        sb.append(padRight("", 15));                     // custPhoneNum1
        sb.append(padRight("", 15));                     // custPhoneNum2
        sb.append("000000123");                          // custSsn with leading zeros
        sb.append(padRight("", 20));                     // custGovtIssuedId
        sb.append(padRight("", 10));                     // custDobYyyyMmDd
        sb.append(padRight("", 10));                     // custEftAccountId
        sb.append(" ");                                  // custPriCardHolderInd
        sb.append("099");                                // custFicoCreditScore with leading zero
        while (sb.length() < CustomerRecord.RECORD_LENGTH) {
            sb.append(" ");
        }

        CustomerRecord rec = CustomerRecord.fromLine(sb.toString());

        assertEquals(1L, rec.custId);
        assertEquals(123L, rec.custSsn);
        assertEquals(99, rec.custFicoCreditScore);
    }

    // Test fromLine with all spaces for numeric fields returns zero
    @Test
    void testFromLineWithSpacesInNumericFields() {
        StringBuilder sb = new StringBuilder();
        sb.append("         ");                          // custId - all spaces
        sb.append(padRight("", 25));                     // custFirstName
        sb.append(padRight("", 25));                     // custMiddleName
        sb.append(padRight("", 25));                     // custLastName
        sb.append(padRight("", 50));                     // custAddrLine1
        sb.append(padRight("", 50));                     // custAddrLine2
        sb.append(padRight("", 50));                     // custAddrLine3
        sb.append("  ");                                 // custAddrStateCd
        sb.append("   ");                                // custAddrCountryCd
        sb.append(padRight("", 10));                     // custAddrZip
        sb.append(padRight("", 15));                     // custPhoneNum1
        sb.append(padRight("", 15));                     // custPhoneNum2
        sb.append("         ");                          // custSsn - all spaces
        sb.append(padRight("", 20));                     // custGovtIssuedId
        sb.append(padRight("", 10));                     // custDobYyyyMmDd
        sb.append(padRight("", 10));                     // custEftAccountId
        sb.append(" ");                                  // custPriCardHolderInd
        sb.append("   ");                                // custFicoCreditScore - all spaces
        while (sb.length() < CustomerRecord.RECORD_LENGTH) {
            sb.append(" ");
        }

        CustomerRecord rec = CustomerRecord.fromLine(sb.toString());

        assertEquals(0L, rec.custId);
        assertEquals(0L, rec.custSsn);
        assertEquals(0, rec.custFicoCreditScore);
    }

    // Test that field assignments work correctly
    @Test
    void testFieldAssignments() {
        record.custId = 999999999L;
        record.custFirstName = "TestFirst";
        record.custLastName = "TestLast";
        record.custSsn = 123456789L;
        record.custFicoCreditScore = 850;

        assertEquals(999999999L, record.custId);
        assertEquals("TestFirst", record.custFirstName);
        assertEquals("TestLast", record.custLastName);
        assertEquals(123456789L, record.custSsn);
        assertEquals(850, record.custFicoCreditScore);
    }

    // Test boundary values for custId (max 9 digits)
    @Test
    void testCustIdBoundaryValues() {
        String maxIdLine = "999999999" + padRight("", 491);
        CustomerRecord rec = CustomerRecord.fromLine(maxIdLine);
        assertEquals(999999999L, rec.custId);
    }

    // Test boundary values for custFicoCreditScore (max 3 digits)
    @Test
    void testFicoCreditScoreBoundaryValues() {
        StringBuilder sb = new StringBuilder();
        sb.append("000000001");                          // custId
        sb.append(padRight("", 25));                     // custFirstName
        sb.append(padRight("", 25));                     // custMiddleName
        sb.append(padRight("", 25));                     // custLastName
        sb.append(padRight("", 50));                     // custAddrLine1
        sb.append(padRight("", 50));                     // custAddrLine2
        sb.append(padRight("", 50));                     // custAddrLine3
        sb.append("  ");                                 // custAddrStateCd
        sb.append("   ");                                // custAddrCountryCd
        sb.append(padRight("", 10));                     // custAddrZip
        sb.append(padRight("", 15));                     // custPhoneNum1
        sb.append(padRight("", 15));                     // custPhoneNum2
        sb.append("000000000");                          // custSsn
        sb.append(padRight("", 20));                     // custGovtIssuedId
        sb.append(padRight("", 10));                     // custDobYyyyMmDd
        sb.append(padRight("", 10));                     // custEftAccountId
        sb.append(" ");                                  // custPriCardHolderInd
        sb.append("999");                                // custFicoCreditScore - max value
        while (sb.length() < CustomerRecord.RECORD_LENGTH) {
            sb.append(" ");
        }

        CustomerRecord rec = CustomerRecord.fromLine(sb.toString());
        assertEquals(999, rec.custFicoCreditScore);
    }

    // Helper method to pad string to specified length
    private String padRight(String s, int length) {
        if (s == null) s = "";
        if (s.length() >= length) {
            return s.substring(0, length);
        }
        StringBuilder sb = new StringBuilder(s);
        while (sb.length() < length) {
            sb.append(" ");
        }
        return sb.toString();
    }
}