// Generated by CardDemo Agentic Converter on 2026-03-21 16:11:03
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;

class DailyTranRecordTest {

    private String validLine;

    @BeforeEach
    void setUp() {
        // Build a valid 350-character fixed-length line
        StringBuilder sb = new StringBuilder();
        sb.append(padRight("TXN1234567890123", 16));  // dalytranId (0-16)
        sb.append(padRight("CR", 2));                  // dalytranTypeCd (16-18)
        sb.append(padLeft("1234", 4, '0'));            // dalytranCatCd (18-22)
        sb.append(padRight("ONLINE", 10));             // dalytranSource (22-32)
        sb.append(padRight("Purchase at store", 100)); // dalytranDesc (32-132)
        sb.append(padLeft("00012345678", 12, '0'));    // dalytranAmt S9(09)V99 = 123456.78 (132-144)
        sb.append(padLeft("123456789", 9, '0'));       // dalytranMerchantId (144-153)
        sb.append(padRight("ACME Corporation", 50));   // dalytranMerchantName (153-203)
        sb.append(padRight("New York", 50));           // dalytranMerchantCity (203-253)
        sb.append(padRight("10001", 10));              // dalytranMerchantZip (253-263)
        sb.append(padRight("4111111111111111", 16));   // dalytranCardNum (263-279)
        sb.append(padRight("2024-01-15T10:30:00.00000", 26)); // dalytranOrigTs (279-305)
        sb.append(padRight("2024-01-15T10:35:00.00000", 26)); // dalytranProcTs (305-331)
        sb.append(padRight("", 19));                   // FILLER to reach 350 (331-350)
        
        validLine = sb.toString();
        // Ensure exactly 350 characters
        if (validLine.length() < 350) {
            validLine = padRight(validLine, 350);
        } else if (validLine.length() > 350) {
            validLine = validLine.substring(0, 350);
        }
    }

    // Test that fromLine correctly parses a valid fixed-length input
    @Test
    void testFromLineWithValidInput() {
        DailyTranRecord record = DailyTranRecord.fromLine(validLine);

        assertEquals("TXN1234567890123", record.dalytranId.trim());
        assertEquals("CR", record.dalytranTypeCd.trim());
        assertEquals(1234, record.dalytranCatCd);
        assertEquals("ONLINE", record.dalytranSource.trim());
        assertEquals("Purchase at store", record.dalytranDesc.trim());
        assertEquals(123456789L, record.dalytranMerchantId);
        assertEquals("ACME Corporation", record.dalytranMerchantName.trim());
        assertEquals("New York", record.dalytranMerchantCity.trim());
        assertEquals("10001", record.dalytranMerchantZip.trim());
        assertEquals("4111111111111111", record.dalytranCardNum.trim());
        assertNotNull(record.dalytranOrigTs);
        assertNotNull(record.dalytranProcTs);
    }

    // Test that fromLine handles null input gracefully
    @Test
    void testFromLineWithNullInput() {
        DailyTranRecord record = DailyTranRecord.fromLine(null);

        assertNotNull(record);
        assertEquals("", record.dalytranId);
        assertEquals("", record.dalytranTypeCd);
        assertEquals(0, record.dalytranCatCd);
        assertEquals("", record.dalytranSource);
        assertEquals(BigDecimal.ZERO, record.dalytranAmt);
    }

    // Test that fromLine handles empty string input gracefully
    @Test
    void testFromLineWithEmptyInput() {
        DailyTranRecord record = DailyTranRecord.fromLine("");

        assertNotNull(record);
        assertEquals("", record.dalytranId);
        assertEquals("", record.dalytranTypeCd);
        assertEquals(0, record.dalytranCatCd);
    }

    // Test that fromLine handles short input (less than expected length)
    @Test
    void testFromLineWithShortInput() {
        String shortLine = "TXN123";
        DailyTranRecord record = DailyTranRecord.fromLine(shortLine);

        assertNotNull(record);
        // Should still parse what it can
        assertTrue(record.dalytranId.contains("TXN123") || record.dalytranId.length() <= 16);
    }

    // Test default constructor initializes all fields properly
    @Test
    void testDefaultConstructor() {
        DailyTranRecord record = new DailyTranRecord();

        assertEquals("", record.dalytranId);
        assertEquals("", record.dalytranTypeCd);
        assertEquals(0, record.dalytranCatCd);
        assertEquals("", record.dalytranSource);
        assertEquals("", record.dalytranDesc);
        assertEquals(BigDecimal.ZERO, record.dalytranAmt);
        assertEquals(0L, record.dalytranMerchantId);
        assertEquals("", record.dalytranMerchantName);
        assertEquals("", record.dalytranMerchantCity);
        assertEquals("", record.dalytranMerchantZip);
        assertEquals("", record.dalytranCardNum);
        assertEquals("", record.dalytranOrigTs);
        assertEquals("", record.dalytranProcTs);
    }

    // Test RECORD_LENGTH constant is correct
    @Test
    void testRecordLengthConstant() {
        assertEquals(350, DailyTranRecord.RECORD_LENGTH);
    }

    // Test that valid line has correct length
    @Test
    void testValidLineLength() {
        assertEquals(350, validLine.length());
    }

    // Test fromLine parses numeric fields correctly
    @Test
    void testFromLineNumericParsing() {
        DailyTranRecord record = DailyTranRecord.fromLine(validLine);

        assertEquals(1234, record.dalytranCatCd);
        assertEquals(123456789L, record.dalytranMerchantId);
        assertNotNull(record.dalytranAmt);
    }

    // Test fromLine with line containing all spaces
    @Test
    void testFromLineWithAllSpaces() {
        String spaceLine = " ".repeat(350);
        DailyTranRecord record = DailyTranRecord.fromLine(spaceLine);

        assertNotNull(record);
        assertEquals("", record.dalytranId.trim());
        assertEquals(0, record.dalytranCatCd);
        assertEquals(0L, record.dalytranMerchantId);
    }

    // Test fromLine with line containing zeros for numeric fields
    @Test
    void testFromLineWithZeroNumericFields() {
        StringBuilder sb = new StringBuilder();
        sb.append(padRight("TXNZERO", 16));
        sb.append(padRight("DB", 2));
        sb.append("0000");  // dalytranCatCd = 0
        sb.append(padRight("SOURCE", 10));
        sb.append(padRight("Description", 100));
        sb.append("000000000000");  // dalytranAmt = 0
        sb.append("000000000");  // dalytranMerchantId = 0
        sb.append(padRight("Merchant", 50));
        sb.append(padRight("City", 50));
        sb.append(padRight("12345", 10));
        sb.append(padRight("1234567890123456", 16));
        sb.append(padRight("2024-01-01T00:00:00.00000", 26));
        sb.append(padRight("2024-01-01T00:00:00.00000", 26));
        sb.append(padRight("", 19));

        String zeroLine = padRight(sb.toString(), 350);
        if (zeroLine.length() > 350) {
            zeroLine = zeroLine.substring(0, 350);
        }

        DailyTranRecord record = DailyTranRecord.fromLine(zeroLine);

        assertEquals(0, record.dalytranCatCd);
        assertEquals(0L, record.dalytranMerchantId);
    }

    // Helper method to pad string on right with spaces
    private String padRight(String s, int length) {
        if (s == null) s = "";
        if (s.length() >= length) return s.substring(0, length);
        StringBuilder sb = new StringBuilder(s);
        while (sb.length() < length) {
            sb.append(' ');
        }
        return sb.toString();
    }

    // Helper method to pad string on left with specified character
    private String padLeft(String s, int length, char padChar) {
        if (s == null) s = "";
        if (s.length() >= length) return s.substring(0, length);
        StringBuilder sb = new StringBuilder();
        while (sb.length() < length - s.length()) {
            sb.append(padChar);
        }
        sb.append(s);
        return sb.toString();
    }
}