// Generated by CardDemo Agentic Converter on 2026-03-21 16:03:53
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class DateConversionRecordTest {

    private DateConversionRecord record;

    @BeforeEach
    void setUp() {
        record = new DateConversionRecord();
    }

    // Test that fromLine correctly parses a valid fixed-length input string
    @Test
    void testFromLineWithValidInput() {
        // Create a valid 80-character input line
        // Format: type(1) + inpDate(20) + outType(1) + outDate(20) + errorMsg(38) = 80
        String inputLine = "1" +                    // type
                          "20231215            " +  // inpDate (20 chars)
                          "1" +                     // outType
                          "2023-12-15          " +  // outDate (20 chars)
                          "                                      "; // errorMsg (38 chars)
        
        DateConversionRecord result = DateConversionRecord.fromLine(inputLine);
        
        assertNotNull(result);
        assertEquals("1", result.codatecnType);
        assertEquals("20231215            ", result.codatecnInpDate);
        // Test YYYYMMDD redefine parsing
        assertEquals("2023", result.codatecn1Yyyy);
        assertEquals("12", result.codatecn1Mm);
        assertEquals("15", result.codatecn1Dd);
    }

    // Test that fromLine handles null input gracefully
    @Test
    void testFromLineWithNullInput() {
        DateConversionRecord result = DateConversionRecord.fromLine(null);
        
        assertNotNull(result);
        assertEquals("", result.codatecnType);
        assertEquals("", result.codatecnInpDate);
    }

    // Test that fromLine handles empty string input gracefully
    @Test
    void testFromLineWithEmptyInput() {
        DateConversionRecord result = DateConversionRecord.fromLine("");
        
        assertNotNull(result);
        assertEquals("", result.codatecnType);
        assertEquals("", result.codatecnInpDate);
    }

    // Test that fromLine handles short input string gracefully
    @Test
    void testFromLineWithShortInput() {
        String shortInput = "1202312";
        
        DateConversionRecord result = DateConversionRecord.fromLine(shortInput);
        
        assertNotNull(result);
        assertEquals("1", result.codatecnType);
        // Should handle partial data without throwing exception
        assertNotNull(result.codatecn1Yyyy);
    }

    // Test the RECORD_LENGTH constant is correct
    @Test
    void testRecordLengthConstant() {
        // Verify the record length matches expected: 1 + 20 + 1 + 20 + 38 = 80
        assertEquals(80, DateConversionRecord.RECORD_LENGTH);
    }

    // Test the 88-level constants for input type
    @Test
    void testInputTypeConstants() {
        assertEquals("1", DateConversionRecord.YYYYMMDD_IN);
        assertEquals("2", DateConversionRecord.YYYY_MM_DD_IN);
    }

    // Test the 88-level constants for output type
    @Test
    void testOutputTypeConstants() {
        assertEquals("1", DateConversionRecord.YYYY_MM_DD_OP);
        assertEquals("2", DateConversionRecord.YYYYMMDD_OP);
    }

    // Test YYYYMMDD format parsing (type 1)
    @Test
    void testYYYYMMDDFormatParsing() {
        String inputLine = "1" +                    // type = YYYYMMDD_IN
                          "20231225            " +  // inpDate in YYYYMMDD format
                          "1" +                     // outType
                          "                    " +  // outDate (20 chars)
                          "                                      "; // errorMsg (38 chars)
        
        DateConversionRecord result = DateConversionRecord.fromLine(inputLine);
        
        assertEquals(DateConversionRecord.YYYYMMDD_IN, result.codatecnType);
        assertEquals("2023", result.codatecn1Yyyy);
        assertEquals("12", result.codatecn1Mm);
        assertEquals("25", result.codatecn1Dd);
    }

    // Test YYYY-MM-DD format parsing (type 2)
    @Test
    void testYYYY_MM_DDFormatParsing() {
        String inputLine = "2" +                    // type = YYYY_MM_DD_IN
                          "2023-12-25          " +  // inpDate in YYYY-MM-DD format
                          "1" +                     // outType
                          "                    " +  // outDate (20 chars)
                          "                                      "; // errorMsg (38 chars)
        
        DateConversionRecord result = DateConversionRecord.fromLine(inputLine);
        
        assertEquals(DateConversionRecord.YYYY_MM_DD_IN, result.codatecnType);
        assertEquals("2023", result.codatecn1OYyyy);
    }

    // Test that default constructor creates valid object with null fields
    @Test
    void testDefaultConstructor() {
        DateConversionRecord newRecord = new DateConversionRecord();
        
        assertNotNull(newRecord);
        assertNull(newRecord.codatecnType);
        assertNull(newRecord.codatecnInpDate);
        assertNull(newRecord.codatecnErrorMsg);
    }

    // Test parsing with exactly RECORD_LENGTH characters
    @Test
    void testFromLineWithExactRecordLength() {
        StringBuilder sb = new StringBuilder();
        sb.append("1");                              // type (1)
        sb.append("20231215            ");           // inpDate (20)
        sb.append("1");                              // outType (1)
        sb.append("2023-12-15          ");           // outDate (20)
        sb.append("No errors                             "); // errorMsg (38)
        
        // Ensure we have exactly 80 characters
        String inputLine = sb.toString();
        while (inputLine.length() < 80) {
            inputLine += " ";
        }
        inputLine = inputLine.substring(0, 80);
        
        assertEquals(80, inputLine.length());
        
        DateConversionRecord result = DateConversionRecord.fromLine(inputLine);
        
        assertNotNull(result);
        assertEquals("1", result.codatecnType);
    }

    // Test field assignment and retrieval
    @Test
    void testFieldAssignment() {
        record.codatecnType = "1";
        record.codatecnInpDate = "20231215";
        record.codatecnOuttype = "2";
        record.codatecn0utDate = "2023-12-15";
        record.codatecnErrorMsg = "Success";
        
        assertEquals("1", record.codatecnType);
        assertEquals("20231215", record.codatecnInpDate);
        assertEquals("2", record.codatecnOuttype);
        assertEquals("2023-12-15", record.codatecn0utDate);
        assertEquals("Success", record.codatecnErrorMsg);
    }
}