// Generated by CardDemo Agentic Converter on 2026-03-21 16:12:06
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class ReportStructuresTest {

    // Tests for ReportNameHeader

    @Test
    // Verifies that fromLine correctly parses a valid fixed-length input string
    void testReportNameHeader_fromLine_validInput() {
        String line = String.format("%-38s%-41s%-12s%-10s    %-10s", 
            "DALYREPT", "Daily Transaction Report", "Date Range: ", "2024-01-01", "2024-01-31");
        
        ReportStructures.ReportNameHeader header = ReportStructures.ReportNameHeader.fromLine(line);
        
        assertEquals("DALYREPT", header.reptShortName.trim());
        assertEquals("Daily Transaction Report", header.reptLongName.trim());
        assertEquals("Date Range:", header.reptDateHeader.trim());
        assertEquals("2024-01-01", header.reptStartDate.trim());
        assertEquals("2024-01-31", header.reptEndDate.trim());
    }

    @Test
    // Verifies that toLine produces output with correct record length
    void testReportNameHeader_toLine_correctLength() {
        ReportStructures.ReportNameHeader header = new ReportStructures.ReportNameHeader();
        header.reptShortName = "TESTREPT";
        header.reptLongName = "Test Report";
        header.reptDateHeader = "Date Range: ";
        header.reptStartDate = "2024-01-01";
        header.reptEndDate = "2024-12-31";
        
        String line = header.toLine();
        
        assertEquals(ReportStructures.ReportNameHeader.RECORD_LENGTH, line.length());
    }

    @Test
    // Verifies roundtrip: fromLine then toLine produces same length output
    void testReportNameHeader_roundtrip() {
        String originalLine = String.format("%-115s", "DALYREPT                                Daily Transaction Report                Date Range: 2024-01-01 to 2024-01-31");
        originalLine = originalLine.substring(0, ReportStructures.ReportNameHeader.RECORD_LENGTH);
        
        ReportStructures.ReportNameHeader header = ReportStructures.ReportNameHeader.fromLine(originalLine);
        String resultLine = header.toLine();
        
        assertEquals(ReportStructures.ReportNameHeader.RECORD_LENGTH, resultLine.length());
    }

    @Test
    // Verifies that key() returns the trimmed short name
    void testReportNameHeader_key_returnsCorrectKey() {
        ReportStructures.ReportNameHeader header = new ReportStructures.ReportNameHeader();
        header.reptShortName = "DALYREPT  ";
        
        String key = header.key();
        
        assertEquals("DALYREPT", key);
    }

    @Test
    // Verifies that fromLine handles null input gracefully
    void testReportNameHeader_fromLine_nullInput() {
        ReportStructures.ReportNameHeader header = ReportStructures.ReportNameHeader.fromLine(null);
        
        assertNotNull(header);
        assertEquals("", header.reptShortName.trim());
    }

    @Test
    // Verifies that fromLine handles empty input gracefully
    void testReportNameHeader_fromLine_emptyInput() {
        ReportStructures.ReportNameHeader header = ReportStructures.ReportNameHeader.fromLine("");
        
        assertNotNull(header);
        assertEquals("", header.reptShortName.trim());
    }

    @Test
    // Verifies that fromLine handles short input gracefully without throwing exception
    void testReportNameHeader_fromLine_shortInput() {
        String shortLine = "TESTREPT";
        
        ReportStructures.ReportNameHeader header = ReportStructures.ReportNameHeader.fromLine(shortLine);
        
        assertNotNull(header);
        assertTrue(header.reptShortName.contains("TESTREPT"));
    }

    @Test
    // Verifies that toString returns a meaningful representation
    void testReportNameHeader_toString() {
        ReportStructures.ReportNameHeader header = new ReportStructures.ReportNameHeader();
        header.reptShortName = "DALYREPT";
        header.reptLongName = "Daily Report";
        header.reptStartDate = "2024-01-01";
        header.reptEndDate = "2024-01-31";
        
        String result = header.toString();
        
        assertTrue(result.contains("DALYREPT"));
        assertTrue(result.contains("Daily Report"));
        assertTrue(result.contains("2024-01-01"));
        assertTrue(result.contains("2024-01-31"));
    }

    @Test
    // Verifies default values are set correctly
    void testReportNameHeader_defaultValues() {
        ReportStructures.ReportNameHeader header = new ReportStructures.ReportNameHeader();
        
        assertEquals("DALYREPT", header.reptShortName);
        assertEquals("Daily Transaction Report", header.reptLongName);
        assertEquals("Date Range: ", header.reptDateHeader);
        assertEquals("", header.reptStartDate);
        assertEquals("", header.reptEndDate);
    }

    // Tests for TransactionDetailReport

    @Test
    // Verifies that TransactionDetailReport has correct record length constant
    void testTransactionDetailReport_recordLength() {
        assertEquals(115, ReportStructures.TransactionDetailReport.RECORD_LENGTH);
    }

    @Test
    // Verifies that TransactionDetailReport can be instantiated with default values
    void testTransactionDetailReport_defaultValues() {
        ReportStructures.TransactionDetailReport report = new ReportStructures.TransactionDetailReport();
        
        assertEquals("", report.tranReportTransId);
        assertEquals("", report.tranReportAccountId);
        assertEquals("", report.tranReportTypeCd);
        assertEquals("", report.tranReportTypeDesc);
        assertEquals(0, report.tranReportCatCd);
        assertEquals("", report.tranReportCatDesc);
        assertEquals("", report.tranReportSource);
        assertEquals("", report.tranReportAmt);
    }

    @Test
    // Verifies that TransactionDetailReport fields can be set and retrieved
    void testTransactionDetailReport_setFields() {
        ReportStructures.TransactionDetailReport report = new ReportStructures.TransactionDetailReport();
        
        report.tranReportTransId = "TXN001";
        report.tranReportAccountId = "ACC001";
        report.tranReportTypeCd = "CR";
        report.tranReportTypeDesc = "Credit";
        report.tranReportCatCd = 5;
        report.tranReportCatDesc = "Deposit";
        report.tranReportSource = "ATM";
        report.tranReportAmt = "1000.00";
        
        assertEquals("TXN001", report.tranReportTransId);
        assertEquals("ACC001", report.tranReportAccountId);
        assertEquals("CR", report.tranReportTypeCd);
        assertEquals("Credit", report.tranReportTypeDesc);
        assertEquals(5, report.tranReportCatCd);
        assertEquals("Deposit", report.tranReportCatDesc);
        assertEquals("ATM", report.tranReportSource);
        assertEquals("1000.00", report.tranReportAmt);
    }

    // Tests for ReportStructures container class

    @Test
    // Verifies that the container class can be instantiated
    void testReportStructures_instantiation() {
        ReportStructures structures = new ReportStructures();
        assertNotNull(structures);
    }

    @Test
    // Verifies that nested classes are accessible from the container
    void testReportStructures_nestedClassAccess() {
        ReportStructures.ReportNameHeader header = new ReportStructures.ReportNameHeader();
        ReportStructures.TransactionDetailReport detail = new ReportStructures.TransactionDetailReport();
        
        assertNotNull(header);
        assertNotNull(detail);
    }
}