// Generated by CardDemo Agentic Converter on 2026-03-21 16:08:39
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class TranTypeRecordTest {

    // Test that fromLine correctly parses a valid fixed-length input
    @Test
    void testFromLineWithValidInput() {
        String line = "01Purchase Transaction                                    FILLER  ";
        TranTypeRecord rec = TranTypeRecord.fromLine(line);
        
        assertEquals("01", rec.tranType);
        assertEquals("Purchase Transaction                              ", rec.tranTypeDesc);
    }

    // Test that fromLine handles exact field boundaries correctly
    @Test
    void testFromLineWithExactFieldBoundaries() {
        String tranType = "AB";
        String tranTypeDesc = String.format("%-50s", "Test Description");
        String filler = "        ";
        String line = tranType + tranTypeDesc + filler;
        
        TranTypeRecord rec = TranTypeRecord.fromLine(line);
        
        assertEquals("AB", rec.tranType);
        assertEquals("Test Description                                  ", rec.tranTypeDesc);
    }

    // Test that fromLine handles null input gracefully
    @Test
    void testFromLineWithNullInput() {
        TranTypeRecord rec = TranTypeRecord.fromLine(null);
        
        assertEquals("", rec.tranType);
        assertEquals("", rec.tranTypeDesc);
    }

    // Test that fromLine handles empty input gracefully
    @Test
    void testFromLineWithEmptyInput() {
        TranTypeRecord rec = TranTypeRecord.fromLine("");
        
        assertEquals("", rec.tranType);
        assertEquals("", rec.tranTypeDesc);
    }

    // Test that fromLine handles short input gracefully
    @Test
    void testFromLineWithShortInput() {
        String line = "XY";
        TranTypeRecord rec = TranTypeRecord.fromLine(line);
        
        assertEquals("XY", rec.tranType);
        assertEquals("", rec.tranTypeDesc);
    }

    // Test that toLine produces correct record length
    @Test
    void testToLineProducesCorrectLength() {
        TranTypeRecord rec = new TranTypeRecord();
        rec.tranType = "01";
        rec.tranTypeDesc = "Test Transaction";
        
        String line = rec.toLine();
        
        assertEquals(TranTypeRecord.RECORD_LENGTH, line.length());
    }

    // Test roundtrip: fromLine then toLine should preserve data and length
    @Test
    void testRoundtripFromLineToLine() {
        String originalLine = String.format("%-60s", "01Refund Transaction Type");
        TranTypeRecord rec = TranTypeRecord.fromLine(originalLine);
        String outputLine = rec.toLine();
        
        assertEquals(TranTypeRecord.RECORD_LENGTH, outputLine.length());
        assertEquals("01", rec.tranType);
    }

    // Test that roundtrip preserves field values
    @Test
    void testRoundtripPreservesFieldValues() {
        TranTypeRecord original = new TranTypeRecord();
        original.tranType = "99";
        original.tranTypeDesc = "Credit Adjustment";
        
        String line = original.toLine();
        TranTypeRecord parsed = TranTypeRecord.fromLine(line);
        
        assertEquals(original.tranType, parsed.tranType.trim());
        assertEquals(original.tranTypeDesc, parsed.tranTypeDesc.trim());
    }

    // Test that key() returns the transaction type
    @Test
    void testKeyReturnsTransactionType() {
        TranTypeRecord rec = new TranTypeRecord();
        rec.tranType = "05";
        rec.tranTypeDesc = "Some Description";
        
        assertEquals("05", rec.key());
    }

    // Test that key() handles null tranType
    @Test
    void testKeyWithNullTranType() {
        TranTypeRecord rec = new TranTypeRecord();
        rec.tranType = null;
        
        assertEquals("", rec.key());
    }

    // Test that toLine handles null field values
    @Test
    void testToLineWithNullFields() {
        TranTypeRecord rec = new TranTypeRecord();
        rec.tranType = null;
        rec.tranTypeDesc = null;
        
        String line = rec.toLine();
        
        assertEquals(TranTypeRecord.RECORD_LENGTH, line.length());
    }

    // Test toString method for debugging output
    @Test
    void testToStringMethod() {
        TranTypeRecord rec = new TranTypeRecord();
        rec.tranType = "AA";
        rec.tranTypeDesc = "Test";
        
        String result = rec.toString();
        
        assertTrue(result.contains("tranType='AA'"));
        assertTrue(result.contains("tranTypeDesc='Test'"));
        assertTrue(result.startsWith("TranTypeRecord{"));
    }

    // Test that RECORD_LENGTH constant is correct
    @Test
    void testRecordLengthConstant() {
        assertEquals(60, TranTypeRecord.RECORD_LENGTH);
    }

    // Test fromLine with partial tranTypeDesc
    @Test
    void testFromLineWithPartialDescription() {
        String line = "XXShort";
        TranTypeRecord rec = TranTypeRecord.fromLine(line);
        
        assertEquals("XX", rec.tranType);
        assertEquals("Short", rec.tranTypeDesc);
    }

    // Test that toLine pads fields correctly
    @Test
    void testToLinePadsFieldsCorrectly() {
        TranTypeRecord rec = new TranTypeRecord();
        rec.tranType = "A";
        rec.tranTypeDesc = "B";
        
        String line = rec.toLine();
        
        assertEquals(TranTypeRecord.RECORD_LENGTH, line.length());
        assertTrue(line.startsWith("A "));
    }

    // Test toLine truncates long values
    @Test
    void testToLineTruncatesLongValues() {
        TranTypeRecord rec = new TranTypeRecord();
        rec.tranType = "ABCD";
        rec.tranTypeDesc = "This is a very long description that exceeds the fifty character limit for this field";
        
        String line = rec.toLine();
        
        assertEquals(TranTypeRecord.RECORD_LENGTH, line.length());
        assertEquals("AB", line.substring(0, 2));
    }
}