// Generated by CardDemo Agentic Converter on 2026-03-21 16:08:05
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;

class TranCatBalRecordTest {

    private TranCatBalRecord record;

    @BeforeEach
    void setUp() {
        record = new TranCatBalRecord();
    }

    // Test that default constructor initializes fields with default values
    @Test
    void testDefaultConstructorInitializesFieldsCorrectly() {
        assertEquals(0L, record.trancatAcctId);
        assertEquals("", record.trancatTypeCd);
        assertEquals(0, record.trancatCd);
        assertEquals(BigDecimal.ZERO, record.tranCatBal);
    }

    // Test fromLine() correctly parses a valid fixed-length input
    @Test
    void testFromLineWithValidInput() {
        // Build a valid 50-character line
        // trancatAcctId: 12345678901 (11 chars)
        // trancatTypeCd: AB (2 chars)
        // trancatCd: 1234 (4 chars)
        // tranCatBal: +00000123456 (12 chars, represents 1234.56)
        // FILLER: 22 spaces
        String line = "12345678901AB1234+00000123456                      ";
        
        TranCatBalRecord rec = TranCatBalRecord.fromLine(line);
        
        assertEquals(12345678901L, rec.trancatAcctId);
        assertEquals("AB", rec.trancatTypeCd);
        assertEquals(1234, rec.trancatCd);
        assertEquals(new BigDecimal("1234.56"), rec.tranCatBal);
    }

    // Test fromLine() with negative balance value
    @Test
    void testFromLineWithNegativeBalance() {
        String line = "00000000001XY0001-00000098765                      ";
        
        TranCatBalRecord rec = TranCatBalRecord.fromLine(line);
        
        assertEquals(1L, rec.trancatAcctId);
        assertEquals("XY", rec.trancatTypeCd);
        assertEquals(1, rec.trancatCd);
        assertEquals(new BigDecimal("-987.65"), rec.tranCatBal);
    }

    // Test fromLine() with null input returns record with default/empty values
    @Test
    void testFromLineWithNullInput() {
        TranCatBalRecord rec = TranCatBalRecord.fromLine(null);
        
        assertNotNull(rec);
        assertEquals(0L, rec.trancatAcctId);
        assertEquals("  ", rec.trancatTypeCd);
        assertEquals(0, rec.trancatCd);
    }

    // Test fromLine() with empty string input pads and returns record
    @Test
    void testFromLineWithEmptyInput() {
        TranCatBalRecord rec = TranCatBalRecord.fromLine("");
        
        assertNotNull(rec);
        assertEquals(0L, rec.trancatAcctId);
    }

    // Test fromLine() with short input pads correctly
    @Test
    void testFromLineWithShortInput() {
        String shortLine = "12345678901AB";
        
        TranCatBalRecord rec = TranCatBalRecord.fromLine(shortLine);
        
        assertEquals(12345678901L, rec.trancatAcctId);
        assertEquals("AB", rec.trancatTypeCd);
    }

    // Test toLine() produces correct length output
    @Test
    void testToLineProducesCorrectLength() {
        record.trancatAcctId = 12345678901L;
        record.trancatTypeCd = "AB";
        record.trancatCd = 1234;
        record.tranCatBal = new BigDecimal("1234.56");
        
        String line = record.toLine();
        
        assertEquals(TranCatBalRecord.RECORD_LENGTH, line.length());
    }

    // Test roundtrip: fromLine then toLine produces same length
    @Test
    void testRoundtripFromLineToLinePreservesLength() {
        String originalLine = "12345678901AB1234+00000123456                      ";
        
        TranCatBalRecord rec = TranCatBalRecord.fromLine(originalLine);
        String resultLine = rec.toLine();
        
        assertEquals(TranCatBalRecord.RECORD_LENGTH, resultLine.length());
    }

    // Test roundtrip preserves key fields
    @Test
    void testRoundtripPreservesKeyFields() {
        String originalLine = "12345678901AB1234+00000123456                      ";
        
        TranCatBalRecord rec = TranCatBalRecord.fromLine(originalLine);
        String resultLine = rec.toLine();
        TranCatBalRecord rec2 = TranCatBalRecord.fromLine(resultLine);
        
        assertEquals(rec.trancatAcctId, rec2.trancatAcctId);
        assertEquals(rec.trancatTypeCd, rec2.trancatTypeCd);
        assertEquals(rec.trancatCd, rec2.trancatCd);
    }

    // Test key() returns correctly formatted key string
    @Test
    void testKeyReturnsCorrectKey() {
        record.trancatAcctId = 12345678901L;
        record.trancatTypeCd = "AB";
        record.trancatCd = 1234;
        
        String key = record.key();
        
        assertEquals("12345678901AB1234", key);
    }

    // Test key() with small account id pads with zeros
    @Test
    void testKeyPadsAccountIdWithZeros() {
        record.trancatAcctId = 1L;
        record.trancatTypeCd = "XY";
        record.trancatCd = 5;
        
        String key = record.key();
        
        assertEquals("00000000001XY0005", key);
    }

    // Test key() with null type code handles gracefully
    @Test
    void testKeyWithNullTypeCd() {
        record.trancatAcctId = 123L;
        record.trancatTypeCd = null;
        record.trancatCd = 99;
        
        String key = record.key();
        
        assertNotNull(key);
        assertEquals(17, key.length());
    }

    // Test toLine() with negative balance
    @Test
    void testToLineWithNegativeBalance() {
        record.trancatAcctId = 1L;
        record.trancatTypeCd = "AB";
        record.trancatCd = 1;
        record.tranCatBal = new BigDecimal("-500.25");
        
        String line = record.toLine();
        
        assertEquals(TranCatBalRecord.RECORD_LENGTH, line.length());
        assertTrue(line.contains("-00000050025"));
    }

    // Test toLine() with zero balance
    @Test
    void testToLineWithZeroBalance() {
        record.trancatAcctId = 99999999999L;
        record.trancatTypeCd = "ZZ";
        record.trancatCd = 9999;
        record.tranCatBal = BigDecimal.ZERO;
        
        String line = record.toLine();
        
        assertEquals(TranCatBalRecord.RECORD_LENGTH, line.length());
        assertTrue(line.contains("+00000000000"));
    }

    // Test toLine() with null balance uses default
    @Test
    void testToLineWithNullBalance() {
        record.trancatAcctId = 1L;
        record.trancatTypeCd = "AB";
        record.trancatCd = 1;
        record.tranCatBal = null;
        
        String line = record.toLine();
        
        assertEquals(TranCatBalRecord.RECORD_LENGTH, line.length());
    }

    // Test RECORD_LENGTH constant is correct
    @Test
    void testRecordLengthConstant() {
        assertEquals(50, TranCatBalRecord.RECORD_LENGTH);
    }

    // Test fromLine with maximum values
    @Test
    void testFromLineWithMaximumValues() {
        // Max account id: 99999999999, type: XX, code: 9999, bal: 999999999.99
        String line = "99999999999XX9999+99999999999                      ";
        
        TranCatBalRecord rec = TranCatBalRecord.fromLine(line);
        
        assertEquals(99999999999L, rec.trancatAcctId);
        assertEquals("XX", rec.trancatTypeCd);
        assertEquals(9999, rec.trancatCd);
    }

    // Test type code truncation in toLine when longer than 2 chars
    @Test
    void testToLineTruncatesLongTypeCd() {
        record.trancatAcctId = 1L;
        record.trancatTypeCd = "ABCD";
        record.trancatCd = 1;
        record.tranCatBal = BigDecimal.ZERO;
        
        String line = record.toLine();
        
        assertEquals(TranCatBalRecord.RECORD_LENGTH, line.length());
        assertEquals("AB", line.substring(11, 13));
    }
}