// Generated by CardDemo Agentic Converter on 2026-03-21 16:10:12
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;

class TranRecordTest {

    private TranRecord record;

    @BeforeEach
    void setUp() {
        record = new TranRecord();
    }

    // Test that default constructor initializes all fields to default values
    @Test
    void testDefaultConstructorInitializesFields() {
        assertEquals("", record.tranId);
        assertEquals("", record.tranTypeCd);
        assertEquals(0, record.tranCatCd);
        assertEquals("", record.tranSource);
        assertEquals("", record.tranDesc);
        assertEquals(BigDecimal.ZERO, record.tranAmt);
        assertEquals(0L, record.tranMerchantId);
        assertEquals("", record.tranMerchantName);
        assertEquals("", record.tranMerchantCity);
        assertEquals("", record.tranMerchantZip);
        assertEquals("", record.tranCardNum);
        assertEquals("", record.tranOrigTs);
        assertEquals("", record.tranProcTs);
    }

    // Test that RECORD_LENGTH constant is correctly set
    @Test
    void testRecordLengthConstant() {
        assertEquals(350, TranRecord.RECORD_LENGTH);
    }

    // Test fromLine with valid fixed-length input parses fields correctly
    @Test
    void testFromLineWithValidInput() {
        // Build a 350-character fixed-length record
        StringBuilder sb = new StringBuilder();
        sb.append("TRN1234567890123");  // tranId: 16 chars
        sb.append("SA");                 // tranTypeCd: 2 chars
        sb.append("1234");               // tranCatCd: 4 chars
        sb.append("ONLINE    ");         // tranSource: 10 chars
        sb.append(padRight("Purchase at store", 100)); // tranDesc: 100 chars
        sb.append("+000012345678");      // tranAmt: 12 chars (S9(09)V99)
        sb.append("123456789");          // tranMerchantId: 9 chars
        sb.append(padRight("ACME Corporation", 50)); // tranMerchantName: 50 chars
        sb.append(padRight("New York", 50)); // tranMerchantCity: 50 chars
        sb.append("10001     ");         // tranMerchantZip: 10 chars
        sb.append("4111111111111111");   // tranCardNum: 16 chars
        sb.append("2024-01-15T10:30:00.000Z  "); // tranOrigTs: 26 chars
        sb.append("2024-01-15T10:31:00.000Z  "); // tranProcTs: 26 chars
        sb.append(padRight("", 20));     // FILLER: 20 chars
        
        String line = sb.toString();
        // Ensure line is exactly 350 characters
        if (line.length() < 350) {
            line = padRight(line, 350);
        } else if (line.length() > 350) {
            line = line.substring(0, 350);
        }
        
        TranRecord result = TranRecord.fromLine(line);
        
        assertNotNull(result);
        assertEquals("TRN1234567890123", result.tranId);
        assertEquals("SA", result.tranTypeCd);
    }

    // Test fromLine with null input handles gracefully
    @Test
    void testFromLineWithNullInput() {
        TranRecord result = TranRecord.fromLine(null);
        assertNotNull(result);
        assertEquals("", result.tranId);
        assertEquals("", result.tranTypeCd);
    }

    // Test fromLine with empty string input handles gracefully
    @Test
    void testFromLineWithEmptyInput() {
        TranRecord result = TranRecord.fromLine("");
        assertNotNull(result);
        assertEquals("", result.tranId);
        assertEquals("", result.tranTypeCd);
    }

    // Test fromLine with short input (less than record length) handles gracefully
    @Test
    void testFromLineWithShortInput() {
        String shortLine = "TRN123";
        TranRecord result = TranRecord.fromLine(shortLine);
        assertNotNull(result);
        // Should extract what it can from the short input
        assertTrue(result.tranId.startsWith("TRN123"));
    }

    // Test that fields can be set and retrieved
    @Test
    void testFieldAssignment() {
        record.tranId = "TEST1234567890AB";
        record.tranTypeCd = "CR";
        record.tranCatCd = 9999;
        record.tranSource = "MOBILE";
        record.tranDesc = "Test transaction description";
        record.tranAmt = new BigDecimal("12345.67");
        record.tranMerchantId = 987654321L;
        record.tranMerchantName = "Test Merchant";
        record.tranMerchantCity = "Test City";
        record.tranMerchantZip = "12345";
        record.tranCardNum = "1234567890123456";
        record.tranOrigTs = "2024-01-01T00:00:00.000Z";
        record.tranProcTs = "2024-01-01T00:01:00.000Z";
        
        assertEquals("TEST1234567890AB", record.tranId);
        assertEquals("CR", record.tranTypeCd);
        assertEquals(9999, record.tranCatCd);
        assertEquals("MOBILE", record.tranSource);
        assertEquals("Test transaction description", record.tranDesc);
        assertEquals(new BigDecimal("12345.67"), record.tranAmt);
        assertEquals(987654321L, record.tranMerchantId);
        assertEquals("Test Merchant", record.tranMerchantName);
        assertEquals("Test City", record.tranMerchantCity);
        assertEquals("12345", record.tranMerchantZip);
        assertEquals("1234567890123456", record.tranCardNum);
        assertEquals("2024-01-01T00:00:00.000Z", record.tranOrigTs);
        assertEquals("2024-01-01T00:01:00.000Z", record.tranProcTs);
    }

    // Test that tranId can serve as a key identifier
    @Test
    void testTranIdAsKey() {
        record.tranId = "UNIQUE_KEY_12345";
        assertNotNull(record.tranId);
        assertEquals(16, record.tranId.length());
    }

    // Test BigDecimal tranAmt handles decimal precision
    @Test
    void testTranAmtDecimalPrecision() {
        record.tranAmt = new BigDecimal("123456789.99");
        assertEquals(new BigDecimal("123456789.99"), record.tranAmt);
        assertEquals(2, record.tranAmt.scale());
    }

    // Test tranMerchantId handles large values
    @Test
    void testTranMerchantIdLargeValue() {
        record.tranMerchantId = 999999999L;
        assertEquals(999999999L, record.tranMerchantId);
    }

    // Test tranCatCd handles maximum 4-digit value
    @Test
    void testTranCatCdMaxValue() {
        record.tranCatCd = 9999;
        assertEquals(9999, record.tranCatCd);
    }

    // Helper method to pad string to specified length
    private String padRight(String str, int length) {
        if (str == null) str = "";
        if (str.length() >= length) return str.substring(0, length);
        StringBuilder sb = new StringBuilder(str);
        while (sb.length() < length) {
            sb.append(' ');
        }
        return sb.toString();
    }
}