// Generated by CardDemo Agentic Converter on 2026-03-21 16:09:18
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class TranCatRecordTest {

    // Test that fromLine correctly parses a valid fixed-length input
    @Test
    void testFromLineWithValidInput() {
        String line = "PR0001Grocery Purchase                                    XXXX";
        TranCatRecord rec = TranCatRecord.fromLine(line);
        
        assertEquals("PR", rec.tranTypeCd);
        assertEquals(1, rec.tranCatCd);
        assertEquals("Grocery Purchase", rec.tranCatTypeDesc.trim());
    }

    // Test that fromLine handles exact 60-byte record correctly
    @Test
    void testFromLineWithExactRecordLength() {
        String tranTypeCd = "SA";
        String tranCatCd = "0025";
        String tranCatTypeDesc = String.format("%-50s", "Salary Deposit");
        String filler = "    ";
        String line = tranTypeCd + tranCatCd + tranCatTypeDesc + filler;
        
        assertEquals(60, line.length());
        
        TranCatRecord rec = TranCatRecord.fromLine(line);
        
        assertEquals("SA", rec.tranTypeCd);
        assertEquals(25, rec.tranCatCd);
        assertEquals("Salary Deposit", rec.tranCatTypeDesc.trim());
    }

    // Test that toLine produces a record of correct length
    @Test
    void testToLineProducesCorrectLength() {
        TranCatRecord rec = new TranCatRecord();
        rec.tranTypeCd = "WD";
        rec.tranCatCd = 99;
        rec.tranCatTypeDesc = "ATM Withdrawal";
        
        String line = rec.toLine();
        
        assertEquals(TranCatRecord.RECORD_LENGTH, line.length());
    }

    // Test roundtrip: fromLine then toLine should produce same length record
    @Test
    void testRoundtripFromLineToLine() {
        String originalLine = "CR0010Cash Refund                                         FILL";
        TranCatRecord rec = TranCatRecord.fromLine(originalLine);
        String outputLine = rec.toLine();
        
        assertEquals(TranCatRecord.RECORD_LENGTH, outputLine.length());
        assertEquals("CR", outputLine.substring(0, 2));
        assertEquals("0010", outputLine.substring(2, 6));
    }

    // Test that key() returns correct composite key
    @Test
    void testKeyReturnsCorrectCompositeKey() {
        TranCatRecord rec = new TranCatRecord();
        rec.tranTypeCd = "DB";
        rec.tranCatCd = 123;
        rec.tranCatTypeDesc = "Debit Transaction";
        
        String key = rec.key();
        
        assertEquals("DB0123", key);
    }

    // Test key() with single digit category code (should be zero-padded)
    @Test
    void testKeyWithZeroPaddedCategoryCode() {
        TranCatRecord rec = new TranCatRecord();
        rec.tranTypeCd = "TX";
        rec.tranCatCd = 5;
        rec.tranCatTypeDesc = "Tax Payment";
        
        String key = rec.key();
        
        assertEquals("TX0005", key);
    }

    // Test fromLine handles null input gracefully
    @Test
    void testFromLineWithNullInput() {
        TranCatRecord rec = TranCatRecord.fromLine(null);
        
        assertNotNull(rec);
        assertEquals("", rec.tranTypeCd);
        assertEquals(0, rec.tranCatCd);
        assertEquals("", rec.tranCatTypeDesc);
    }

    // Test fromLine handles empty string input gracefully
    @Test
    void testFromLineWithEmptyInput() {
        TranCatRecord rec = TranCatRecord.fromLine("");
        
        assertNotNull(rec);
        assertEquals("", rec.tranTypeCd);
        assertEquals(0, rec.tranCatCd);
        assertEquals("", rec.tranCatTypeDesc);
    }

    // Test fromLine handles short input gracefully
    @Test
    void testFromLineWithShortInput() {
        TranCatRecord rec = TranCatRecord.fromLine("AB");
        
        assertNotNull(rec);
        assertEquals("AB", rec.tranTypeCd);
        assertEquals(0, rec.tranCatCd);
        assertEquals("", rec.tranCatTypeDesc);
    }

    // Test default constructor initializes fields correctly
    @Test
    void testDefaultConstructor() {
        TranCatRecord rec = new TranCatRecord();
        
        assertEquals("", rec.tranTypeCd);
        assertEquals(0, rec.tranCatCd);
        assertEquals("", rec.tranCatTypeDesc);
    }

    // Test toLine with default/empty values
    @Test
    void testToLineWithDefaultValues() {
        TranCatRecord rec = new TranCatRecord();
        String line = rec.toLine();
        
        assertEquals(TranCatRecord.RECORD_LENGTH, line.length());
        assertEquals("  ", line.substring(0, 2));
        assertEquals("0000", line.substring(2, 6));
    }

    // Test toLine truncates long description
    @Test
    void testToLineTruncatesLongDescription() {
        TranCatRecord rec = new TranCatRecord();
        rec.tranTypeCd = "LG";
        rec.tranCatCd = 999;
        rec.tranCatTypeDesc = "This is a very long transaction category description that exceeds fifty characters";
        
        String line = rec.toLine();
        
        assertEquals(TranCatRecord.RECORD_LENGTH, line.length());
        assertEquals("This is a very long transaction category descripti", line.substring(6, 56));
    }

    // Test toString method produces expected format
    @Test
    void testToStringFormat() {
        TranCatRecord rec = new TranCatRecord();
        rec.tranTypeCd = "FE";
        rec.tranCatCd = 42;
        rec.tranCatTypeDesc = "Service Fee";
        
        String str = rec.toString();
        
        assertTrue(str.contains("TranCatRecord{"));
        assertTrue(str.contains("tranTypeCd='FE'"));
        assertTrue(str.contains("tranCatCd=42"));
        assertTrue(str.contains("tranCatTypeDesc='Service Fee'"));
    }

    // Test fromLine with non-numeric category code defaults to zero
    @Test
    void testFromLineWithNonNumericCategoryCode() {
        String line = "ABxxxx" + String.format("%-50s", "Test Description") + "    ";
        TranCatRecord rec = TranCatRecord.fromLine(line);
        
        assertEquals("AB", rec.tranTypeCd);
        assertEquals(0, rec.tranCatCd);
        assertEquals("Test Description", rec.tranCatTypeDesc.trim());
    }

    // Test RECORD_LENGTH constant
    @Test
    void testRecordLengthConstant() {
        assertEquals(60, TranCatRecord.RECORD_LENGTH);
    }

    // Test key with null tranTypeCd handled via nvl
    @Test
    void testKeyHandlesNullTranTypeCd() {
        TranCatRecord rec = new TranCatRecord();
        rec.tranTypeCd = null;
        rec.tranCatCd = 100;
        
        // This should not throw NPE due to nvl handling
        assertDoesNotThrow(() -> rec.key());
    }
}