// Generated by CardDemo Agentic Converter on 2026-03-21 18:40:04
// Source: AWS CardDemo (Apache 2.0)

/**
 * Java service class converted from COBOL program CBACT01C.cbl
 * Application: CardDemo
 * Type: Batch Program
 * Function: Read the account file and write into multiple output files
 * 
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 * Licensed under the Apache License, Version 2.0
 */

import java.io.*;
import java.math.BigDecimal;
import java.nio.file.*;
import java.util.*;
import java.util.logging.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class CbAct01Service {

    private static final Logger logger = Logger.getLogger(CbAct01Service.class.getName());

    // File paths from environment variables (JCL DD name mapping)
    private final String acctFilePath;
    private final String outFilePath;
    private final String arryFilePath;
    private final String vbrcFilePath;

    // File handlers
    private BufferedReader acctFileReader;
    private BufferedWriter outFileWriter;
    private BufferedWriter arryFileWriter;
    private BufferedWriter vbrcFileWriter;

    // File status variables
    private String acctFileStatus = "00";
    private String outFileStatus = "00";
    private String arryFileStatus = "00";
    private String vbrcFileStatus = "00";

    // Working storage variables
    private int applResult = 0;
    private boolean endOfFile = false;
    private AccountRecord accountRecord;

    // Output record structures
    private OutAcctRec outAcctRec;
    private ArrArrayRec arrArrayRec;
    private VbrcRec1 vbrcRec1;
    private VbrcRec2 vbrcRec2;

    // Date conversion working fields
    private String wsReissueDate;
    private String wsAcctReissueYyyy;

    /**
     * Constructor - initializes file paths from environment variables
     */
    public CbAct01Service() {
        this.acctFilePath = getEnv("ACCTFILE", "data/ACCTFILE.dat");
        this.outFilePath = getEnv("OUTFILE", "data/OUTFILE.dat");
        this.arryFilePath = getEnv("ARRYFILE", "data/ARRYFILE.dat");
        this.vbrcFilePath = getEnv("VBRCFILE", "data/VBRCFILE.dat");
    }

    /**
     * Main execution method - maps to PROCEDURE DIVISION
     */
    public void execute() {
        logger.info("START OF EXECUTION OF PROGRAM CBACT01C");

        // Perform file opens - maps to 0000-ACCTFILE-OPEN, 2000-OUTFILE-OPEN, etc.
        openAcctFile();
        openOutFile();
        openArrFile();
        openVbrFile();

        // Main processing loop - maps to PERFORM UNTIL END-OF-FILE = 'Y'
        while (!endOfFile) {
            if (!endOfFile) {
                getNextAcctRecord();
                if (!endOfFile) {
                    logger.info(accountRecord.toString());
                }
            }
        }

        // Close files - maps to 9000-ACCTFILE-CLOSE
        closeAcctFile();
        closeOutFile();
        closeArrFile();
        closeVbrFile();

        logger.info("END OF EXECUTION OF PROGRAM CBACT01C");
    }

    /**
     * 1000-ACCTFILE-GET-NEXT - Read next record from account file
     */
    private void getNextAcctRecord() {
        try {
            String line = acctFileReader.readLine();
            if (line != null) {
                accountRecord = AccountRecord.fromLine(line);
                acctFileStatus = "00";
                applResult = 0;

                // Initialize array record
                arrArrayRec = new ArrArrayRec();

                // Process record - maps to various PERFORM statements
                displayAcctRecord();
                populAcctRecord();
                writeAcctRecord();
                populArrayRecord();
                writeArryRecord();

                // Initialize and process VBR records
                vbrcRec1 = new VbrcRec1();
                vbrcRec2 = new VbrcRec2();
                populVbrcRecord();
                writeVb1Record();
                writeVb2Record();
            } else {
                acctFileStatus = "10";
                applResult = 16;
            }
        } catch (IOException e) {
            acctFileStatus = "12";
            applResult = 12;
        }

        if (applResult == 0) {
            // Continue processing
        } else if (applResult == 16) {
            endOfFile = true;
        } else {
            logger.severe("ERROR READING ACCOUNT FILE");
            displayIoStatus(acctFileStatus);
            abendProgram();
        }
    }

    /**
     * 1100-DISPLAY-ACCT-RECORD - Display account record fields
     */
    private void displayAcctRecord() {
        logger.info("ACCT-ID                 :" + accountRecord.acctId);
        logger.info("ACCT-ACTIVE-STATUS      :" + accountRecord.acctActiveStatus);
        logger.info("ACCT-CURR-BAL           :" + accountRecord.acctCurrBal);
        logger.info("ACCT-CREDIT-LIMIT       :" + accountRecord.acctCreditLimit);
        logger.info("ACCT-CASH-CREDIT-LIMIT  :" + accountRecord.acctCashCreditLimit);
        logger.info("ACCT-OPEN-DATE          :" + accountRecord.acctOpenDate);
        logger.info("ACCT-EXPIRAION-DATE     :" + accountRecord.acctExpiraionDate);
        logger.info("ACCT-REISSUE-DATE       :" + accountRecord.acctReissueDate);
        logger.info("ACCT-CURR-CYC-CREDIT    :" + accountRecord.acctCurrCycCredit);
        logger.info("ACCT-CURR-CYC-DEBIT     :" + accountRecord.acctCurrCycDebit);
        logger.info("ACCT-GROUP-ID           :" + accountRecord.acctGroupId);
        logger.info("-------------------------------------------------");
    }

    /**
     * 1300-POPUL-ACCT-RECORD - Populate output account record
     */
    private void populAcctRecord() {
        outAcctRec = new OutAcctRec();
        outAcctRec.outAcctId = accountRecord.acctId;
        outAcctRec.outAcctActiveStatus = accountRecord.acctActiveStatus;
        outAcctRec.outAcctCurrBal = accountRecord.acctCurrBal;
        outAcctRec.outAcctCreditLimit = accountRecord.acctCreditLimit;
        outAcctRec.outAcctCashCreditLimit = accountRecord.acctCashCreditLimit;
        outAcctRec.outAcctOpenDate = accountRecord.acctOpenDate;
        outAcctRec.outAcctExpiraionDate = accountRecord.acctExpiraionDate;

        // Store reissue date for later use
        wsReissueDate = accountRecord.acctReissueDate;
        if (wsReissueDate != null && wsReissueDate.length() >= 4) {
            wsAcctReissueYyyy = wsReissueDate.substring(0, 4);
        } else {
            wsAcctReissueYyyy = "    ";
        }

        // Date conversion - using java.time instead of CALL 'COBDATFT'
        String convertedDate = convertDate(accountRecord.acctReissueDate);
        outAcctRec.outAcctReissueDate = convertedDate;

        outAcctRec.outAcctCurrCycCredit = accountRecord.acctCurrCycCredit;

        // Handle zero debit case
        if (accountRecord.acctCurrCycDebit == null || 
            accountRecord.acctCurrCycDebit.compareTo(BigDecimal.ZERO) == 0) {
            outAcctRec.outAcctCurrCycDebit = new BigDecimal("2525.00");
        } else {
            outAcctRec.outAcctCurrCycDebit = accountRecord.acctCurrCycDebit;
        }

        outAcctRec.outAcctGroupId = accountRecord.acctGroupId;
    }

    /**
     * Date conversion helper - replaces CALL 'COBDATFT'
     * Converts date from one format to another
     */
    private String convertDate(String inputDate) {
        if (inputDate == null || inputDate.trim().isEmpty()) {
            return "          ";
        }
        try {
            String trimmed = inputDate.trim();
            // Try YYYY-MM-DD format first
            if (trimmed.contains("-")) {
                LocalDate date = LocalDate.parse(trimmed, DateTimeFormatter.ISO_LOCAL_DATE);
                return date.format(DateTimeFormatter.ISO_LOCAL_DATE);
            } else if (trimmed.length() == 8) {
                // YYYYMMDD format
                LocalDate date = LocalDate.parse(trimmed, DateTimeFormatter.BASIC_ISO_DATE);
                return date.format(DateTimeFormatter.ISO_LOCAL_DATE);
            }
            return inputDate;
        } catch (Exception e) {
            return inputDate;
        }
    }

    /**
     * 1350-WRITE-ACCT-RECORD - Write output account record
     */
    private void writeAcctRecord() {
        try {
            outFileWriter.write(outAcctRec.toLine());
            outFileWriter.newLine();
            outFileStatus = "00";
        } catch (IOException e) {
            outFileStatus = "12";
        }

        if (!outFileStatus.equals("00") && !outFileStatus.equals("10")) {
            logger.severe("ACCOUNT FILE WRITE STATUS IS:" + outFileStatus);
            displayIoStatus(outFileStatus);
            abendProgram();
        }
    }

    /**
     * 1400-POPUL-ARRAY-RECORD - Populate array record
     */
    private void populArrayRecord() {
        arrArrayRec.arrAcctId = accountRecord.acctId;
        arrArrayRec.arrAcctCurrBal[0] = accountRecord.acctCurrBal;
        arrArrayRec.arrAcctCurrCycDebit[0] = new BigDecimal("1005.00");
        arrArrayRec.arrAcctCurrBal[1] = accountRecord.acctCurrBal;
        arrArrayRec.arrAcctCurrCycDebit[1] = new BigDecimal("1525.00");
        arrArrayRec.arrAcctCurrBal[2] = new BigDecimal("-1025.00");
        arrArrayRec.arrAcctCurrCycDebit[2] = new BigDecimal("-2500.00");
    }

    /**
     * 1450-WRITE-ARRY-RECORD - Write array record
     */
    private void writeArryRecord() {
        try {
            arryFileWriter.write(arrArrayRec.toLine());
            arryFileWriter.newLine();
            arryFileStatus = "00";
        } catch (IOException e) {
            arryFileStatus = "12";
        }

        if (!arryFileStatus.equals("00") && !arryFileStatus.equals("10")) {
            logger.severe("ACCOUNT FILE WRITE STATUS IS:" + arryFileStatus);
            displayIoStatus(arryFileStatus);
            abendProgram();
        }
    }

    /**
     * 1500-POPUL-VBRC-RECORD - Populate variable-length records
     */
    private void populVbrcRecord() {
        vbrcRec1.vb1AcctId = accountRecord.acctId;
        vbrcRec1.vb1AcctActiveStatus = accountRecord.acctActiveStatus;

        vbrcRec2.vb2AcctId = accountRecord.acctId;
        vbrcRec2.vb2AcctCurrBal = accountRecord.acctCurrBal;
        vbrcRec2.vb2AcctCreditLimit = accountRecord.acctCreditLimit;
        vbrcRec2.vb2AcctReissueYyyy = wsAcctReissueYyyy;

        logger.info("VBRC-REC1:" + vbrcRec1.toLine());
        logger.info("VBRC-REC2:" + vbrcRec2.toLine());
    }

    /**
     * 1550-WRITE-VB1-RECORD - Write variable-length record 1
     */
    private void writeVb1Record() {
        try {
            String record = vbrcRec1.toLine();
            vbrcFileWriter.write(record.substring(0, Math.min(12, record.length())));
            vbrcFileWriter.newLine();
            vbrcFileStatus = "00";
        } catch (IOException e) {
            vbrcFileStatus = "12";
        }

        if (!vbrcFileStatus.equals("00") && !vbrcFileStatus.equals("10")) {
            logger.severe("ACCOUNT FILE WRITE STATUS IS:" + vbrcFileStatus);
            displayIoStatus(vbrcFileStatus);
            abendProgram();
        }
    }

    /**
     * 1575-WRITE-VB2-RECORD - Write variable-length record 2
     */
    private void writeVb2Record() {
        try {
            String record = vbrcRec2.toLine();
            vbrcFileWriter.write(record.substring(0, Math.min(39, record.length())));
            vbrcFileWriter.newLine();
            vbrcFileStatus = "00";
        } catch (IOException e) {
            vbrcFileStatus = "12";
        }

        if (!vbrcFileStatus.equals("00") && !vbrcFileStatus.equals("10")) {
            logger.severe("ACCOUNT FILE WRITE STATUS IS:" + vbrcFileStatus);
            displayIoStatus(vbrcFileStatus);
            abendProgram();
        }
    }

    /**
     * 0000-ACCTFILE-OPEN - Open account input file
     */
    private void openAcctFile() {
        applResult = 8;
        try {
            acctFileReader = new BufferedReader(new FileReader(acctFilePath));
            acctFileStatus = "00";
            applResult = 0;
        } catch (FileNotFoundException e) {
            acctFileStatus = "35";
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING ACCTFILE");
            displayIoStatus(acctFileStatus);
            abendProgram();
        }
    }

    /**
     * 2000-OUTFILE-OPEN - Open output file
     */
    private void openOutFile() {
        applResult = 8;
        try {
            outFileWriter = new BufferedWriter(new FileWriter(outFilePath));
            outFileStatus = "00";
            applResult = 0;
        } catch (IOException e) {
            outFileStatus = "35";
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING OUTFILE " + outFileStatus);
            displayIoStatus(outFileStatus);
            abendProgram();
        }
    }

    /**
     * 3000-ARRFILE-OPEN - Open array output file
     */
    private void openArrFile() {
        applResult = 8;
        try {
            arryFileWriter = new BufferedWriter(new FileWriter(arryFilePath));
            arryFileStatus = "00";
            applResult = 0;
        } catch (IOException e) {
            arryFileStatus = "35";
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING ARRAYFILE " + arryFileStatus);
            displayIoStatus(arryFileStatus);
            abendProgram();
        }
    }

    /**
     * 4000-VBRFILE-OPEN - Open variable-length record file
     */
    private void openVbrFile() {
        applResult = 8;
        try {
            vbrcFileWriter = new BufferedWriter(new FileWriter(vbrcFilePath));
            vbrcFileStatus = "00";
            applResult = 0;
        } catch (IOException e) {
            vbrcFileStatus = "35";
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING VBRC FILE " + vbrcFileStatus);
            displayIoStatus(vbrcFileStatus);
            abendProgram();
        }
    }

    /**
     * 9000-ACCTFILE-CLOSE - Close account file
     */
    private void closeAcctFile() {
        applResult = 8;
        try {
            if (acctFileReader != null) {
                acctFileReader.close();
            }
            acctFileStatus = "00";
            applResult = 0;
        } catch (IOException e) {
            acctFileStatus = "99";
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR CLOSING ACCOUNT FILE");
            displayIoStatus(acctFileStatus);
            abendProgram();
        }
    }

    /**
     * Close output file
     */
    private void closeOutFile() {
        try {
            if (outFileWriter != null) {
                outFileWriter.close();
            }
        } catch (IOException e) {
            logger.warning("Error closing output file: " + e.getMessage());
        }
    }

    /**
     * Close array file
     */
    private void closeArrFile() {
        try {
            if (arryFileWriter != null) {
                arryFileWriter.close();
            }
        } catch (IOException e) {
            logger.warning("Error closing array file: " + e.getMessage());
        }
    }

    /**
     * Close VBR file
     */
    private void closeVbrFile() {
        try {
            if (vbrcFileWriter != null) {
                vbrcFileWriter.close();
            }
        } catch (IOException e) {
            logger.warning("Error closing VBR file: " + e.getMessage());
        }
    }

    /**
     * 9910-DISPLAY-IO-STATUS - Display file I/O status
     */
    private void displayIoStatus(String ioStatus) {
        if (ioStatus == null || ioStatus.length() < 2) {
            logger.severe("FILE STATUS IS: NNNN0000");
            return;
        }
        String displayStatus;
        try {
            int statusNum = Integer.parseInt(ioStatus);
            displayStatus = String.format("%04d", statusNum);
        } catch (NumberFormatException e) {
            displayStatus = "00" + ioStatus;
        }
        logger.severe("FILE STATUS IS: NNNN" + displayStatus);
    }

    /**
     * 9999-ABEND-PROGRAM - Abnormal program termination
     * Maps to CALL 'CEE3ABD'
     */
    private void abendProgram() {
        logger.severe("ABENDING PROGRAM");
        throw new RuntimeException("ABEND: Program terminated abnormally with code 999");
    }

    /**
     * Utility method to get environment variable with default value
     */
    private static String getEnv(String key, String def) {
        String v = System.getenv(key);
        return (v != null && !v.isEmpty()) ? v : def;
    }

    /**
     * Main method for standalone execution
     */
    public static void main(String[] args) {
        CbAct01Service service = new CbAct01Service();
        service.execute();
    }

    // =====================================================================
    // Inner classes for record structures not covered by shared copybooks
    // =====================================================================

    /**
     * Output account record structure - maps to OUT-ACCT-REC in COBOL
     */
    private static class OutAcctRec {
        public long outAcctId;                        // PIC 9(11)
        public String outAcctActiveStatus;            // PIC X(01)
        public BigDecimal outAcctCurrBal;             // PIC S9(10)V99
        public BigDecimal outAcctCreditLimit;         // PIC S9(10)V99
        public BigDecimal outAcctCashCreditLimit;     // PIC S9(10)V99
        public String outAcctOpenDate;                // PIC X(10)
        public String outAcctExpiraionDate;           // PIC X(10)
        public String outAcctReissueDate;             // PIC X(10)
        public BigDecimal outAcctCurrCycCredit;       // PIC S9(10)V99
        public BigDecimal outAcctCurrCycDebit;        // PIC S9(10)V99 COMP-3
        public String outAcctGroupId;                 // PIC X(10)

        public OutAcctRec() {
            outAcctId = 0;
            outAcctActiveStatus = " ";
            outAcctCurrBal = BigDecimal.ZERO;
            outAcctCreditLimit = BigDecimal.ZERO;
            outAcctCashCreditLimit = BigDecimal.ZERO;
            outAcctOpenDate = "          ";
            outAcctExpiraionDate = "          ";
            outAcctReissueDate = "          ";
            outAcctCurrCycCredit = BigDecimal.ZERO;
            outAcctCurrCycDebit = BigDecimal.ZERO;
            outAcctGroupId = "          ";
        }

        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%011d", outAcctId));
            sb.append(outAcctActiveStatus != null ? outAcctActiveStatus : " ");
            sb.append(formatDecimal(outAcctCurrBal, 12, 2));
            sb.append(formatDecimal(outAcctCreditLimit, 12, 2));
            sb.append(formatDecimal(outAcctCashCreditLimit, 12, 2));
            sb.append(padRight(outAcctOpenDate, 10));
            sb.append(padRight(outAcctExpiraionDate, 10));
            sb.append(padRight(outAcctReissueDate, 10));
            sb.append(formatDecimal(outAcctCurrCycCredit, 12, 2));
            sb.append(formatDecimal(outAcctCurrCycDebit, 12, 2));
            sb.append(padRight(outAcctGroupId, 10));
            return sb.toString();
        }

        private String formatDecimal(BigDecimal value, int totalDigits, int decimals) {
            if (value == null) value = BigDecimal.ZERO;
            String sign = value.compareTo(BigDecimal.ZERO) < 0 ? "-" : "+";
            BigDecimal absValue = value.abs();
            long intPart = absValue.movePointRight(decimals).longValue();
            return sign + String.format("%0" + (totalDigits - 1) + "d", intPart);
        }

        private String padRight(String s, int len) {
            if (s == null) s = "";
            if (s.length() >= len) return s.substring(0, len);
            return String.format("%-" + len + "s", s);
        }
    }

    /**
     * Array record structure - maps to ARR-ARRAY-REC in COBOL
     */
    private static class ArrArrayRec {
        public long arrAcctId;                        // PIC 9(11)
        public BigDecimal[] arrAcctCurrBal;           // OCCURS 5 TIMES
        public BigDecimal[] arrAcctCurrCycDebit;      // OCCURS 5 TIMES
        public String arrFiller;                      // PIC X(04)

        public ArrArrayRec() {
            arrAcctId = 0;
            arrAcctCurrBal = new BigDecimal[5];
            arrAcctCurrCycDebit = new BigDecimal[5];
            for (int i = 0; i < 5; i++) {
                arrAcctCurrBal[i] = BigDecimal.ZERO;
                arrAcctCurrCycDebit[i] = BigDecimal.ZERO;
            }
            arrFiller = "    ";
        }

        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%011d", arrAcctId));
            for (int i = 0; i < 5; i++) {
                sb.append(formatDecimal(arrAcctCurrBal[i], 12, 2));
                sb.append(formatComp3(arrAcctCurrCycDebit[i]));
            }
            sb.append(arrFiller);
            return sb.toString();
        }

        private String formatDecimal(BigDecimal value, int totalDigits, int decimals) {
            if (value == null) value = BigDecimal.ZERO;
            String sign = value.compareTo(BigDecimal.ZERO) < 0 ? "-" : "+";
            BigDecimal absValue = value.abs();
            long intPart = absValue.movePointRight(decimals).longValue();
            return sign + String.format("%0" + (totalDigits - 1) + "d", intPart);
        }

        private String formatComp3(BigDecimal value) {
            // Simplified COMP-3 representation as text for output
            if (value == null) value = BigDecimal.ZERO;
            return String.format("%+013.2f", value.doubleValue());
        }
    }

    /**
     * Variable-length record 1 - maps to VBRC-REC1 in COBOL
     */
    private static class VbrcRec1 {
        public long vb1AcctId;                        // PIC 9(11)
        public String vb1AcctActiveStatus;            // PIC X(01)

        public VbrcRec1() {
            vb1AcctId = 0;
            vb1AcctActiveStatus = " ";
        }

        public String toLine() {
            return String.format("%011d", vb1AcctId) + 
                   (vb1AcctActiveStatus != null ? vb1AcctActiveStatus : " ");
        }
    }

    /**
     * Variable-length record 2 - maps to VBRC-REC2 in COBOL
     */
    private static class VbrcRec2 {
        public long vb2AcctId;                        // PIC 9(11)
        public BigDecimal vb2AcctCurrBal;             // PIC S9(10)V99
        public BigDecimal vb2AcctCreditLimit;         // PIC S9(10)V99
        public String vb2AcctReissueYyyy;             // PIC X(04)

        public VbrcRec2() {
            vb2AcctId = 0;
            vb2AcctCurrBal = BigDecimal.ZERO;
            vb2AcctCreditLimit = BigDecimal.ZERO;
            vb2AcctReissueYyyy = "    ";
        }

        public String toLine() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%011d", vb2AcctId));
            sb.append(formatDecimal(vb2AcctCurrBal, 12, 2));
            sb.append(formatDecimal(vb2AcctCreditLimit, 12, 2));
            sb.append(vb2AcctReissueYyyy != null ? vb2AcctReissueYyyy : "    ");
            return sb.toString();
        }

        private String formatDecimal(BigDecimal value, int totalDigits, int decimals) {
            if (value == null) value = BigDecimal.ZERO;
            String sign = value.compareTo(BigDecimal.ZERO) < 0 ? "-" : "+";
            BigDecimal absValue = value.abs();
            long intPart = absValue.movePointRight(decimals).longValue();
            return sign + String.format("%0" + (totalDigits - 1) + "d", intPart);
        }
    }
}