// Generated by CardDemo Agentic Converter on 2026-03-21 18:44:26
// Source: AWS CardDemo (Apache 2.0)

/**
 * CbTrn03Service - Transaction Detail Report Generator
 * 
 * Converted from: CBTRN03C.CBL
 * Application: CardDemo
 * Type: Batch COBOL Program
 * Function: Print the transaction detail report.
 * 
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 * Licensed under the Apache License, Version 2.0
 */

import java.io.*;
import java.math.BigDecimal;
import java.nio.file.*;
import java.util.*;
import java.util.logging.*;

public class CbTrn03Service {

    private static final Logger logger = Logger.getLogger(CbTrn03Service.class.getName());

    // File paths from JCL DD names
    private final String tranFilePath = getEnv("TRANFILE", "data/TRANFILE.dat");
    private final String cardXrefPath = getEnv("CARDXREF", "data/CARDXREF.dat");
    private final String tranTypePath = getEnv("TRANTYPE", "data/TRANTYPE.dat");
    private final String tranCatgPath = getEnv("TRANCATG", "data/TRANCATG.dat");
    private final String tranReptPath = getEnv("TRANREPT", "data/TRANREPT.dat");
    private final String dateParmPath = getEnv("DATEPARM", "data/DATEPARM.dat");

    // File handlers
    private BufferedReader tranFileReader;
    private BufferedWriter reportFileWriter;
    private BufferedReader dateParmReader;
    private Map<String, CardXrefRecord> cardXrefMap;
    private Map<String, TranTypeRecord> tranTypeMap;
    private Map<String, TranCatRecord> tranCatgMap;

    // File status codes
    private String tranFileStatus = "00";
    private String cardXrefStatus = "00";
    private String tranTypeStatus = "00";
    private String tranCatgStatus = "00";
    private String tranReptStatus = "00";
    private String dateParmStatus = "00";

    // Working storage variables
    private String wsStartDate = "";
    private String wsEndDate = "";
    private boolean wsFirstTime = true;
    private int wsLineCounter = 0;
    private static final int WS_PAGE_SIZE = 20;
    private static final String WS_BLANK_LINE = " ".repeat(133);
    private BigDecimal wsPageTotal = BigDecimal.ZERO;
    private BigDecimal wsAccountTotal = BigDecimal.ZERO;
    private BigDecimal wsGrandTotal = BigDecimal.ZERO;
    private String wsCurrCardNum = "";

    // Current record holders
    private TranRecord tranRecord;
    private CardXrefRecord cardXrefRecord;
    private TranTypeRecord tranTypeRecord;
    private TranCatRecord tranCatRecord;

    // Application result codes
    private int applResult = 0;
    private static final int APPL_AOK = 0;
    private static final int APPL_EOF = 16;

    private boolean endOfFile = false;

    /**
     * Main execution method - equivalent to PROCEDURE DIVISION
     */
    public void execute() {
        logger.info("START OF EXECUTION OF PROGRAM CBTRN03C");

        // Open all files - 0000-TRANFILE-OPEN through 0500-DATEPARM-OPEN
        openTranFile();
        openReportFile();
        openCardXrefFile();
        openTranTypeFile();
        openTranCatgFile();
        openDateParmFile();

        // Read date parameters - 0550-DATEPARM-READ
        readDateParm();

        // Main processing loop
        while (!endOfFile) {
            // 1000-TRANFILE-GET-NEXT
            getNextTransaction();

            if (!endOfFile) {
                // Check date range filter
                String tranProcDate = tranRecord.tranProcTs != null && tranRecord.tranProcTs.length() >= 10
                        ? tranRecord.tranProcTs.substring(0, 10)
                        : "";

                if (tranProcDate.compareTo(wsStartDate) >= 0 && tranProcDate.compareTo(wsEndDate) <= 0) {
                    logger.info(tranRecord.toString());

                    // Check if card number changed
                    if (!wsCurrCardNum.equals(tranRecord.tranCardNum)) {
                        if (!wsFirstTime) {
                            // 1120-WRITE-ACCOUNT-TOTALS
                            writeAccountTotals();
                        }
                        wsCurrCardNum = tranRecord.tranCardNum;
                        // 1500-A-LOOKUP-XREF
                        lookupCardXref(tranRecord.tranCardNum);
                    }

                    // 1500-B-LOOKUP-TRANTYPE
                    lookupTranType(tranRecord.tranTypeCd);

                    // 1500-C-LOOKUP-TRANCATG
                    lookupTranCatg(tranRecord.tranTypeCd, tranRecord.tranCatCd);

                    // 1100-WRITE-TRANSACTION-REPORT
                    writeTransactionReport();
                }
            } else {
                // End of file processing
                logger.info("TRAN-AMT " + (tranRecord != null ? tranRecord.tranAmt : BigDecimal.ZERO));
                logger.info("WS-PAGE-TOTAL " + wsPageTotal);

                if (tranRecord != null && tranRecord.tranAmt != null) {
                    wsPageTotal = wsPageTotal.add(tranRecord.tranAmt);
                    wsAccountTotal = wsAccountTotal.add(tranRecord.tranAmt);
                }

                // 1110-WRITE-PAGE-TOTALS
                writePageTotals();
                // 1110-WRITE-GRAND-TOTALS
                writeGrandTotals();
            }
        }

        // Close all files - 9000-TRANFILE-CLOSE through 9500-DATEPARM-CLOSE
        closeTranFile();
        closeReportFile();
        closeCardXrefFile();
        closeTranTypeFile();
        closeTranCatgFile();
        closeDateParmFile();

        logger.info("END OF EXECUTION OF PROGRAM CBTRN03C");
    }

    /**
     * 0550-DATEPARM-READ - Read the date parameter file
     */
    private void readDateParm() {
        try {
            String line = dateParmReader.readLine();
            if (line != null) {
                dateParmStatus = "00";
                applResult = APPL_AOK;
                // Parse date parameters: format is START_DATE END_DATE (10 chars each with 1 char separator)
                if (line.length() >= 21) {
                    wsStartDate = line.substring(0, 10);
                    wsEndDate = line.substring(11, 21);
                }
                logger.info("Reporting from " + wsStartDate + " to " + wsEndDate);
            } else {
                dateParmStatus = "10";
                applResult = APPL_EOF;
                endOfFile = true;
            }
        } catch (IOException e) {
            dateParmStatus = "12";
            applResult = 12;
            logger.severe("ERROR READING DATEPARM FILE");
            displayIoStatus(dateParmStatus);
            abendProgram();
        }
    }

    /**
     * 1000-TRANFILE-GET-NEXT - Read next transaction record
     */
    private void getNextTransaction() {
        try {
            String line = tranFileReader.readLine();
            if (line != null) {
                tranFileStatus = "00";
                applResult = APPL_AOK;
                tranRecord = TranRecord.fromLine(line);
            } else {
                tranFileStatus = "10";
                applResult = APPL_EOF;
                endOfFile = true;
            }
        } catch (IOException e) {
            tranFileStatus = "12";
            applResult = 12;
            logger.severe("ERROR READING TRANSACTION FILE");
            displayIoStatus(tranFileStatus);
            abendProgram();
        }
    }

    /**
     * 1100-WRITE-TRANSACTION-REPORT - Write transaction to report
     */
    private void writeTransactionReport() {
        if (wsFirstTime) {
            wsFirstTime = false;
            // 1120-WRITE-HEADERS
            writeHeaders();
        }

        if (wsLineCounter % WS_PAGE_SIZE == 0 && wsLineCounter > 0) {
            // 1110-WRITE-PAGE-TOTALS
            writePageTotals();
            // 1120-WRITE-HEADERS
            writeHeaders();
        }

        wsPageTotal = wsPageTotal.add(tranRecord.tranAmt != null ? tranRecord.tranAmt : BigDecimal.ZERO);
        wsAccountTotal = wsAccountTotal.add(tranRecord.tranAmt != null ? tranRecord.tranAmt : BigDecimal.ZERO);

        // 1120-WRITE-DETAIL
        writeDetail();
    }

    /**
     * 1110-WRITE-PAGE-TOTALS - Write page totals
     */
    private void writePageTotals() {
        String pageTotalLine = formatPageTotals(wsPageTotal);
        writeReportRec(pageTotalLine);
        wsGrandTotal = wsGrandTotal.add(wsPageTotal);
        wsPageTotal = BigDecimal.ZERO;
        wsLineCounter++;

        writeReportRec(getTransactionHeader2());
        wsLineCounter++;
    }

    /**
     * 1120-WRITE-ACCOUNT-TOTALS - Write account totals
     */
    private void writeAccountTotals() {
        String accountTotalLine = formatAccountTotals(wsAccountTotal);
        writeReportRec(accountTotalLine);
        wsAccountTotal = BigDecimal.ZERO;
        wsLineCounter++;

        writeReportRec(getTransactionHeader2());
        wsLineCounter++;
    }

    /**
     * 1110-WRITE-GRAND-TOTALS - Write grand totals
     */
    private void writeGrandTotals() {
        String grandTotalLine = formatGrandTotals(wsGrandTotal);
        writeReportRec(grandTotalLine);
    }

    /**
     * 1120-WRITE-HEADERS - Write report headers
     */
    private void writeHeaders() {
        // Report name header
        ReportStructures.ReportNameHeader header = new ReportStructures.ReportNameHeader();
        header.reptStartDate = wsStartDate;
        header.reptEndDate = wsEndDate;
        writeReportRec(header.toLine());
        wsLineCounter++;

        // Blank line
        writeReportRec(WS_BLANK_LINE);
        wsLineCounter++;

        // Transaction header 1
        ReportStructures.TransactionHeader1 transHeader1 = new ReportStructures.TransactionHeader1();
        writeReportRec(transHeader1.toLine());
        wsLineCounter++;

        // Transaction header 2 (separator line)
        writeReportRec(getTransactionHeader2());
        wsLineCounter++;
    }

    /**
     * 1111-WRITE-REPORT-REC - Write a record to the report file
     */
    private void writeReportRec(String line) {
        try {
            reportFileWriter.write(line);
            reportFileWriter.newLine();
            tranReptStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranReptStatus = "12";
            applResult = 12;
            logger.severe("ERROR WRITING REPTFILE");
            displayIoStatus(tranReptStatus);
            abendProgram();
        }
    }

    /**
     * 1120-WRITE-DETAIL - Write transaction detail line
     */
    private void writeDetail() {
        ReportStructures.TransactionDetailReport detail = new ReportStructures.TransactionDetailReport();
        detail.tranReportTransId = tranRecord.tranId != null ? tranRecord.tranId : "";
        detail.tranReportAccountId = cardXrefRecord != null ? String.valueOf(cardXrefRecord.xrefAcctId) : "";
        detail.tranReportTypeCd = tranRecord.tranTypeCd != null ? tranRecord.tranTypeCd : "";
        detail.tranReportTypeDesc = tranTypeRecord != null && tranTypeRecord.tranTypeDesc != null 
                ? tranTypeRecord.tranTypeDesc : "";
        detail.tranReportCatCd = tranRecord.tranCatCd;
        detail.tranReportCatDesc = tranCatRecord != null && tranCatRecord.tranCatTypeDesc != null 
                ? tranCatRecord.tranCatTypeDesc : "";
        detail.tranReportSource = tranRecord.tranSource != null ? tranRecord.tranSource : "";
        detail.tranReportAmt = tranRecord.tranAmt != null ? tranRecord.tranAmt.toString() : "0.00";

        writeReportRec(detail.toLine());
        wsLineCounter++;
    }

    /**
     * 0000-TRANFILE-OPEN - Open transaction file
     */
    private void openTranFile() {
        applResult = 8;
        try {
            tranFileReader = new BufferedReader(new FileReader(tranFilePath));
            tranFileStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranFileStatus = "12";
            applResult = 12;
            logger.severe("ERROR OPENING TRANFILE");
            displayIoStatus(tranFileStatus);
            abendProgram();
        }
    }

    /**
     * 0100-REPTFILE-OPEN - Open report file
     */
    private void openReportFile() {
        applResult = 8;
        try {
            reportFileWriter = new BufferedWriter(new FileWriter(tranReptPath));
            tranReptStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranReptStatus = "12";
            applResult = 12;
            logger.severe("ERROR OPENING REPTFILE");
            displayIoStatus(tranReptStatus);
            abendProgram();
        }
    }

    /**
     * 0200-CARDXREF-OPEN - Open card cross-reference file (VSAM KSDS)
     */
    private void openCardXrefFile() {
        applResult = 8;
        cardXrefMap = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(cardXrefPath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                CardXrefRecord record = CardXrefRecord.fromLine(line);
                cardXrefMap.put(record.xrefCardNum, record);
            }
            cardXrefStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            cardXrefStatus = "12";
            applResult = 12;
            logger.severe("ERROR OPENING CROSS REF FILE");
            displayIoStatus(cardXrefStatus);
            abendProgram();
        }
    }

    /**
     * 0300-TRANTYPE-OPEN - Open transaction type file (VSAM KSDS)
     */
    private void openTranTypeFile() {
        applResult = 8;
        tranTypeMap = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(tranTypePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                TranTypeRecord record = TranTypeRecord.fromLine(line);
                tranTypeMap.put(record.tranType, record);
            }
            tranTypeStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranTypeStatus = "12";
            applResult = 12;
            logger.severe("ERROR OPENING TRANSACTION TYPE FILE");
            displayIoStatus(tranTypeStatus);
            abendProgram();
        }
    }

    /**
     * 0400-TRANCATG-OPEN - Open transaction category file (VSAM KSDS)
     */
    private void openTranCatgFile() {
        applResult = 8;
        tranCatgMap = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(tranCatgPath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                TranCatRecord record = TranCatRecord.fromLine(line);
                String key = record.tranTypeCd + String.format("%04d", record.tranCatCd);
                tranCatgMap.put(key, record);
            }
            tranCatgStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranCatgStatus = "12";
            applResult = 12;
            logger.severe("ERROR OPENING TRANSACTION CATG FILE");
            displayIoStatus(tranCatgStatus);
            abendProgram();
        }
    }

    /**
     * 0500-DATEPARM-OPEN - Open date parameters file
     */
    private void openDateParmFile() {
        applResult = 8;
        try {
            dateParmReader = new BufferedReader(new FileReader(dateParmPath));
            dateParmStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            dateParmStatus = "12";
            applResult = 12;
            logger.severe("ERROR OPENING DATE PARM FILE");
            displayIoStatus(dateParmStatus);
            abendProgram();
        }
    }

    /**
     * 1500-A-LOOKUP-XREF - Look up card cross-reference
     */
    private void lookupCardXref(String cardNum) {
        cardXrefRecord = cardXrefMap.get(cardNum);
        if (cardXrefRecord == null) {
            logger.severe("INVALID CARD NUMBER : " + cardNum);
            displayIoStatus("23");
            abendProgram();
        }
    }

    /**
     * 1500-B-LOOKUP-TRANTYPE - Look up transaction type
     */
    private void lookupTranType(String tranType) {
        tranTypeRecord = tranTypeMap.get(tranType);
        if (tranTypeRecord == null) {
            logger.severe("INVALID TRANSACTION TYPE : " + tranType);
            displayIoStatus("23");
            abendProgram();
        }
    }

    /**
     * 1500-C-LOOKUP-TRANCATG - Look up transaction category
     */
    private void lookupTranCatg(String tranTypeCd, int tranCatCd) {
        String key = tranTypeCd + String.format("%04d", tranCatCd);
        tranCatRecord = tranCatgMap.get(key);
        if (tranCatRecord == null) {
            logger.severe("INVALID TRAN CATG KEY : " + key);
            displayIoStatus("23");
            abendProgram();
        }
    }

    /**
     * 9000-TRANFILE-CLOSE - Close transaction file
     */
    private void closeTranFile() {
        applResult = 8;
        try {
            if (tranFileReader != null) {
                tranFileReader.close();
            }
            tranFileStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranFileStatus = "12";
            applResult = 12;
            logger.severe("ERROR CLOSING POSTED TRANSACTION FILE");
            displayIoStatus(tranFileStatus);
            abendProgram();
        }
    }

    /**
     * 9100-REPTFILE-CLOSE - Close report file
     */
    private void closeReportFile() {
        applResult = 8;
        try {
            if (reportFileWriter != null) {
                reportFileWriter.close();
            }
            tranReptStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranReptStatus = "12";
            applResult = 12;
            logger.severe("ERROR CLOSING REPORT FILE");
            displayIoStatus(tranReptStatus);
            abendProgram();
        }
    }

    /**
     * 9200-CARDXREF-CLOSE - Close card cross-reference file
     */
    private void closeCardXrefFile() {
        applResult = 8;
        cardXrefMap = null;
        cardXrefStatus = "00";
        applResult = APPL_AOK;
    }

    /**
     * 9300-TRANTYPE-CLOSE - Close transaction type file
     */
    private void closeTranTypeFile() {
        applResult = 8;
        tranTypeMap = null;
        tranTypeStatus = "00";
        applResult = APPL_AOK;
    }

    /**
     * 9400-TRANCATG-CLOSE - Close transaction category file
     */
    private void closeTranCatgFile() {
        applResult = 8;
        tranCatgMap = null;
        tranCatgStatus = "00";
        applResult = APPL_AOK;
    }

    /**
     * 9500-DATEPARM-CLOSE - Close date parameters file
     */
    private void closeDateParmFile() {
        applResult = 8;
        try {
            if (dateParmReader != null) {
                dateParmReader.close();
            }
            dateParmStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            dateParmStatus = "12";
            applResult = 12;
            logger.severe("ERROR CLOSING DATE PARM FILE");
            displayIoStatus(dateParmStatus);
            abendProgram();
        }
    }

    /**
     * 9910-DISPLAY-IO-STATUS - Display I/O status
     */
    private void displayIoStatus(String ioStatus) {
        logger.info("FILE STATUS IS: " + ioStatus);
    }

    /**
     * 9999-ABEND-PROGRAM - Abnormal end program
     */
    private void abendProgram() {
        logger.severe("ABENDING PROGRAM");
        throw new RuntimeException("ABEND: Program terminated abnormally with code 999");
    }

    /**
     * Get transaction header 2 (separator line)
     */
    private String getTransactionHeader2() {
        return "-".repeat(133);
    }

    /**
     * Format page totals line
     */
    private String formatPageTotals(BigDecimal total) {
        return String.format("%-100s PAGE TOTAL: %15.2f", "", total);
    }

    /**
     * Format account totals line
     */
    private String formatAccountTotals(BigDecimal total) {
        return String.format("%-97s ACCOUNT TOTAL: %15.2f", "", total);
    }

    /**
     * Format grand totals line
     */
    private String formatGrandTotals(BigDecimal total) {
        return String.format("%-99s GRAND TOTAL: %15.2f", "", total);
    }

    /**
     * Get environment variable with default
     */
    private static String getEnv(String key, String def) {
        String v = System.getenv(key);
        return (v != null && !v.isEmpty()) ? v : def;
    }

    /**
     * Main entry point for batch execution
     */
    public static void main(String[] args) {
        CbTrn03Service service = new CbTrn03Service();
        service.execute();
    }
}