// Generated by CardDemo Agentic Converter on 2026-03-21 18:43:04
// Source: AWS CardDemo (Apache 2.0)

/**
 * CbTrn02Service - Java service class converted from CBTRN02C.cbl
 * 
 * Application: CardDemo
 * Type: Batch Service
 * Function: Post the records from daily transaction file.
 * 
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 * Licensed under the Apache License, Version 2.0
 */

import java.io.*;
import java.math.BigDecimal;
import java.nio.file.*;
import java.util.*;
import java.util.logging.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class CbTrn02Service {

    private static final Logger logger = Logger.getLogger(CbTrn02Service.class.getName());

    // File paths from JCL DD names
    private final String dalytranPath;
    private final String tranfilePath;
    private final String xreffilePath;
    private final String dalyrejsPath;
    private final String acctfilePath;
    private final String tcatbalfPath;

    // File handlers
    private BufferedReader dalytranReader;
    private BufferedWriter tranfileWriter;
    private BufferedWriter dalyrejsWriter;
    private Map<String, CardXrefRecord> xrefMap;
    private Map<Long, AccountRecord> accountMap;
    private Map<String, TranCatBalRecord> tcatbalMap;

    // Working storage variables
    private DailyTranRecord dalytranRecord;
    private TranRecord tranRecord;
    private CardXrefRecord cardXrefRecord;
    private AccountRecord accountRecord;
    private TranCatBalRecord tranCatBalRecord;

    // Status variables
    private boolean endOfFile = false;
    private int applResult = 0;

    // Counters
    private int wsTransactionCount = 0;
    private int wsRejectCount = 0;
    private BigDecimal wsTempBal = BigDecimal.ZERO;

    // Validation variables
    private int wsValidationFailReason = 0;
    private String wsValidationFailReasonDesc = "";

    // Flags
    private boolean wsCreateTrancatRec = false;

    // Return code
    private int returnCode = 0;

    /**
     * Constructor - Initialize file paths from environment variables
     */
    public CbTrn02Service() {
        this.dalytranPath = getEnv("DALYTRAN", "data/DALYTRAN.dat");
        this.tranfilePath = getEnv("TRANFILE", "data/TRANFILE.dat");
        this.xreffilePath = getEnv("XREFFILE", "data/XREFFILE.dat");
        this.dalyrejsPath = getEnv("DALYREJS", "data/DALYREJS.dat");
        this.acctfilePath = getEnv("ACCTFILE", "data/ACCTFILE.dat");
        this.tcatbalfPath = getEnv("TCATBALF", "data/TCATBALF.dat");

        this.xrefMap = new HashMap<>();
        this.accountMap = new HashMap<>();
        this.tcatbalMap = new HashMap<>();
    }

    /**
     * Main execution method - PROCEDURE DIVISION
     */
    public int execute() {
        logger.info("START OF EXECUTION OF PROGRAM CBTRN02C");

        // 0000-DALYTRAN-OPEN
        openDalytranFile();
        // 0100-TRANFILE-OPEN
        openTranfile();
        // 0200-XREFFILE-OPEN
        openXreffile();
        // 0300-DALYREJS-OPEN
        openDalyrejsFile();
        // 0400-ACCTFILE-OPEN
        openAcctfile();
        // 0500-TCATBALF-OPEN
        openTcatbalFile();

        // Main processing loop
        while (!endOfFile) {
            if (!endOfFile) {
                // 1000-DALYTRAN-GET-NEXT
                getDalytranNext();
                if (!endOfFile) {
                    wsTransactionCount++;
                    wsValidationFailReason = 0;
                    wsValidationFailReasonDesc = "";
                    
                    // 1500-VALIDATE-TRAN
                    validateTran();
                    
                    if (wsValidationFailReason == 0) {
                        // 2000-POST-TRANSACTION
                        postTransaction();
                    } else {
                        wsRejectCount++;
                        // 2500-WRITE-REJECT-REC
                        writeRejectRec();
                    }
                }
            }
        }

        // 9000-DALYTRAN-CLOSE
        closeDalytranFile();
        // 9100-TRANFILE-CLOSE
        closeTranfile();
        // 9200-XREFFILE-CLOSE
        closeXreffile();
        // 9300-DALYREJS-CLOSE
        closeDalyrejsFile();
        // 9400-ACCTFILE-CLOSE
        closeAcctfile();
        // 9500-TCATBALF-CLOSE
        closeTcatbalFile();

        logger.info("TRANSACTIONS PROCESSED :" + wsTransactionCount);
        logger.info("TRANSACTIONS REJECTED  :" + wsRejectCount);

        if (wsRejectCount > 0) {
            returnCode = 4;
        }

        logger.info("END OF EXECUTION OF PROGRAM CBTRN02C");
        return returnCode;
    }

    /**
     * 0000-DALYTRAN-OPEN - Open daily transaction input file
     */
    private void openDalytranFile() {
        applResult = 8;
        try {
            dalytranReader = new BufferedReader(new FileReader(dalytranPath));
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING DALYTRAN");
            displayIoStatus("DALYTRAN", applResult);
            abendProgram();
        }
    }

    /**
     * 0100-TRANFILE-OPEN - Open transaction output file (VSAM KSDS OUTPUT)
     */
    private void openTranfile() {
        applResult = 8;
        try {
            tranfileWriter = new BufferedWriter(new FileWriter(tranfilePath));
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING TRANSACTION FILE");
            displayIoStatus("TRANFILE", applResult);
            abendProgram();
        }
    }

    /**
     * 0200-XREFFILE-OPEN - Open cross reference file (VSAM KSDS INPUT)
     */
    private void openXreffile() {
        applResult = 8;
        try {
            BufferedReader reader = new BufferedReader(new FileReader(xreffilePath));
            String line;
            while ((line = reader.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    CardXrefRecord record = CardXrefRecord.fromLine(line);
                    xrefMap.put(record.xrefCardNum, record);
                }
            }
            reader.close();
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING CROSS REF FILE");
            displayIoStatus("XREFFILE", applResult);
            abendProgram();
        }
    }

    /**
     * 0300-DALYREJS-OPEN - Open daily rejects output file
     */
    private void openDalyrejsFile() {
        applResult = 8;
        try {
            dalyrejsWriter = new BufferedWriter(new FileWriter(dalyrejsPath));
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING DALY REJECTS FILE");
            displayIoStatus("DALYREJS", applResult);
            abendProgram();
        }
    }

    /**
     * 0400-ACCTFILE-OPEN - Open account file (VSAM KSDS I-O)
     */
    private void openAcctfile() {
        applResult = 8;
        try {
            BufferedReader reader = new BufferedReader(new FileReader(acctfilePath));
            String line;
            while ((line = reader.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    AccountRecord record = AccountRecord.fromLine(line);
                    accountMap.put(record.acctId, record);
                }
            }
            reader.close();
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING ACCOUNT MASTER FILE");
            displayIoStatus("ACCTFILE", applResult);
            abendProgram();
        }
    }

    /**
     * 0500-TCATBALF-OPEN - Open transaction category balance file (VSAM KSDS I-O)
     */
    private void openTcatbalFile() {
        applResult = 8;
        try {
            File file = new File(tcatbalfPath);
            if (file.exists()) {
                BufferedReader reader = new BufferedReader(new FileReader(tcatbalfPath));
                String line;
                while ((line = reader.readLine()) != null) {
                    if (!line.trim().isEmpty()) {
                        TranCatBalRecord record = TranCatBalRecord.fromLine(line);
                        String key = buildTcatKey(record.trancatAcctId, record.trancatTypeCd, record.trancatCd);
                        tcatbalMap.put(key, record);
                    }
                }
                reader.close();
            }
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR OPENING TRANSACTION BALANCE FILE");
            displayIoStatus("TCATBALF", applResult);
            abendProgram();
        }
    }

    /**
     * 1000-DALYTRAN-GET-NEXT - Read next record from daily transaction file
     */
    private void getDalytranNext() {
        try {
            String line = dalytranReader.readLine();
            if (line != null) {
                dalytranRecord = DailyTranRecord.fromLine(line);
                applResult = 0;
            } else {
                applResult = 16; // EOF
            }
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult == 0) {
            // Continue processing
        } else if (applResult == 16) {
            endOfFile = true;
        } else {
            logger.severe("ERROR READING DALYTRAN FILE");
            displayIoStatus("DALYTRAN", applResult);
            abendProgram();
        }
    }

    /**
     * 1500-VALIDATE-TRAN - Validate the transaction
     */
    private void validateTran() {
        // 1500-A-LOOKUP-XREF
        lookupXref();
        
        if (wsValidationFailReason == 0) {
            // 1500-B-LOOKUP-ACCT
            lookupAcct();
        }
        // ADD MORE VALIDATIONS HERE
    }

    /**
     * 1500-A-LOOKUP-XREF - Lookup card cross reference
     */
    private void lookupXref() {
        String cardNum = dalytranRecord.dalytranCardNum;
        cardXrefRecord = xrefMap.get(cardNum);
        
        if (cardXrefRecord == null) {
            wsValidationFailReason = 100;
            wsValidationFailReasonDesc = "INVALID CARD NUMBER FOUND";
        }
    }

    /**
     * 1500-B-LOOKUP-ACCT - Lookup account and validate
     */
    private void lookupAcct() {
        long acctId = cardXrefRecord.xrefAcctId;
        accountRecord = accountMap.get(acctId);
        
        if (accountRecord == null) {
            wsValidationFailReason = 101;
            wsValidationFailReasonDesc = "ACCOUNT RECORD NOT FOUND";
        } else {
            // Calculate temp balance
            wsTempBal = accountRecord.acctCurrCycCredit
                    .subtract(accountRecord.acctCurrCycDebit)
                    .add(dalytranRecord.dalytranAmt);

            if (accountRecord.acctCreditLimit.compareTo(wsTempBal) < 0) {
                wsValidationFailReason = 102;
                wsValidationFailReasonDesc = "OVERLIMIT TRANSACTION";
            }

            // Check expiration date
            String tranOrigTs = dalytranRecord.dalytranOrigTs;
            String tranDate = tranOrigTs.length() >= 10 ? tranOrigTs.substring(0, 10) : tranOrigTs;
            
            if (accountRecord.acctExpiraionDate.compareTo(tranDate) < 0) {
                wsValidationFailReason = 103;
                wsValidationFailReasonDesc = "TRANSACTION RECEIVED AFTER ACCT EXPIRATION";
            }
        }
    }

    /**
     * 2000-POST-TRANSACTION - Post the validated transaction
     */
    private void postTransaction() {
        // Create new transaction record
        tranRecord = new TranRecord();
        tranRecord.tranId = dalytranRecord.dalytranId;
        tranRecord.tranTypeCd = dalytranRecord.dalytranTypeCd;
        tranRecord.tranCatCd = dalytranRecord.dalytranCatCd;
        tranRecord.tranSource = dalytranRecord.dalytranSource;
        tranRecord.tranDesc = dalytranRecord.dalytranDesc;
        tranRecord.tranAmt = dalytranRecord.dalytranAmt;
        tranRecord.tranMerchantId = dalytranRecord.dalytranMerchantId;
        tranRecord.tranMerchantName = dalytranRecord.dalytranMerchantName;
        tranRecord.tranMerchantCity = dalytranRecord.dalytranMerchantCity;
        tranRecord.tranMerchantZip = dalytranRecord.dalytranMerchantZip;
        tranRecord.tranCardNum = dalytranRecord.dalytranCardNum;
        tranRecord.tranOrigTs = dalytranRecord.dalytranOrigTs;
        tranRecord.tranProcTs = getDb2FormatTimestamp();

        // 2700-UPDATE-TCATBAL
        updateTcatbal();
        // 2800-UPDATE-ACCOUNT-REC
        updateAccountRec();
        // 2900-WRITE-TRANSACTION-FILE
        writeTransactionFile();
    }

    /**
     * 2500-WRITE-REJECT-REC - Write rejected transaction to rejects file
     */
    private void writeRejectRec() {
        applResult = 8;
        try {
            // Build reject record: transaction data (350) + validation trailer (80)
            String tranData = dalytranRecord.toLine();
            // Pad to 350 characters
            tranData = String.format("%-350s", tranData);
            if (tranData.length() > 350) {
                tranData = tranData.substring(0, 350);
            }
            
            // Build validation trailer
            String validationTrailer = String.format("%04d%-76s", 
                    wsValidationFailReason, wsValidationFailReasonDesc);
            
            String rejectRecord = tranData + validationTrailer;
            dalyrejsWriter.write(rejectRecord);
            dalyrejsWriter.newLine();
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR WRITING TO REJECTS FILE");
            displayIoStatus("DALYREJS", applResult);
            abendProgram();
        }
    }

    /**
     * 2700-UPDATE-TCATBAL - Update transaction category balance
     */
    private void updateTcatbal() {
        long acctId = cardXrefRecord.xrefAcctId;
        String typeCd = dalytranRecord.dalytranTypeCd;
        int catCd = dalytranRecord.dalytranCatCd;
        String tcatKey = buildTcatKey(acctId, typeCd, catCd);

        wsCreateTrancatRec = false;
        tranCatBalRecord = tcatbalMap.get(tcatKey);
        
        if (tranCatBalRecord == null) {
            logger.info("TCATBAL record not found for key : " + tcatKey + ".. Creating.");
            wsCreateTrancatRec = true;
            applResult = 0;
        } else {
            applResult = 0;
        }

        if (applResult != 0) {
            logger.severe("ERROR READING TRANSACTION BALANCE FILE");
            displayIoStatus("TCATBALF", applResult);
            abendProgram();
        }

        if (wsCreateTrancatRec) {
            // 2700-A-CREATE-TCATBAL-REC
            createTcatbalRec(acctId, typeCd, catCd);
        } else {
            // 2700-B-UPDATE-TCATBAL-REC
            updateTcatbalRec();
        }
    }

    /**
     * 2700-A-CREATE-TCATBAL-REC - Create new transaction category balance record
     */
    private void createTcatbalRec(long acctId, String typeCd, int catCd) {
        tranCatBalRecord = new TranCatBalRecord();
        tranCatBalRecord.trancatAcctId = acctId;
        tranCatBalRecord.trancatTypeCd = typeCd;
        tranCatBalRecord.trancatCd = catCd;
        tranCatBalRecord.tranCatBal = dalytranRecord.dalytranAmt;

        String tcatKey = buildTcatKey(acctId, typeCd, catCd);
        tcatbalMap.put(tcatKey, tranCatBalRecord);
        applResult = 0;

        if (applResult != 0) {
            logger.severe("ERROR WRITING TRANSACTION BALANCE FILE");
            displayIoStatus("TCATBALF", applResult);
            abendProgram();
        }
    }

    /**
     * 2700-B-UPDATE-TCATBAL-REC - Update existing transaction category balance record
     */
    private void updateTcatbalRec() {
        tranCatBalRecord.tranCatBal = tranCatBalRecord.tranCatBal.add(dalytranRecord.dalytranAmt);
        
        String tcatKey = buildTcatKey(tranCatBalRecord.trancatAcctId, 
                tranCatBalRecord.trancatTypeCd, tranCatBalRecord.trancatCd);
        tcatbalMap.put(tcatKey, tranCatBalRecord);
        applResult = 0;

        if (applResult != 0) {
            logger.severe("ERROR REWRITING TRANSACTION BALANCE FILE");
            displayIoStatus("TCATBALF", applResult);
            abendProgram();
        }
    }

    /**
     * 2800-UPDATE-ACCOUNT-REC - Update account record with posted transaction
     */
    private void updateAccountRec() {
        accountRecord.acctCurrBal = accountRecord.acctCurrBal.add(dalytranRecord.dalytranAmt);
        
        if (dalytranRecord.dalytranAmt.compareTo(BigDecimal.ZERO) >= 0) {
            accountRecord.acctCurrCycCredit = accountRecord.acctCurrCycCredit.add(dalytranRecord.dalytranAmt);
        } else {
            accountRecord.acctCurrCycDebit = accountRecord.acctCurrCycDebit.add(dalytranRecord.dalytranAmt);
        }

        // Update in map (will be written at close)
        accountMap.put(accountRecord.acctId, accountRecord);
    }

    /**
     * 2900-WRITE-TRANSACTION-FILE - Write transaction to output file
     */
    private void writeTransactionFile() {
        applResult = 8;
        try {
            tranfileWriter.write(tranRecord.toLine());
            tranfileWriter.newLine();
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR WRITING TO TRANSACTION FILE");
            displayIoStatus("TRANFILE", applResult);
            abendProgram();
        }
    }

    /**
     * 9000-DALYTRAN-CLOSE - Close daily transaction file
     */
    private void closeDalytranFile() {
        applResult = 8;
        try {
            if (dalytranReader != null) {
                dalytranReader.close();
            }
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR CLOSING DALYTRAN FILE");
            displayIoStatus("DALYTRAN", applResult);
            abendProgram();
        }
    }

    /**
     * 9100-TRANFILE-CLOSE - Close transaction output file
     */
    private void closeTranfile() {
        applResult = 8;
        try {
            if (tranfileWriter != null) {
                tranfileWriter.close();
            }
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR CLOSING TRANSACTION FILE");
            displayIoStatus("TRANFILE", applResult);
            abendProgram();
        }
    }

    /**
     * 9200-XREFFILE-CLOSE - Close cross reference file
     */
    private void closeXreffile() {
        applResult = 8;
        // Map was loaded at open, nothing to close
        applResult = 0;

        if (applResult != 0) {
            logger.severe("ERROR CLOSING CROSS REF FILE");
            displayIoStatus("XREFFILE", applResult);
            abendProgram();
        }
    }

    /**
     * 9300-DALYREJS-CLOSE - Close daily rejects file
     */
    private void closeDalyrejsFile() {
        applResult = 8;
        try {
            if (dalyrejsWriter != null) {
                dalyrejsWriter.close();
            }
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR CLOSING DAILY REJECTS FILE");
            displayIoStatus("DALYREJS", applResult);
            abendProgram();
        }
    }

    /**
     * 9400-ACCTFILE-CLOSE - Close account file and write back changes
     */
    private void closeAcctfile() {
        applResult = 8;
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(acctfilePath));
            for (AccountRecord record : accountMap.values()) {
                writer.write(record.toLine());
                writer.newLine();
            }
            writer.close();
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR CLOSING ACCOUNT FILE");
            displayIoStatus("ACCTFILE", applResult);
            abendProgram();
        }
    }

    /**
     * 9500-TCATBALF-CLOSE - Close transaction category balance file and write back changes
     */
    private void closeTcatbalFile() {
        applResult = 8;
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(tcatbalfPath));
            for (TranCatBalRecord record : tcatbalMap.values()) {
                writer.write(record.toLine());
                writer.newLine();
            }
            writer.close();
            applResult = 0;
        } catch (IOException e) {
            applResult = 12;
        }

        if (applResult != 0) {
            logger.severe("ERROR CLOSING TRANSACTION BALANCE FILE");
            displayIoStatus("TCATBALF", applResult);
            abendProgram();
        }
    }

    /**
     * Z-GET-DB2-FORMAT-TIMESTAMP - Get current timestamp in DB2 format
     */
    private String getDb2FormatTimestamp() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd-HH.mm.ss.SS'0000'");
        return LocalDateTime.now().format(formatter);
    }

    /**
     * 9910-DISPLAY-IO-STATUS - Display I/O status information
     */
    private void displayIoStatus(String fileName, int status) {
        logger.severe("FILE STATUS IS: " + fileName + " STATUS=" + String.format("%04d", status));
    }

    /**
     * 9999-ABEND-PROGRAM - Abnormal program termination
     */
    private void abendProgram() {
        logger.severe("ABENDING PROGRAM");
        throw new RuntimeException("ABEND: Program terminated abnormally with code 999");
    }

    /**
     * Build transaction category balance key
     */
    private String buildTcatKey(long acctId, String typeCd, int catCd) {
        return String.format("%011d%2s%04d", acctId, typeCd, catCd);
    }

    /**
     * Get environment variable with default value
     */
    private static String getEnv(String key, String def) {
        String v = System.getenv(key);
        return (v != null && !v.isEmpty()) ? v : def;
    }

    /**
     * Main method for standalone execution
     */
    public static void main(String[] args) {
        CbTrn02Service service = new CbTrn02Service();
        int rc = service.execute();
        System.exit(rc);
    }
}