// Generated by CardDemo Agentic Converter on 2026-03-21 18:41:22
// Source: AWS CardDemo (Apache 2.0)

/**
 * CBTRN01C - Post the records from daily transaction file.
 * 
 * Converted from COBOL program CBTRN01C.cbl
 * Application: CardDemo
 * Type: Batch COBOL Program
 * 
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License").
 */

import java.io.*;
import java.math.BigDecimal;
import java.nio.file.*;
import java.util.*;
import java.util.logging.*;

public class CbTrn01Service {

    private static final Logger logger = Logger.getLogger(CbTrn01Service.class.getName());

    // File paths from JCL DD names
    private final String dalyTranPath;
    private final String custFilePath;
    private final String xrefFilePath;
    private final String cardFilePath;
    private final String acctFilePath;
    private final String tranFilePath;

    // File handlers
    private BufferedReader dalyTranReader;
    private Map<Long, CustomerRecord> customerMap;
    private Map<String, CardXrefRecord> xrefMap;
    private Map<String, CardRecord> cardMap;
    private Map<Long, AccountRecord> accountMap;
    private Map<String, TranRecord> tranMap;

    // File status codes
    private String dalyTranStatus;
    private String custFileStatus;
    private String xrefFileStatus;
    private String cardFileStatus;
    private String acctFileStatus;
    private String tranFileStatus;
    private String ioStatus;

    // Working storage variables
    private DailyTranRecord dalyTranRecord;
    private CustomerRecord customerRecord;
    private CardXrefRecord cardXrefRecord;
    private CardRecord cardRecord;
    private AccountRecord accountRecord;
    private TranRecord tranRecord;

    private int applResult;
    private static final int APPL_AOK = 0;
    private static final int APPL_EOF = 16;

    private boolean endOfDailyTransFile;
    private int wsXrefReadStatus;
    private int wsAcctReadStatus;

    public CbTrn01Service() {
        this.dalyTranPath = getEnv("DALYTRAN", "data/DALYTRAN.dat");
        this.custFilePath = getEnv("CUSTFILE", "data/CUSTFILE.dat");
        this.xrefFilePath = getEnv("XREFFILE", "data/XREFFILE.dat");
        this.cardFilePath = getEnv("CARDFILE", "data/CARDFILE.dat");
        this.acctFilePath = getEnv("ACCTFILE", "data/ACCTFILE.dat");
        this.tranFilePath = getEnv("TRANFILE", "data/TRANFILE.dat");

        this.dalyTranRecord = new DailyTranRecord();
        this.customerRecord = new CustomerRecord();
        this.cardXrefRecord = new CardXrefRecord();
        this.cardRecord = new CardRecord();
        this.accountRecord = new AccountRecord();
        this.tranRecord = new TranRecord();

        this.endOfDailyTransFile = false;
    }

    /**
     * Main execution method - corresponds to MAIN-PARA in COBOL
     */
    public void execute() {
        logger.info("START OF EXECUTION OF PROGRAM CBTRN01C");

        // 0000-DALYTRAN-OPEN
        openDalyTranFile();
        // 0100-CUSTFILE-OPEN
        openCustFile();
        // 0200-XREFFILE-OPEN
        openXrefFile();
        // 0300-CARDFILE-OPEN
        openCardFile();
        // 0400-ACCTFILE-OPEN
        openAcctFile();
        // 0500-TRANFILE-OPEN
        openTranFile();

        // Main processing loop
        while (!endOfDailyTransFile) {
            if (!endOfDailyTransFile) {
                // 1000-DALYTRAN-GET-NEXT
                getDalyTranNext();
                if (!endOfDailyTransFile) {
                    logger.info(dalyTranRecord.toString());
                }
                wsXrefReadStatus = 0;
                cardXrefRecord.xrefCardNum = dalyTranRecord.dalytranCardNum;
                // 2000-LOOKUP-XREF
                lookupXref();
                if (wsXrefReadStatus == 0) {
                    wsAcctReadStatus = 0;
                    accountRecord.acctId = cardXrefRecord.xrefAcctId;
                    // 3000-READ-ACCOUNT
                    readAccount();
                    if (wsAcctReadStatus != 0) {
                        logger.info("ACCOUNT " + accountRecord.acctId + " NOT FOUND");
                    }
                } else {
                    logger.info("CARD NUMBER " + dalyTranRecord.dalytranCardNum +
                            " COULD NOT BE VERIFIED. SKIPPING TRANSACTION ID-" +
                            dalyTranRecord.dalytranId);
                }
            }
        }

        // 9000-DALYTRAN-CLOSE
        closeDalyTranFile();
        // 9100-CUSTFILE-CLOSE
        closeCustFile();
        // 9200-XREFFILE-CLOSE
        closeXrefFile();
        // 9300-CARDFILE-CLOSE
        closeCardFile();
        // 9400-ACCTFILE-CLOSE
        closeAcctFile();
        // 9500-TRANFILE-CLOSE
        closeTranFile();

        logger.info("END OF EXECUTION OF PROGRAM CBTRN01C");
    }

    /**
     * 1000-DALYTRAN-GET-NEXT - Read next record from daily transaction file
     */
    private void getDalyTranNext() {
        try {
            String line = dalyTranReader.readLine();
            if (line != null) {
                dalyTranRecord = DailyTranRecord.fromLine(line);
                dalyTranStatus = "00";
                applResult = APPL_AOK;
            } else {
                dalyTranStatus = "10";
                applResult = APPL_EOF;
            }
        } catch (IOException e) {
            dalyTranStatus = "12";
            applResult = 12;
        }

        if (applResult == APPL_AOK) {
            // Continue processing
        } else if (applResult == APPL_EOF) {
            endOfDailyTransFile = true;
        } else {
            logger.severe("ERROR READING DAILY TRANSACTION FILE");
            ioStatus = dalyTranStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 2000-LOOKUP-XREF - Lookup cross reference by card number
     */
    private void lookupXref() {
        String cardNum = cardXrefRecord.xrefCardNum;
        CardXrefRecord foundRecord = xrefMap.get(cardNum);
        if (foundRecord == null) {
            logger.info("INVALID CARD NUMBER FOR XREF");
            wsXrefReadStatus = 4;
        } else {
            cardXrefRecord = foundRecord;
            logger.info("SUCCESSFUL READ OF XREF");
            logger.info("CARD NUMBER: " + cardXrefRecord.xrefCardNum);
            logger.info("ACCOUNT ID : " + cardXrefRecord.xrefAcctId);
            logger.info("CUSTOMER ID: " + cardXrefRecord.xrefCustId);
        }
    }

    /**
     * 3000-READ-ACCOUNT - Read account record by account ID
     */
    private void readAccount() {
        long acctId = accountRecord.acctId;
        AccountRecord foundRecord = accountMap.get(acctId);
        if (foundRecord == null) {
            logger.info("INVALID ACCOUNT NUMBER FOUND");
            wsAcctReadStatus = 4;
        } else {
            accountRecord = foundRecord;
            logger.info("SUCCESSFUL READ OF ACCOUNT FILE");
        }
    }

    /**
     * 0000-DALYTRAN-OPEN - Open daily transaction file
     */
    private void openDalyTranFile() {
        applResult = 8;
        try {
            dalyTranReader = new BufferedReader(new FileReader(dalyTranPath));
            dalyTranStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            dalyTranStatus = "35";
            applResult = 12;
        }

        if (applResult != APPL_AOK) {
            logger.severe("ERROR OPENING DAILY TRANSACTION FILE");
            ioStatus = dalyTranStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 0100-CUSTFILE-OPEN - Open customer file
     */
    private void openCustFile() {
        applResult = 8;
        customerMap = new HashMap<>();
        try {
            Path path = Paths.get(custFilePath);
            if (Files.exists(path)) {
                List<String> lines = Files.readAllLines(path);
                for (String line : lines) {
                    CustomerRecord record = CustomerRecord.fromLine(line);
                    customerMap.put(record.custId, record);
                }
            }
            custFileStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            custFileStatus = "35";
            applResult = 12;
        }

        if (applResult != APPL_AOK) {
            logger.severe("ERROR OPENING CUSTOMER FILE");
            ioStatus = custFileStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 0200-XREFFILE-OPEN - Open cross reference file
     */
    private void openXrefFile() {
        applResult = 8;
        xrefMap = new HashMap<>();
        try {
            Path path = Paths.get(xrefFilePath);
            if (Files.exists(path)) {
                List<String> lines = Files.readAllLines(path);
                for (String line : lines) {
                    CardXrefRecord record = CardXrefRecord.fromLine(line);
                    xrefMap.put(record.xrefCardNum, record);
                }
            }
            xrefFileStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            xrefFileStatus = "35";
            applResult = 12;
        }

        if (applResult != APPL_AOK) {
            logger.severe("ERROR OPENING CROSS REF FILE");
            ioStatus = xrefFileStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 0300-CARDFILE-OPEN - Open card file
     */
    private void openCardFile() {
        applResult = 8;
        cardMap = new HashMap<>();
        try {
            Path path = Paths.get(cardFilePath);
            if (Files.exists(path)) {
                List<String> lines = Files.readAllLines(path);
                for (String line : lines) {
                    CardRecord record = CardRecord.fromLine(line);
                    cardMap.put(record.cardNum, record);
                }
            }
            cardFileStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            cardFileStatus = "35";
            applResult = 12;
        }

        if (applResult != APPL_AOK) {
            logger.severe("ERROR OPENING CARD FILE");
            ioStatus = cardFileStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 0400-ACCTFILE-OPEN - Open account file
     */
    private void openAcctFile() {
        applResult = 8;
        accountMap = new HashMap<>();
        try {
            Path path = Paths.get(acctFilePath);
            if (Files.exists(path)) {
                List<String> lines = Files.readAllLines(path);
                for (String line : lines) {
                    AccountRecord record = AccountRecord.fromLine(line);
                    accountMap.put(record.acctId, record);
                }
            }
            acctFileStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            acctFileStatus = "35";
            applResult = 12;
        }

        if (applResult != APPL_AOK) {
            logger.severe("ERROR OPENING ACCOUNT FILE");
            ioStatus = acctFileStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 0500-TRANFILE-OPEN - Open transaction file
     */
    private void openTranFile() {
        applResult = 8;
        tranMap = new HashMap<>();
        try {
            Path path = Paths.get(tranFilePath);
            if (Files.exists(path)) {
                List<String> lines = Files.readAllLines(path);
                for (String line : lines) {
                    TranRecord record = TranRecord.fromLine(line);
                    tranMap.put(record.tranId, record);
                }
            }
            tranFileStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            tranFileStatus = "35";
            applResult = 12;
        }

        if (applResult != APPL_AOK) {
            logger.severe("ERROR OPENING TRANSACTION FILE");
            ioStatus = tranFileStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 9000-DALYTRAN-CLOSE - Close daily transaction file
     */
    private void closeDalyTranFile() {
        applResult = 8;
        try {
            if (dalyTranReader != null) {
                dalyTranReader.close();
            }
            dalyTranStatus = "00";
            applResult = APPL_AOK;
        } catch (IOException e) {
            dalyTranStatus = "35";
            applResult = 12;
        }

        if (applResult != APPL_AOK) {
            logger.severe("ERROR CLOSING CUSTOMER FILE");
            ioStatus = custFileStatus;
            displayIoStatus();
            abendProgram();
        }
    }

    /**
     * 9100-CUSTFILE-CLOSE - Close customer file
     */
    private void closeCustFile() {
        applResult = 8;
        custFileStatus = "00";
        applResult = APPL_AOK;
        // HashMap doesn't need explicit close, data was read-only
    }

    /**
     * 9200-XREFFILE-CLOSE - Close cross reference file
     */
    private void closeXrefFile() {
        applResult = 8;
        xrefFileStatus = "00";
        applResult = APPL_AOK;
        // HashMap doesn't need explicit close, data was read-only
    }

    /**
     * 9300-CARDFILE-CLOSE - Close card file
     */
    private void closeCardFile() {
        applResult = 8;
        cardFileStatus = "00";
        applResult = APPL_AOK;
        // HashMap doesn't need explicit close, data was read-only
    }

    /**
     * 9400-ACCTFILE-CLOSE - Close account file
     */
    private void closeAcctFile() {
        applResult = 8;
        acctFileStatus = "00";
        applResult = APPL_AOK;
        // HashMap doesn't need explicit close, data was read-only
    }

    /**
     * 9500-TRANFILE-CLOSE - Close transaction file
     */
    private void closeTranFile() {
        applResult = 8;
        tranFileStatus = "00";
        applResult = APPL_AOK;
        // HashMap doesn't need explicit close, data was read-only
    }

    /**
     * Z-ABEND-PROGRAM - Abnormal program termination
     */
    private void abendProgram() {
        logger.severe("ABENDING PROGRAM");
        throw new RuntimeException("ABEND: Program terminated abnormally with code 999");
    }

    /**
     * Z-DISPLAY-IO-STATUS - Display I/O status for diagnostics
     */
    private void displayIoStatus() {
        if (ioStatus == null || ioStatus.length() < 2) {
            logger.info("FILE STATUS IS: NNNN0000");
            return;
        }
        char stat1 = ioStatus.charAt(0);
        char stat2 = ioStatus.charAt(1);
        String ioStatus04;
        if (!Character.isDigit(stat1) || !Character.isDigit(stat2) || stat1 == '9') {
            int binaryValue = (int) stat2;
            ioStatus04 = String.format("%c%03d", stat1, binaryValue);
        } else {
            ioStatus04 = "00" + ioStatus;
        }
        logger.info("FILE STATUS IS: NNNN" + ioStatus04);
    }

    /**
     * Utility method to get environment variable with default
     */
    private static String getEnv(String key, String def) {
        String v = System.getenv(key);
        return (v != null && !v.isEmpty()) ? v : def;
    }

    /**
     * Main method for standalone execution
     */
    public static void main(String[] args) {
        CbTrn01Service service = new CbTrn01Service();
        service.execute();
    }
}