// Generated by CardDemo Agentic Converter on 2026-03-21 19:10:04
// Source: AWS CardDemo (Apache 2.0)

/**
 * CbTrn03Service - Transaction Detail Report Generator
 * 
 * Converted from COBOL program: CBTRN03C.CBL
 * Application: CardDemo
 * Type: Batch Java Service
 * Function: Print the transaction detail report
 * 
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 * Licensed under the Apache License, Version 2.0
 */

import java.io.*;
import java.math.BigDecimal;
import java.nio.file.*;
import java.util.*;
import java.util.logging.*;

public class CbTrn03Service {

    private static final Logger logger = Logger.getLogger(CbTrn03Service.class.getName());

    // File paths from JCL DD names
    private final String tranFilePath;
    private final String cardXrefPath;
    private final String tranTypePath;
    private final String tranCatgPath;
    private final String reportPath;
    private final String dateParmPath;

    // File handlers
    private BufferedReader tranFileReader;
    private BufferedWriter reportWriter;
    private Map<String, CardXrefRecord> cardXrefMap;
    private Map<String, TranTypeRecord> tranTypeMap;
    private Map<String, TranCatRecord> tranCatgMap;

    // Working storage variables
    private String wsStartDate = "";
    private String wsEndDate = "";
    private boolean wsFirstTime = true;
    private int wsLineCounter = 0;
    private static final int WS_PAGE_SIZE = 20;
    private static final String WS_BLANK_LINE = " ".repeat(133);
    private BigDecimal wsPageTotal = BigDecimal.ZERO;
    private BigDecimal wsAccountTotal = BigDecimal.ZERO;
    private BigDecimal wsGrandTotal = BigDecimal.ZERO;
    private String wsCurrCardNum = "";

    // Current record being processed
    private TranRecord tranRecord;
    private CardXrefRecord xrefRecord;
    private TranTypeRecord tranTypeRecord;
    private TranCatRecord tranCatRecord;

    // End of file flag
    private boolean endOfFile = false;

    // Application result codes
    private static final int APPL_AOK = 0;
    private static final int APPL_EOF = 16;

    /**
     * Constructor - initializes file paths from environment variables
     */
    public CbTrn03Service() {
        this.tranFilePath = getEnv("TRANFILE", "data/TRANFILE.dat");
        this.cardXrefPath = getEnv("CARDXREF", "data/CARDXREF.dat");
        this.tranTypePath = getEnv("TRANTYPE", "data/TRANTYPE.dat");
        this.tranCatgPath = getEnv("TRANCATG", "data/TRANCATG.dat");
        this.reportPath = getEnv("TRANREPT", "data/TRANREPT.txt");
        this.dateParmPath = getEnv("DATEPARM", "data/DATEPARM.dat");
    }

    /**
     * Main execution method - PROCEDURE DIVISION
     */
    public void execute() {
        logger.info("START OF EXECUTION OF PROGRAM CBTRN03C");

        try {
            // 0000-TRANFILE-OPEN
            openTranFile();
            // 0100-REPTFILE-OPEN
            openReportFile();
            // 0200-CARDXREF-OPEN
            openCardXrefFile();
            // 0300-TRANTYPE-OPEN
            openTranTypeFile();
            // 0400-TRANCATG-OPEN
            openTranCatgFile();
            // 0500-DATEPARM-OPEN
            openDateParmFile();

            // 0550-DATEPARM-READ
            readDateParm();

            // Main processing loop
            while (!endOfFile) {
                // 1000-TRANFILE-GET-NEXT
                getTranFileNext();

                if (!endOfFile) {
                    // Check date range filter
                    String tranProcDate = tranRecord.tranProcTs != null && tranRecord.tranProcTs.length() >= 10
                            ? tranRecord.tranProcTs.substring(0, 10) : "";

                    if (tranProcDate.compareTo(wsStartDate) >= 0 && tranProcDate.compareTo(wsEndDate) <= 0) {
                        logger.info("Processing transaction: " + tranRecord.toString());

                        // Check if card number changed
                        if (!wsCurrCardNum.equals(tranRecord.tranCardNum)) {
                            if (!wsFirstTime) {
                                // 1120-WRITE-ACCOUNT-TOTALS
                                writeAccountTotals();
                            }
                            wsCurrCardNum = tranRecord.tranCardNum;
                            // 1500-A-LOOKUP-XREF
                            lookupXref(tranRecord.tranCardNum);
                        }

                        // 1500-B-LOOKUP-TRANTYPE
                        lookupTranType(tranRecord.tranTypeCd);
                        // 1500-C-LOOKUP-TRANCATG
                        lookupTranCatg(tranRecord.tranTypeCd, tranRecord.tranCatCd);
                        // 1100-WRITE-TRANSACTION-REPORT
                        writeTransactionReport();
                    }
                } else {
                    // End of file reached - write final totals
                    // Note: Do NOT add tranAmt again here - it was already added in writeTransactionReport
                    logger.info("WS-PAGE-TOTAL: " + wsPageTotal);
                    writePageTotals();
                    writeGrandTotals();
                }
            }

            // Close all files
            // 9000-TRANFILE-CLOSE
            closeTranFile();
            // 9100-REPTFILE-CLOSE
            closeReportFile();
            // 9200-CARDXREF-CLOSE
            closeCardXrefFile();
            // 9300-TRANTYPE-CLOSE
            closeTranTypeFile();
            // 9400-TRANCATG-CLOSE
            closeTranCatgFile();
            // 9500-DATEPARM-CLOSE
            closeDateParmFile();

            logger.info("END OF EXECUTION OF PROGRAM CBTRN03C");

        } catch (Exception e) {
            logger.severe("Error during execution: " + e.getMessage());
            abendProgram("Unexpected error: " + e.getMessage());
        }
    }

    /**
     * 0550-DATEPARM-READ - Read the date parameter file
     */
    private void readDateParm() {
        try (BufferedReader reader = new BufferedReader(new FileReader(dateParmPath))) {
            String line = reader.readLine();
            if (line != null && line.length() >= 21) {
                wsStartDate = line.substring(0, 10);
                wsEndDate = line.substring(11, 21);
                logger.info("Reporting from " + wsStartDate + " to " + wsEndDate);
            } else if (line == null) {
                endOfFile = true;
            } else {
                logger.severe("ERROR READING DATEPARM FILE - invalid format");
                abendProgram("ERROR READING DATEPARM FILE");
            }
        } catch (IOException e) {
            logger.severe("ERROR READING DATEPARM FILE: " + e.getMessage());
            abendProgram("ERROR READING DATEPARM FILE");
        }
    }

    /**
     * 1000-TRANFILE-GET-NEXT - Read next transaction record
     */
    private void getTranFileNext() {
        try {
            String line = tranFileReader.readLine();
            if (line != null) {
                tranRecord = TranRecord.fromLine(line);
            } else {
                endOfFile = true;
            }
        } catch (IOException e) {
            logger.severe("ERROR READING TRANSACTION FILE: " + e.getMessage());
            abendProgram("ERROR READING TRANSACTION FILE");
        }
    }

    /**
     * 1100-WRITE-TRANSACTION-REPORT - Write transaction to report
     */
    private void writeTransactionReport() {
        if (wsFirstTime) {
            wsFirstTime = false;
            // 1120-WRITE-HEADERS
            writeHeaders();
        }

        if (wsLineCounter % WS_PAGE_SIZE == 0 && wsLineCounter > 0) {
            // 1110-WRITE-PAGE-TOTALS
            writePageTotals();
            // 1120-WRITE-HEADERS
            writeHeaders();
        }

        // Add transaction amount to totals
        if (tranRecord.tranAmt != null) {
            wsPageTotal = wsPageTotal.add(tranRecord.tranAmt);
            wsAccountTotal = wsAccountTotal.add(tranRecord.tranAmt);
        }

        // 1120-WRITE-DETAIL
        writeDetail();
    }

    /**
     * 1110-WRITE-PAGE-TOTALS - Write page totals
     */
    private void writePageTotals() {
        String pageTotalLine = String.format("%-100s PAGE TOTAL: %20s", "", 
                String.format("%,.2f", wsPageTotal));
        writeReportRec(padRight(pageTotalLine, 133));

        // Accumulate to grand total before resetting
        wsGrandTotal = wsGrandTotal.add(wsPageTotal);
        wsPageTotal = BigDecimal.ZERO;
        wsLineCounter++;

        writeReportRec(createSeparatorLine());
        wsLineCounter++;
    }

    /**
     * 1120-WRITE-ACCOUNT-TOTALS - Write account totals
     */
    private void writeAccountTotals() {
        String accountTotalLine = String.format("%-100s ACCOUNT TOTAL: %17s", "",
                String.format("%,.2f", wsAccountTotal));
        writeReportRec(padRight(accountTotalLine, 133));
        wsAccountTotal = BigDecimal.ZERO;
        wsLineCounter++;

        writeReportRec(createSeparatorLine());
        wsLineCounter++;
    }

    /**
     * 1110-WRITE-GRAND-TOTALS - Write grand totals
     */
    private void writeGrandTotals() {
        String grandTotalLine = String.format("%-100s GRAND TOTAL: %19s", "",
                String.format("%,.2f", wsGrandTotal));
        writeReportRec(padRight(grandTotalLine, 133));
    }

    /**
     * 1120-WRITE-HEADERS - Write report headers
     */
    private void writeHeaders() {
        // Report name header
        ReportStructures.ReportNameHeader nameHeader = new ReportStructures.ReportNameHeader();
        nameHeader.reptShortName = "CBTRN03C";
        nameHeader.reptLongName = "TRANSACTION DETAIL REPORT";
        nameHeader.reptDateHeader = "DATE RANGE:";
        nameHeader.reptStartDate = wsStartDate;
        nameHeader.reptEndDate = wsEndDate;
        writeReportRec(nameHeader.toLine());
        wsLineCounter++;

        // Blank line
        writeReportRec(WS_BLANK_LINE);
        wsLineCounter++;

        // Transaction header 1
        String header1 = String.format("%-16s %-11s %-4s %-20s %-6s %-30s %-10s %20s",
                "TRANSACTION ID", "ACCOUNT ID", "TYPE", "TYPE DESCRIPTION", 
                "CAT CD", "CATEGORY DESCRIPTION", "SOURCE", "AMOUNT");
        writeReportRec(padRight(header1, 133));
        wsLineCounter++;

        // Separator line (Transaction header 2)
        writeReportRec(createSeparatorLine());
        wsLineCounter++;
    }

    /**
     * 1120-WRITE-DETAIL - Write transaction detail line
     */
    private void writeDetail() {
        ReportStructures.TransactionDetailReport detail = new ReportStructures.TransactionDetailReport();
        
        detail.tranReportTransId = tranRecord.tranId != null ? tranRecord.tranId : "";
        detail.tranReportAccountId = xrefRecord != null ? String.valueOf(xrefRecord.xrefAcctId) : "";
        detail.tranReportTypeCd = tranRecord.tranTypeCd != null ? tranRecord.tranTypeCd : "";
        detail.tranReportTypeDesc = tranTypeRecord != null && tranTypeRecord.tranTypeDesc != null 
                ? tranTypeRecord.tranTypeDesc : "";
        detail.tranReportCatCd = tranRecord.tranCatCd;
        detail.tranReportCatDesc = tranCatRecord != null && tranCatRecord.tranCatTypeDesc != null 
                ? tranCatRecord.tranCatTypeDesc : "";
        detail.tranReportSource = tranRecord.tranSource != null ? tranRecord.tranSource : "";
        detail.tranReportAmt = tranRecord.tranAmt != null 
                ? String.format("%.2f", tranRecord.tranAmt) : "0.00";

        writeReportRec(detail.toLine());
        wsLineCounter++;
    }

    /**
     * 1111-WRITE-REPORT-REC - Write a record to the report file
     */
    private void writeReportRec(String record) {
        try {
            reportWriter.write(record);
            reportWriter.newLine();
        } catch (IOException e) {
            logger.severe("ERROR WRITING REPTFILE: " + e.getMessage());
            abendProgram("ERROR WRITING REPTFILE");
        }
    }

    /**
     * 0000-TRANFILE-OPEN - Open transaction file for input
     */
    private void openTranFile() {
        try {
            tranFileReader = new BufferedReader(new FileReader(tranFilePath));
            logger.info("Opened transaction file: " + tranFilePath);
        } catch (FileNotFoundException e) {
            logger.severe("ERROR OPENING TRANFILE: " + e.getMessage());
            abendProgram("ERROR OPENING TRANFILE");
        }
    }

    /**
     * 0100-REPTFILE-OPEN - Open report file for output
     */
    private void openReportFile() {
        try {
            reportWriter = new BufferedWriter(new FileWriter(reportPath));
            logger.info("Opened report file: " + reportPath);
        } catch (IOException e) {
            logger.severe("ERROR OPENING REPTFILE: " + e.getMessage());
            abendProgram("ERROR OPENING REPTFILE");
        }
    }

    /**
     * 0200-CARDXREF-OPEN - Open card cross-reference file (KSDS - load into HashMap)
     */
    private void openCardXrefFile() {
        cardXrefMap = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(cardXrefPath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                CardXrefRecord record = CardXrefRecord.fromLine(line);
                cardXrefMap.put(record.xrefCardNum, record);
            }
            logger.info("Loaded " + cardXrefMap.size() + " card cross-reference records");
        } catch (IOException e) {
            logger.severe("ERROR OPENING CROSS REF FILE: " + e.getMessage());
            abendProgram("ERROR OPENING CROSS REF FILE");
        }
    }

    /**
     * 0300-TRANTYPE-OPEN - Open transaction type file (KSDS - load into HashMap)
     */
    private void openTranTypeFile() {
        tranTypeMap = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(tranTypePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                TranTypeRecord record = TranTypeRecord.fromLine(line);
                tranTypeMap.put(record.tranType, record);
            }
            logger.info("Loaded " + tranTypeMap.size() + " transaction type records");
        } catch (IOException e) {
            logger.severe("ERROR OPENING TRANSACTION TYPE FILE: " + e.getMessage());
            abendProgram("ERROR OPENING TRANSACTION TYPE FILE");
        }
    }

    /**
     * 0400-TRANCATG-OPEN - Open transaction category file (KSDS - load into HashMap)
     */
    private void openTranCatgFile() {
        tranCatgMap = new HashMap<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(tranCatgPath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                TranCatRecord record = TranCatRecord.fromLine(line);
                String key = record.tranTypeCd + String.format("%04d", record.tranCatCd);
                tranCatgMap.put(key, record);
            }
            logger.info("Loaded " + tranCatgMap.size() + " transaction category records");
        } catch (IOException e) {
            logger.severe("ERROR OPENING TRANSACTION CATG FILE: " + e.getMessage());
            abendProgram("ERROR OPENING TRANSACTION CATG FILE");
        }
    }

    /**
     * 0500-DATEPARM-OPEN - Open date parameters file (handled in readDateParm)
     */
    private void openDateParmFile() {
        // File is opened and read in readDateParm method
        logger.info("Date parameter file path: " + dateParmPath);
    }

    /**
     * 1500-A-LOOKUP-XREF - Lookup card cross-reference record
     */
    private void lookupXref(String cardNum) {
        xrefRecord = cardXrefMap.get(cardNum);
        if (xrefRecord == null) {
            logger.severe("INVALID CARD NUMBER: " + cardNum);
            abendProgram("INVALID CARD NUMBER: " + cardNum);
        }
    }

    /**
     * 1500-B-LOOKUP-TRANTYPE - Lookup transaction type record
     */
    private void lookupTranType(String tranType) {
        tranTypeRecord = tranTypeMap.get(tranType);
        if (tranTypeRecord == null) {
            logger.severe("INVALID TRANSACTION TYPE: " + tranType);
            abendProgram("INVALID TRANSACTION TYPE: " + tranType);
        }
    }

    /**
     * 1500-C-LOOKUP-TRANCATG - Lookup transaction category record
     */
    private void lookupTranCatg(String tranTypeCd, int tranCatCd) {
        String key = tranTypeCd + String.format("%04d", tranCatCd);
        tranCatRecord = tranCatgMap.get(key);
        if (tranCatRecord == null) {
            logger.severe("INVALID TRAN CATG KEY: " + key);
            abendProgram("INVALID TRAN CATG KEY: " + key);
        }
    }

    /**
     * 9000-TRANFILE-CLOSE - Close transaction file
     */
    private void closeTranFile() {
        try {
            if (tranFileReader != null) {
                tranFileReader.close();
                logger.info("Closed transaction file");
            }
        } catch (IOException e) {
            logger.severe("ERROR CLOSING POSTED TRANSACTION FILE: " + e.getMessage());
            abendProgram("ERROR CLOSING POSTED TRANSACTION FILE");
        }
    }

    /**
     * 9100-REPTFILE-CLOSE - Close report file
     */
    private void closeReportFile() {
        try {
            if (reportWriter != null) {
                reportWriter.close();
                logger.info("Closed report file");
            }
        } catch (IOException e) {
            logger.severe("ERROR CLOSING REPORT FILE: " + e.getMessage());
            abendProgram("ERROR CLOSING REPORT FILE");
        }
    }

    /**
     * 9200-CARDXREF-CLOSE - Close card cross-reference file
     */
    private void closeCardXrefFile() {
        cardXrefMap = null;
        logger.info("Closed card cross-reference file");
    }

    /**
     * 9300-TRANTYPE-CLOSE - Close transaction type file
     */
    private void closeTranTypeFile() {
        tranTypeMap = null;
        logger.info("Closed transaction type file");
    }

    /**
     * 9400-TRANCATG-CLOSE - Close transaction category file
     */
    private void closeTranCatgFile() {
        tranCatgMap = null;
        logger.info("Closed transaction category file");
    }

    /**
     * 9500-DATEPARM-CLOSE - Close date parameter file
     */
    private void closeDateParmFile() {
        // File was already closed after reading
        logger.info("Closed date parameter file");
    }

    /**
     * 9999-ABEND-PROGRAM - Abnormal program termination
     */
    private void abendProgram(String reason) {
        logger.severe("ABENDING PROGRAM: " + reason);
        throw new RuntimeException("ABEND: " + reason);
    }

    /**
     * Create separator line for report
     */
    private String createSeparatorLine() {
        return "-".repeat(133);
    }

    /**
     * Pad string to specified length on the right
     */
    private String padRight(String str, int length) {
        if (str == null) {
            return " ".repeat(length);
        }
        if (str.length() >= length) {
            return str.substring(0, length);
        }
        return str + " ".repeat(length - str.length());
    }

    /**
     * Get environment variable with default value
     */
    private static String getEnv(String key, String def) {
        String v = System.getenv(key);
        return (v != null && !v.isEmpty()) ? v : def;
    }

    /**
     * Main method for standalone execution
     */
    public static void main(String[] args) {
        CbTrn03Service service = new CbTrn03Service();
        service.execute();
    }
}