"""
file_writer.py
--------------
Writes converted files to the output directory structure:

converted-usingAgent/
  java/
    records/    <- copybook Java classes
    services/   <- COBOL Java service classes
  python/       <- JCL Python scripts
  tests/
    java/
      records/  <- JUnit tests for record classes
      services/ <- JUnit tests for service classes
    python/     <- pytest tests for Python scripts
  docs/         <- summary docs
"""

import logging
from pathlib import Path
from datetime import datetime

logger = logging.getLogger("FileWriter")


class FileWriter:

    def __init__(self, out_dir: str, clean: bool = False):
        self.out = Path(out_dir)
        if clean and self.out.exists():
            import shutil
            shutil.rmtree(self.out)
            logger.info(f"Cleaned output directory: {self.out}")
        self._create_structure()
        self.written = []

    def _create_structure(self):
        """Creates the full output directory structure."""
        dirs = [
            self.out / "java" / "records",
            self.out / "java" / "services",
            self.out / "python",
            self.out / "tests" / "java" / "records",
            self.out / "tests" / "java" / "services",
            self.out / "tests" / "python",
            self.out / "docs",
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)
        logger.info(f"Output structure created at: {self.out.resolve()}")

    def write_java_record(self, class_name: str, content: str):
        """Writes a Java record class (from copybook) to java/records/"""
        path = self.out / "java" / "records" / f"{class_name}.java"
        self._write(path, content)

    def write_java_service(self, class_name: str, content: str):
        """Writes a Java service class (from COBOL) to java/services/"""
        path = self.out / "java" / "services" / f"{class_name}.java"
        self._write(path, content)

    def write_java_test_record(self, class_name: str, content: str):
        """Writes a JUnit test for a record class to tests/java/records/"""
        path = self.out / "tests" / "java" / "records" / f"{class_name}.java"
        self._write(path, content)

    def write_java_test_service(self, class_name: str, content: str):
        """Writes a JUnit test for a service class to tests/java/services/"""
        path = self.out / "tests" / "java" / "services" / f"{class_name}.java"
        self._write(path, content)

    def write_python(self, script_name: str, content: str):
        """Writes a Python JCL conversion script to python/"""
        path = self.out / "python" / f"{script_name}.py"
        self._write(path, content)

    def write_python_test(self, test_name: str, content: str):
        """Writes a pytest test module to tests/python/"""
        path = self.out / "tests" / "python" / f"{test_name}.py"
        self._write(path, content)

    def _write(self, path: Path, content: str):
        """Writes content to file with header comment."""
        header = self._build_header(path)
        full_content = header + "\n" + content
        path.write_text(full_content, encoding="utf-8")
        file_str = str(path)
        if file_str not in self.written:
            self.written.append(file_str)
        logger.info(f"  Written: {path}")

    def _build_header(self, path: Path) -> str:
        """Builds a file header comment."""
        ext = path.suffix
        ts  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        if ext == ".java":
            return f"// Generated by CardDemo Agentic Converter on {ts}\n// Source: AWS CardDemo (Apache 2.0)\n"
        elif ext == ".py":
            return f"# Generated by CardDemo Agentic Converter on {ts}\n# Source: AWS CardDemo (Apache 2.0)\n"
        return f"// Generated: {ts}\n"

    def print_summary(self):
        """Prints a summary of all written files."""
        logger.info("=" * 60)
        logger.info(f"FILES WRITTEN: {len(self.written)}")
        logger.info("=" * 60)
        for f in self.written:
            logger.info(f"  {f}")
